Expand on Radius presentation page
radius-project/docs pull request #1078
Opened 2024-03-04 20:50 UTC by Reshrahim

Thank you for helping make the Radius documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.radapp.io/community/contributing/docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description
This PR adds some additional details to the presentation page.

## Issue reference

2024-03-04 22:24 UTC, AaronCrawfis requested changes

2024-03-04 22:24 UTC, AaronCrawfis commented on presentation-pack/Radius.potx
The Call to Action slide formatting is a little off: 
![image](https://github.com/radius-project/docs/assets/54363786/6834dcb6-9bd8-4985-99ec-95d431a7abc1)

Instead of bullets, can we instead update the following slide? 
![image](https://github.com/radius-project/docs/assets/54363786/dbb9abe0-c882-46d1-886c-921ad11cdf1a). In a presentation we usually try to avoid giving more than 3 calls to action, as realistically the audience can't click/bookmark/take a picture of everything.

All links should be visible and not hyperlink embedded text, as you should assume this presentation is given on a projector in the front of the room where people can't click the links.

Overall maybe we just need to add a slide on the community calls, and then rely on the existing call to action slide?

2024-03-05 16:21 UTC, Reshrahim commented on presentation-pack/Radius.potx
U mean add a slide for Radius slide for Community like below
<img width="611" alt="image" src="https://github.com/radius-project/docs/assets/61033581/3e21a15c-2490-46fd-9a7c-97447c9c14d7">

And then rely on the existing last slide for other call to action ?

2024-03-05 22:15 UTC, Reshrahim commented on presentation-pack/Radius.potx
As discussed, added a slide for community and retained the existing slide as call to action

2024-03-11 16:16 UTC, jasonviviano approved these changes
LGTM

2024-03-20 20:07 UTC, AaronCrawfis approved these changes

2024-03-20 20:11 UTC, merged