Add enableWebsockets property to the gateway snippet
radius-project/docs pull request #1125
Opened 2024-06-04 10:56 UTC by ytimocin

Thank you for helping make the Radius documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.radapp.io/community/contributing/docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Add **enableWebsockets** property to the gateway snippet

## Issue reference

Fixes: #[issue number]
or
Fixes: https://github.com/radius-project/radius/issues/[issue number]

2024-06-04 15:07 UTC, lakshmimsft commented
based on the update, do we need an entry in table https://docs.radapp.io/reference/resource-schema/core-schema/gateway/#properties ?

2024-06-04 16:13 UTC, willtsai requested changes
@lakshmimsft left this as a comment too, but please add an entry to further describe the field in the table here: https://docs.radapp.io/reference/resource-schema/core-schema/gateway/#properties

2024-06-04 23:05 UTC, lakshmimsft approved these changes

2024-06-06 16:10 UTC, willtsai approved these changes

2024-06-06 16:12 UTC, merged