Create Local quickstart
radius-project/docs pull request #139
Opened 2022-06-22 17:11 UTC by jasonviviano

## Description
Creates a local quickstart document to close https://github.com/project-radius/docs/issues/102

1. Created a basic hello world NodeJS application for the quickstart
2. Walked through prerequisites
3. Sample creation
4. Local environment creation
5. Radius application initialization
6.  Running locally
7.   Accessing application.

2022-07-07 21:02 UTC, emily-potyraj requested changes
Jason, this quickstart is awesome! I think we talked about it a bit in a PM docs review meeting, but I think we've also had some dev changes in the last couple weeks. 

We've been throwing things off the boat to migrate, test, and document a couple fewer workflows for v0.12, and we expect local dev CLI commands to be a fast follow.

I think we should merge this quickstart in so we have it in our docs repo (like our local dev CLI command files are still in the radius repo) and we can hide it for now (like the CLI commands are being hidden). Easy enough to remove the flags for both when we're ready. 

Again, great work, and thanks for being so thoughful about how to teach these concepts. It's a really succinct flow that feels intuitive.

2022-07-07 21:02 UTC, emily-potyraj commented on docs/content/getting-started/quickstarts/local-development/index.md
> +weight: 400
```suggestion
weight: 400
toc_hide: true
hide_summary: true
```

In general, porting local dev workflows to the new rp got pushed to v0.12.1 (or maybe v0.13) in the interest of having 1 fewer workflows to test out for v0.12 :/ 
Let's just hide this quickstart for now and enable it when the local dev CLI commands are ported to the new rp.

2022-07-22 22:42 UTC, emily-potyraj approved these changes
approving because we wanted these changes to land (hidden) for us to un-hide in v0.13. But let's get this PR closed since we love the content.

2022-08-16 18:41 UTC, jasonviviano commented
Closing as local dev isn't in scope anymore.

2022-08-16 18:41 UTC, closed without merging