Incremental update to connector doc
radius-project/docs pull request #150
Opened 2022-07-01 19:19 UTC by ihood

Added intro paragraph and example paragraph. Connector page still needs formatting and additional sections (as indicated by TODOs).

Addresses, but not closes, #147

2022-07-01 23:29 UTC, emily-potyraj commented
looking great! I really like the new text. I think it's both clear but also succinct. 
hope it's ok, I added in an example bicep file based on some of the hot-off-the-press tests the eng team are writing.

2022-07-07 20:51 UTC, emily-potyraj commented
@ihood - I think all that's left here is the first image on the page, right?

2022-07-08 19:46 UTC, ihood reviewed
added picture

2022-07-08 19:46 UTC, ihood commented on docs/content/concepts/defining-an-app/connectors-model/_index.md
> +TODO: insert image here
<img width="286" alt="connectors" src="https://user-images.githubusercontent.com/71398878/178064004-458b7f2f-df7d-4e16-b5c9-2e5263272416.png">

2022-07-08 20:00 UTC, emily-potyraj commented on docs/content/concepts/defining-an-app/connectors-model/_index.md
> +TODO: insert image here
I like this image. 

Can you please add a separate new file for the image that this page references? We've been doing that to make sure we have a high quality version of each image saved. 
(For an example, see this directory: https://github.com/project-radius/docs/tree/0df5f25b2fa322facb10b276e9adb286c562b50b/docs/content/concepts/defining-an-app/app-model-overview)

2022-07-08 20:17 UTC, ihood commented on docs/content/concepts/defining-an-app/connectors-model/_index.md
> +TODO: insert image here
Did I do that right?

2022-07-08 20:34 UTC, AaronCrawfis requested changes

2022-07-08 20:34 UTC, AaronCrawfis commented on docs/content/concepts/defining-an-app/connectors-model/_index.md
> +<img width="578" alt="Screen Shot 2022-07-01 at 12 13 43 PM" src="https://user-images.githubusercontent.com/71398878/176956322-63cb7be6-4c51-4e2d-bf6a-143f817a89c7.png">
```suggestion
<img width="578" alt="Diagram showing a connector abstraction that connects to an infrastructure resource" src="connectors.png">
```

2022-07-08 20:34 UTC, AaronCrawfis commented on docs/content/concepts/defining-an-app/connectors-model/_index.md
> +<h4>Underlying resource</h4>
Use markdown h4 (####) instead of html h4.

Also don't use an H4 without first using an H2 and H3 above it

2022-07-08 20:34 UTC, AaronCrawfis commented on docs/content/concepts/defining-an-app/connectors-model/_index.md
> +<h4>Connector</h4>
See above note

2022-07-08 20:34 UTC, AaronCrawfis commented on docs/content/concepts/defining-an-app/connectors-model/_index.md
> +
```suggestion
```

Double blank line

2022-07-08 20:34 UTC, AaronCrawfis commented on docs/content/concepts/defining-an-app/connectors-model/_index.md
> +<h4>Container</h4>
See above note

2022-07-08 20:34 UTC, AaronCrawfis commented on docs/content/concepts/defining-an-app/connectors-model/snippets/corerp-connector-example.bicep
> +  location: 'global'
We should be using the parameter above instead of manually defining this

2022-07-08 20:35 UTC, AaronCrawfis commented on docs/content/concepts/defining-an-app/connectors-model/_index.md
> +TODO: insert image here
You'll need to have `connectors.png` in both the parent directory and the child directory, which each page pointing to their respective image

2022-07-11 17:38 UTC, merged

2022-07-20 19:04 UTC, emily-potyraj commented on docs/content/concepts/defining-an-app/connectors-model/snippets/corerp-connector-example.bicep
> +  location: 'global'
`location: 'global'` ---> `resourceGroup().location`