page reorg, especially of the reference schemas
radius-project/docs pull request #151
Opened 2022-07-02 00:31 UTC by emily-potyraj

- pull connector schemas out of nested folders. 
- hide 2 connector types that aren't available at v0.12 (dapr secretstore, extenders)
- pull overview pages out of resources folder and use resource schema pages directly as the main info pages
- move resource schema section to dev guides
- make concepts tree flatter

2022-07-06 00:15 UTC, ihood commented on docs/content/author-apps/resource-schema/core-schema/gateway/index.md
> +`Gateway` defines how requests are routed to different resources, and also provides the ability to expose traffic to the internet. Conceptually, gateways allow you to have a single point of entry for
```suggestion
`Gateway` defines how requests are routed to different resources and provides the ability to expose traffic to the internet. Conceptually, gateways allow you to have a single point of entry for traffic in your application, whether it be internal or external traffic.
```

2022-07-06 00:15 UTC, ihood commented on docs/content/author-apps/resource-schema/core-schema/httproute/index.md
> +An `HttpRoute` resources defines HTTP communication between two services. They can be used to define both one-way communication, as well as cycles of communication between services.
```suggestion
An `HttpRoute` resources defines HTTP communication between two services. They can be used to define both one-way communication and cycles of communication between services.
```

2022-07-06 00:15 UTC, ihood commented on docs/content/concepts/_index.md
> +- Iterate quickly in a local dev environment, then scale that same app up in Azure or Kubernetes.
Do we want to remove Azure from here for now since we retired 'rad env init azure'? Until Azure managed service is released?

2022-07-06 00:15 UTC, ihood commented on docs/content/concepts/_index.md
> +Our current focus is on delivering robust support for Azure, Kubernetes, and AWS.
Maybe ordering with cloud providers tg then Kubernetes? 'Azure, AWS, and Kubernetes'

2022-07-06 20:30 UTC, emily-potyraj commented
also changed headers of Concepts sections to be more about the phase of the workflow than about the Radius item (e.g. deployment vs. control plane)

2022-07-06 20:34 UTC, emily-potyraj commented
moved a todo item to a new issue: https://github.com/project-radius/docs/issues/157

2022-07-08 20:57 UTC, AaronCrawfis requested changes
I think this PR needs some further thought. We need to think of three main categories and how docs fit into them.

1. Concepts - teach the why and what of Project Radius. The concept docs introduce a new user to Radius, and teach advanced concepts to existing users when they want to dig in further.
1. Feature pages - sell the user on the capabilities and features of Radius. Show _what the user can do with Radius_.
2. Reference docs - A quick lookup to see schemas/property values/limitations/etc. for Radius resources/CLI/etc. Referenced by users already familiar with Radius and wanting to lookup a concept/feature they already know about

2022-07-08 20:57 UTC, AaronCrawfis commented on docs/layouts/partials/sidebar-tree.html
> +{{ $pages := where $s.Pages ".Params.toc_hide" "!=" true -}}
Could you elaborate on what changes you're making here?

2022-07-08 20:57 UTC, AaronCrawfis commented on docs/content/author-apps/resource-schema/azure-resources/index.md
>  {{< tabs Bicep >}}
I think the resource schemas should remain under reference instead of being pulled into authoring apps. These pages are supposed to be a quick technical reference. They also should be automatically generated (on the backlog). 

They are not meant to teach what these resources _are_. Those docs are the resource library that present categories, features and capabilities.

2022-07-08 21:09 UTC, Reshrahim commented on docs/content/concepts/_index.md
> +Welcome to Project Radius!
I think we should follow the same structure for all the top menu landing pages (Concepts, getting started , Admin guides etc). The landing page should have a light inro to the section followed by links to sub-sections 

This content can be dumped into a subsection "Why Radius" under Concepts

2022-07-08 21:13 UTC, Reshrahim commented on docs/content/concepts/app-model-overview/_index.md
> +<!-- fyi - old notes pulled out of retired pages. for when this page gets cleaned up. -->
Based on the comment, do we want to clean this up later?

2022-07-08 21:15 UTC, Reshrahim commented on docs/content/concepts/app-model-overview/_index.md
>  {{< card header="**Direct Connection**" >}}
I guess we shd follow the same way of calling connections as Direct connections everywhere

2022-07-08 21:15 UTC, Reshrahim commented on docs/content/concepts/connections-model/_index.md
> +title: "Connections"
Direct connections?

2022-08-05 18:45 UTC, emily-potyraj commented
grabbed the changes I want from this PR into a new PR. retiring this one.

2022-08-05 18:45 UTC, closed without merging