Remove CustomRP bicep validation
radius-project/docs pull request #163
Opened 2022-07-08 21:29 UTC by willdavsmith

* Removing CustomRP-based bicep validation

Closes: #161 

Note: this PR will fail checks until all CustomRP-based bicep files have been removed from the repo.

2022-07-08 21:36 UTC, AaronCrawfis approved these changes

2022-07-08 21:51 UTC, emily-potyraj requested changes
sorry, let's hold off on merging this until we come to a consensus, esp matching what we're doing in the radius repo. thanks for the brainstorms here!

2022-07-11 14:56 UTC, AaronCrawfis commented
Now that #164 is open for review, and it doesn't use the prefix, let's revisit this PR and get it though today if possible.

2022-07-11 20:06 UTC, AaronCrawfis commented
Closing in favor of #167

2022-07-11 20:06 UTC, closed without merging