Update concept docs
radius-project/docs pull request #168
Opened 2022-07-12 16:27 UTC by AaronCrawfis

## Overview

This PR updates the concepts section of the Project Radius docs. It overall addresses these areas:

- Typos and grammatical errors
- Incomplete sections and TODO statements
- Removes any references to features that are not currently planned for public preview
- Updates structure to keep every page at most 2 levels deep in the tree

## Specific updates

### Overview

The overview section has been updated to more closely match the updated Project Radius Product Deck. Diagrams, wording, and order have all been updated.

### App model

The "define an app" section has been consolidated into an "App model" section which covers the app model resources and connections. Examples have been updated to reflect this new structure.

### Portability

Connectors content has been placed into a portability section, to best reflect the problem statement instead of the feature name. In the future this page can be updated to reflect other container runtimes such as Azure App Platform and HashiCorp Nomad, once implemented.

### Environments

The environments section has been updated to remove features and capabilities that have not been implemented or planned. In their place are current features and planned features.

### Architecture

"Control-plane" has been renamed to architecture, without any other changes.

2022-07-12 17:25 UTC, emily-potyraj requested changes
I have more notes here, but one big item is that we need to keep the environments page as it was in edge previously. That page has already gone through _extensive_ review with Radius leadership (including Mark and Ryan W). 
We should add a note to the top of the page that that page is forward-looking, but we have decided as a group about how we wanted to frame the environments concept. 
Can you please make that change?

2022-07-12 17:29 UTC, AaronCrawfis commented
> 

Let's discuss in the PM meeting today. We haven't designed any of the features that were listed in the environments page, and trying to sell them as features of Radius environments would be selling large inaccuracies. With features we already have a good idea about, such as Recipes, it makes sense to include it in the page and put an "in progress" disclaimer there. But the rest I have huge reservations about including. Had I been in the meetings where this was previously discussed I would have voiced my concern then.

2022-07-12 17:35 UTC, emily-potyraj commented
> Connectors content has been placed into a portability section, to best reflect the problem statement instead of the feature name. In the future this page can be updated to reflect other container runtimes such as Azure App Platform and HashiCorp Nomad, once implemented.

I don't think we should make this change at this point. Let's change it back to "Connectors."
We already concluded with Mark that equating connectors == portability is missing an opportunity to talk about connectors' other value props. Plus, I'm not sure we want to bucket connectors, Azure App Platform, and HashiCorp Nomad in a group together. From feedback on the Radius product deck, we've been getting great traction focusing on connectors as their own concept.

2022-07-13 14:39 UTC, AaronCrawfis commented
Updated PR to make concepts higher-level and specify that many of the concerns are still coming soon.

Also removed the portability page to later be replaced with #166

2022-07-22 21:14 UTC, Reshrahim commented on docs/content/concepts/environments-concept/_index.md
> +Environments provide a grouping structure for applications and the resources they share. For example, an org might choose to setup separate Radius environments for staging and production. When approp
Do shared resources mentioned here represent other resources like database/cache?

2022-07-22 21:17 UTC, Reshrahim commented on docs/content/concepts/environments-concept/_index.md
>  ## Concerns that environments manage
The below revamp doesn't depict concerns but rather talks about what areas they can manage with environments

2022-07-22 21:24 UTC, Reshrahim commented on docs/content/concepts/environments-concept/_index.md
> +   - Connector recipes are defined for how to deploy and configure infrastructure resources, such as for a Redis cache connector
Recipes are not available for v.12. Shouldn't this be just in the context of what's available today?

2022-07-22 21:32 UTC, Reshrahim commented on docs/content/concepts/overview/_index.md
> +- Iterate quickly in a local dev environment, then scale that same app up in Azure or Kubernetes environment
It's not Azure/ Kubernetes environment anymore. Can we say this as "scale that same app up in staging/ production environment"

2022-07-25 16:43 UTC, AaronCrawfis commented on docs/content/concepts/environments-concept/_index.md
> +Environments provide a grouping structure for applications and the resources they share. For example, an org might choose to setup separate Radius environments for staging and production. When approp
Today shared resources can only be connectors that are scoped to the environment without an application defined.

In the future we'll have other resources be able to be scoped to the environment for applications  to leverage. However that feature is still being defined.

2022-07-25 16:45 UTC, AaronCrawfis commented on docs/content/concepts/environments-concept/_index.md
> +   - Connector recipes are defined for how to deploy and configure infrastructure resources, such as for a Redis cache connector
Good catch, will update

2022-07-25 19:16 UTC, AaronCrawfis commented on docs/content/concepts/environments-concept/_index.md
>  ## Concerns that environments manage
Great callout. Updated page with clearer concerns vs. features callouts

2022-07-26 13:02 UTC, emily-potyraj reviewed
Looking good. Thanks for wrangling all the suggestions and changes here based on our 3.5 months of learnings! 
My suggestions and notes are pretty straight forward - nothing major about restructuring. Thanks for bringing in so much of the deck's language and visuals.

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/appmodel-concept/_index.md
> +{{% alert title="💡 Key concept" color="info" %}}
nit: I vote to make these key concepts just be regular text (not alerts) for readability. We've generally moved away from them in our docs. I think they're just used here and on the connections model page.
not a hill for me to die on tho :)

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/appmodel-concept/snippets/app-connections.bicep
>  param location string = resourceGroup().location
Does this example bicep follow our latest best practices for `location`? I thought we needed to have `location: 'global'` for Containers, no?

And why doesn't the `blobContainer` resource require a location?

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/appmodel-concept/_index.md
> +{{< rad file="snippets/app-resources.bicep" embed="true" >}}
I really like the addition of this snippet

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/architecture/index.md
>  description: Learn how the Project Radius control-plane services deploy and manage your applications
I'm ok with the change to move from "Control Plane" to "Architecture," but I think we should consider this to be a naming piece of our concepts that we're still iterating on. To me, "Architecture" doesn't match the description, but we can adjust our framing as we learn more during Private Preview.

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/connectors-concept/_index.md
> +In the app definition, a developer defines a Mongo connector (`dbconnector`) that references the CosmosDB resource.
do you want to switch this sentence away from parens to commas like you did for the Container section?

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/connectors-concept/_index.md
> +## Supported connectors
this section is a good addition

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/environments-concept/_index.md
> -Additionally, environments can be leveraged to realize organizational best practices.
I think this is one of our catchphrases we should try to fit in somewhere. Right now the Intro blurb on this page doesn't say anything about "best practices" or similar keyword that hints at templating. 

Maybe if we want to describe current state but give a nod to future state it could be something like

"In the future, users will be able to leverage environment templates to realize organizational best practices."

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/environments-concept/_index.md
> +With Radius environments, central operations and IT teams can define and share environments with development teams for them to deploy applications into. Ops teams focus on configuring the compute, de
```suggestion
With Radius environments, central operations and IT teams can define and share environments with development teams for them to deploy applications into. Ops teams focus on configuring the compute, dependencies, networking, and other infrastructure concerns, while developers focus on the business and application concerns. This allows each team to focus on what matters most to them, without needing to become experts in every aspect of the infrastructure and application.
```

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/environments-concept/_index.md
> -In some cases, a full stack developer might write the app code, write the Radius app defintion, and create the Radius environment. However, in some orgs, administrators might build environment templa
This sentence was one of the ones we typed together word for word in the Mark review of this page :)
I think we need to find a place for this blurb somewhere on this page. I think it would go well at the very start of your Handoffs between teams section before the example.

We decided as a group that we didn't have anything acknowledging that we support a range of organizational models. One of the projects we need to do after v0.12 is build a mapping of the different org models/frameworks/divisions of labor we see.

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/environments-concept/_index.md
> +## Example: Handoff between teams
fyi since you were OOO - Mark and Ryan W explicitly requested we have more callouts about the handoffs (generally in our docs and on this specific page).

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/environments-concept/_index.md
> +{{< cardpane >}}
I like the "coming soon" labels and the content looks good for v0.12, but I personally find the cards a bit chaotic to read since we have so many here. Suggest switching to a table for readability.

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/environments-concept/_index.md
> +<img src="env-with-apps-example.png" alt="Diagram of multiple Radius environments deployed to Azure. One environment contains 1 app, the other environment contains multiple apps." width="350px" />
what do we think about switching the text on this image from "Environment" to "Radius environment"?

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/overview/_index.md
> +<img alt="Diagram showing all of the technologies needed to model an application today" src="cloud-apps-today.png" width="600px" />
I think we should remove this image and the next one. It feels like we're blasting people a bit too hard on the current state as the very first thing. If we wanted to expand on current state problems more, let's do it "below the fold" and get to our point about RADIUS IS AWESOME really fast on this page. Assume somebody is giving us 5 seconds.

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/overview/_index.md
> +At the heart of Project Radius is a new **application resource**, with an accompanying set of resources and abstractions to describe your app's requirements and capabilities. These resources form the
```suggestion
At the heart of Project Radius is a new **application resource**, with an accompanying set of resources and abstractions to describe your app's requirements and capabilities.
```

we need to slowly move away from "app model" term

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/overview/_index.md
> +These new resources form the **Radius app model**, which allow you to:
```suggestion
[Defining your app]({{< ref appmodel-concept >}}) in Radius allows you to:
```

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/overview/_index.md
> +The result is no longer just a flat list of resources - it's a fully fledged diagram of how the pieces relate to each other:
```suggestion
The result is no longer just a flat list of resources - it's a fully codified abstraction of how the components relate to each other:
```
hoping to hit more than the visualization side

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/overview/_index.md
> +[App environments]({{< ref environments-concept >}}) act as a landing zone for applications. They are the place where you can deploy, manage, and scale your apps.
```suggestion
[App environments]({{< ref environments-concept >}}) are landing zones for applications. They are the place where you can deploy, manage, and scale your apps.
```

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/overview/_index.md
> +{{< rad file="snippets/appmodel-concept.bicep" embed=true >}}
do we think this page would be just as effective without this snippet? I feel like the code is suddenly 201 level in a 101 level page. If we want a visual here, I think a diagram would be more easily digestible.

2022-07-26 13:02 UTC, emily-potyraj commented on docs/content/concepts/overview/_index.md
> +## Platform strategy
Let's add a little bit more about portability here. 
And how we support multiple platforms and, even if no apps are moving, orgs that use multiple clouds can now have tooling consistency. 

^ We explicitly need to scatter more language about "tooling consistency" in our docs with the v0.12 refresh generally.

2022-07-26 19:59 UTC, AaronCrawfis commented on docs/content/concepts/appmodel-concept/_index.md
> +{{% alert title="💡 Key concept" color="info" %}}
I agree. Will update, was a remnant of the OG readme.md file

2022-07-26 20:02 UTC, AaronCrawfis commented on docs/content/concepts/appmodel-concept/snippets/app-connections.bicep
>  param location string = resourceGroup().location
Not yet, will tackle the new `location` convention in a separate PR where I'll do a giant find/replace.

Also great catch, there should have been an `existing` keyword there instead of declaring a new resource

2022-07-26 20:03 UTC, AaronCrawfis commented on docs/content/concepts/appmodel-concept/_index.md
> +{{% alert title="💡 Key concept" color="info" %}}
Will keep the definition alerts for now though, unless you want to inline those as well

2022-07-26 20:04 UTC, AaronCrawfis commented on docs/content/concepts/architecture/index.md
>  description: Learn how the Project Radius control-plane services deploy and manage your applications
100% agree. Opened #210 to track the use of control-plane also based on @ryanwaite feedback

2022-07-26 20:06 UTC, AaronCrawfis commented on docs/content/concepts/connectors-concept/_index.md
> +In the app definition, a developer defines a Mongo connector (`dbconnector`) that references the CosmosDB resource.
Great consistency check, thanks!!

2022-07-26 20:07 UTC, AaronCrawfis commented on docs/content/concepts/environments-concept/_index.md
> +With Radius environments, central operations and IT teams can define and share environments with development teams for them to deploy applications into. Ops teams focus on configuring the compute, de
Will catch with larger commit, thanks!

2022-07-26 20:08 UTC, AaronCrawfis commented on docs/content/concepts/environments-concept/_index.md
> +## Example: Handoff between teams
Awesome! Anything in particular we want to add now? Once we ship recipes this section will have a lot more amazing content, as well as once we ship environment templates.

2022-07-26 20:15 UTC, AaronCrawfis commented on docs/content/concepts/overview/_index.md
> +<img alt="Diagram showing all of the technologies needed to model an application today" src="cloud-apps-today.png" width="600px" />
Agree on removing the second image, took up too much real estate.

On the first image, thoughts on keeping it to show a clear before/after comparison between the old model and the new Radius model? This slide has been landing well with customer pitches, and I want to make sure we properly land the "why we need Radius" punch.

I can also make a slimmed down version of the image if we want to show the technologies without all the resources inside of it

2022-07-26 20:23 UTC, AaronCrawfis commented on docs/content/concepts/overview/_index.md
> +At the heart of Project Radius is a new **application resource**, with an accompanying set of resources and abstractions to describe your app's requirements and capabilities. These resources form the
I agree for the pitch deck it makes sense to not mention "app model" right now because it doesn't have broad meaning. However, I want to dive into this a little more for our concept/product docs. We have the opportunity to define "app model" and give it meaning. I see the lack of an industry standard "app model" definition as a **net positive thing for us**, because it gives us the power to define it and give it meaning.

2022-07-26 20:24 UTC, AaronCrawfis commented on docs/content/concepts/overview/_index.md
> +These new resources form the **Radius app model**, which allow you to:
Grabbing as one big commit

2022-07-26 20:27 UTC, AaronCrawfis commented on docs/content/concepts/overview/_index.md
> +{{< rad file="snippets/appmodel-concept.bicep" embed=true >}}
You're right this is much too complicated. Let me take a crack at making it simpler. If we're calling out "model applications as code" I think it's important to show some code.

2022-07-26 20:44 UTC, AaronCrawfis commented on docs/content/concepts/overview/_index.md
> +## Platform strategy
Great idea. Just added some content. Lemme know what you think

2022-07-26 20:54 UTC, AaronCrawfis commented on docs/content/concepts/environments-concept/_index.md
> -Additionally, environments can be leveraged to realize organizational best practices.
Added a sentence. Good suggestion!

2022-07-26 20:54 UTC, AaronCrawfis commented on docs/content/concepts/environments-concept/_index.md
> -In some cases, a full stack developer might write the app code, write the Radius app defintion, and create the Radius environment. However, in some orgs, administrators might build environment templa
Missed that context, will reincorporate

2022-07-26 21:54 UTC, emily-potyraj commented on docs/content/concepts/appmodel-concept/_index.md
> +{{% alert title="💡 Key concept" color="info" %}}
sounds great

2022-07-26 21:58 UTC, emily-potyraj commented on docs/content/concepts/environments-concept/_index.md
> +## Example: Handoff between teams
I think it's good for now just to have this callout and the suggestion of handoffs during the tutorial. cc @Reshrahim @jasonviviano @ihood in case they had any other ideas.

2022-07-26 22:04 UTC, emily-potyraj commented on docs/content/concepts/overview/_index.md
> +{{< rad file="snippets/appmodel-concept.bicep" embed=true >}}
not sure if I looked at this while it's still WIP, but I like the current one (as of fcf2394) with the explanatory comment lines. You did a really good job simplifying it, and I think those comments will help users realize what they should be focusing on.

2022-07-27 20:00 UTC, Reshrahim commented on docs/content/concepts/environments-concept/_index.md
> +With Radius environments, central operations and IT teams can define and share environments with development teams for them to deploy applications into. Ops teams focus on configuring the compute, de
I would really like us to use the same persona reference throughout the docs for consistency. I referenced the two personas as developer and infrastructure administrator in tutorial. 

Which one do we go with - operator or infrastructure admin?

2022-07-27 20:08 UTC, Reshrahim commented on docs/content/concepts/environments-concept/_index.md
> +## Example: Handoff between teams
I like the flow of the handoffs. One comment that I added is for us to decide on how we reference personas throughout the docs- should we use operator or infra-admin ?

2022-07-28 00:11 UTC, emily-potyraj submitted a review, later dismissed
@AaronCrawfis did you have any other changes in mind here? LGTM

2022-07-28 22:42 UTC, AaronCrawfis commented on docs/content/concepts/environments-concept/_index.md
> +With Radius environments, central operations and IT teams can define and share environments with development teams for them to deploy applications into. Ops teams focus on configuring the compute, de
Great callout. Switched to "central operations" for consistency to tie it together

2022-07-28 22:45 UTC, merged