Container-app cleanup
radius-project/docs pull request #183
Opened 2022-07-18 19:00 UTC by jasonviviano

## Description

Moving the container app to the reference section, original resting place was in the new quickstart section.

## Issue
#101

2022-07-19 20:54 UTC, AaronCrawfis requested changes
Let's remove all of the step-by-step guides as they contain mostly local dev content, and instead have a one page overview of the reference app and a button link to the samples repo. See https://wonderful-plant-020417a1e-164.westus2.azurestaticapps.net/getting-started/reference-apps/eshop/ for an example

2022-07-21 17:06 UTC, jasonviviano commented
> Let's remove all of the step-by-step guides as they contain mostly local dev content, and instead have a one page overview of the reference app and a button link to the samples repo. See https://wonderful-plant-020417a1e-164.westus2.azurestaticapps.net/getting-started/reference-apps/eshop/ for an example

Let me know if this version makes sense!

2022-07-21 20:44 UTC, emily-potyraj reviewed
Love it! It's looking great. Just had 2 minor suggestions.

2022-07-21 20:44 UTC, emily-potyraj commented on docs/content/getting-started/reference-apps/container-app-store/_index.md
> +*The python-app is a Python flask app that will retrieve and store the state of orders. It uses > Dapr state management to store the state of the orders. When deployed in Container Apps, Dapr is conf
did we mean for this line to be in italics?

2022-07-21 20:44 UTC, emily-potyraj commented on docs/content/getting-started/reference-apps/container-app-store/_index.md
> +{{< button text="View container app store reference app in samples" link="https://github.com/project-radius/samples" color="success" size="btn-lg" >}}
```suggestion
{{< button text="View container app store reference app in samples" link="https://github.com/project-radius/samples/tree/v0.11/reference-apps/container-app-store" color="success" size="btn-lg" >}}
```

suggest linking directly to the CAS sample app's page

2022-07-21 21:18 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/container-app-store/_index.md
> +{{< button text="View container app store reference app in samples" link="https://github.com/project-radius/samples" color="success" size="btn-lg" >}}
The main issue here is that we will be linking to a versioned directory which will need to be updated every release. Linking to the repo will ensure the user always gets the latest stable release.

There is a way to parameterize the version, although because it would be within an existing Hugo shortcode I'm not sure it will work. I'll test it out

2022-07-21 21:18 UTC, AaronCrawfis submitted a review, later dismissed

2022-07-21 21:20 UTC, emily-potyraj commented on docs/content/getting-started/reference-apps/container-app-store/_index.md
> +{{< button text="View container app store reference app in samples" link="https://github.com/project-radius/samples" color="success" size="btn-lg" >}}
fyi Dapr just points users to the edge branch e.g. `https://github.com/dapr/quickstarts/tree/master/tutorials/pub-sub`

2022-07-21 22:42 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/container-app-store/_index.md
> +{{< button text="View container app store reference app in samples" link="https://github.com/project-radius/samples" color="success" size="btn-lg" >}}
Added a shortcode update so that we link to the proper `version` which is set in `config.toml`

2022-07-21 22:42 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/container-app-store/_index.md
> +*The python-app is a Python flask app that will retrieve and store the state of orders. It uses > Dapr state management to store the state of the orders. When deployed in Container Apps, Dapr is conf
```suggestion
The python-app is a Python flask app that will retrieve and store the state of orders. It uses Dapr state management to store the state of the orders. When deployed in Container Apps, Dapr is configured to point to a mongoDB to back the state.
```

2022-07-21 22:54 UTC, AaronCrawfis approved these changes

2022-07-21 23:23 UTC, merged