Added codespace section and Next steps to getting started page
radius-project/docs pull request #186
Opened 2022-07-20 19:44 UTC by jasonviviano

## Description

Just added a codespace section as agreed that currently adding a small tutorial might be too heavy for the main getting started page and a table connecting the page with its sub-pages for users to clearly see what the next steps are.

## Issue

#109

2022-07-20 20:26 UTC, AaronCrawfis requested changes

2022-07-20 20:26 UTC, AaronCrawfis commented on docs/content/getting-started/_index.md
> +If you're running into any difficulties or would prefer to test out Radius in a virtual environment first check out the [official Radius samples repo](https://github.com/project-radius/samples) and t
I'd try and sell Codespaces as a positive instead of framing it as a solution to a negative. "If you're running into any difficulties" makes it sounds like this is a fallback option or workaround.

2022-07-20 20:26 UTC, AaronCrawfis commented on docs/content/getting-started/_index.md
> +The environment comes pre-configured with everything you need to run Radius, as well as a post-command dedicated to creating a [Radius local environment](#create-a-radius-environment).
I wouldn't talk about the implementation details like post-create-commands. Instead, frame it as "automatically creates a Radius environment for you".

2022-07-20 20:26 UTC, AaronCrawfis commented on docs/content/getting-started/_index.md
> +| [Tutorial]({{< ref tutorial >}}) | Hit the ground running with our Radius tutorial, complete with code samples aimed to get you started quickly with Radius |
I'd have tutorial first in the list instead of last

2022-07-20 20:26 UTC, AaronCrawfis commented on docs/content/getting-started/_index.md
> +## Try out Radius on GitHub Codespaces
One challenge with Codespaces is we only have 100 seats available (although we _might_ be able to go over that.

We will need to include a link on how to get access to the GitHub organization for those who don't have access (currently only 80 people out of the ~400 have access)

2022-07-20 20:43 UTC, jasonviviano commented on docs/content/getting-started/_index.md
> +## Try out Radius on GitHub Codespaces
What kind of link are you thinking? I don't seem to have access to look at the collaborator settings  for the repo so I'm not sure what the best option would be.

2022-07-20 21:11 UTC, ihood reviewed
Jason! Codespaces are so cool! Left a couple comments/suggestions

2022-07-20 21:11 UTC, ihood commented on docs/content/getting-started/_index.md
> +Do you prefer to test out Radius in a fast and easy to use virtual environment? Check out the [official Radius samples repo](https://github.com/project-radius/samples) and test out the sample applica
```suggestion
Do you prefer to test out Radius in a fast and easy-to-use virtual environment? Check out the [official Radius samples repo](https://github.com/project-radius/samples) and test out the sample applications on a pre-configured [GitHub Codespaces](https://github.com/features/codespaces) container.
```

2022-07-20 21:11 UTC, ihood commented on docs/content/getting-started/_index.md
> +| [Quickstarts]({{< ref quickstarts >}}) | Learn about Project Radius topics via quickstart guides, complete with code samples |
I think the difference between tutorials and quickstarts could be called out more. Right now, their descriptions feel a little too similar (both have code samples, 'started quickly' vs 'Quickstarts')

2022-07-20 21:40 UTC, jasonviviano commented on docs/content/getting-started/_index.md
> +| [Quickstarts]({{< ref quickstarts >}}) | Learn about Project Radius topics via quickstart guides, complete with code samples |
True, however its tricky since those are the official descriptions we have for them on their pages. I think if we change them here we'd have to change them there as well.

2022-07-20 23:33 UTC, jasonviviano commented on docs/content/getting-started/_index.md
> +## Try out Radius on GitHub Codespaces
Added the Radius form but not sure if that's what you're referring to @AaronCrawfis

2022-07-21 20:47 UTC, emily-potyraj commented on docs/content/getting-started/_index.md
> +| [Quickstarts]({{< ref quickstarts >}}) | Learn about Project Radius topics via quickstart guides, complete with code samples |
What if we change the language just for the Tutorial? This suggestion rips off the way Dapr describes their tutorial. 

Tutorial summary: "Walk through an in-depth example to learn more about how to work with Radius concepts"
for both this table and on the Tutorial page itself.

2022-07-21 20:54 UTC, emily-potyraj reviewed
Great job, Jason! Thanks for helping organize all our thoughts around what the user's first experience should be on this page. Only had a few tiny readability suggestions.

2022-07-21 20:54 UTC, emily-potyraj commented on docs/content/getting-started/_index.md
> +## Try out Radius on GitHub Codespaces
LGTM in its current state.

2022-07-21 20:54 UTC, emily-potyraj commented on docs/content/getting-started/_index.md
> +If in case you'd prefer to run a [dev container](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers) on your local machine, the samples repo o
```suggestion
If you'd prefer to run a [dev container](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers) on your local machine, the samples repo offers a .devcontainer folder that will allow you to configure the environment anywhere you want and will automatically set up a [Radius local environment](#create-a-radius-environment).
```

2022-07-21 20:54 UTC, emily-potyraj commented on docs/content/getting-started/_index.md
> +Just enter your desired sample application directory and run `rad app deploy` to see Radius in action.
```suggestion
After you launching your codespace or dev container, navigate into your desired sample application directory and run `rad app deploy` to see Radius in action.
```

2022-07-21 21:15 UTC, AaronCrawfis requested changes
One quick suggestion but otherwise looks good

2022-07-21 21:15 UTC, AaronCrawfis commented on docs/content/getting-started/_index.md
> +If in case you'd prefer to run a [dev container](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers) on your local machine, the samples repo o
```suggestion
If in case you'd prefer to run a [dev container](https://code.visualstudio.com/docs/remote/containers) on your local machine, the samples repo offer a .devcontainer folder that will allow you to configure the environment anywhere you want as well as automatically set up a [Radius local environment](#create-a-radius-environment).
```

2022-07-21 23:27 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/_index.md
> +description: "Walk through an in-depth example to learn more about how to work with Radius concepts"
Did we want this included as part of this PR?

2022-07-21 23:54 UTC, jasonviviano commented on docs/content/getting-started/tutorial/_index.md
> +description: "Walk through an in-depth example to learn more about how to work with Radius concepts"
Yeah this is coming from a resolved conversation above about the table in regards to how the Tutorial and the Quickstart descriptions sound pretty similar. The table uses the official descriptions in each of these pages so if changing it on the table I figured from @emily-potyraj 's advice that we should change it in this page as well to be consistent as a description.

2022-07-22 01:46 UTC, emily-potyraj approved these changes

2022-07-22 15:05 UTC, AaronCrawfis approved these changes

2022-07-22 15:05 UTC, merged