Tutorial to match mongo container fix
radius-project/docs pull request #224
Opened 2022-08-01 05:16 UTC by emily-potyraj

also closes #219

2022-08-01 06:10 UTC, emily-potyraj commented
might need some more story telling on the "swap to azure-cosmosdb.bicep" part

2022-08-01 17:23 UTC, AaronCrawfis requested changes

2022-08-01 17:23 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-initial-deployment/index.md
> +linkTitle: "Deploy initial app"
Now that we're removing the "in memory" configuration of deploying just the container without a database, it seems weird to call this "deploy initial app". I'd instead call this page "Deploy application" or "Author and deploy app".

2022-08-01 17:23 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-initial-deployment/snippets/app.bicep
> +        DBCONNECTION: db.connectionString()
I believe the container uses the auto-injected environment variable `CONNECTION_ITEMSTORE_CONNECTIONSTRING`, not `DBCONNECTION`.

https://github.com/project-radius/samples/blob/edge/tutorial/src/server.ts#L26

2022-08-01 17:23 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-initial-deployment/snippets/app.bicep
> +      connectionString: 'mongodb://db:27017/db?authSource=admin'
This should be parameterized and use values passed back by the module

2022-08-01 17:23 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-swap-connector-resource/snippets/app-azure.bicep
> +         destination: frontendRoute.id
```suggestion
         path: '/'
         destination: frontendRoute.id
```

2022-08-01 17:23 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-swap-connector-resource/snippets/app-azure.bicep
> +      connectionString: 'mongodb://db:27017/db?authSource=admin'
See note above on parameterizing this

2022-08-01 17:23 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-swap-connector-resource/snippets/app-azure.bicep
> +    location: location
We should check that this passes the proper value. @jkotalik given this module contains Azure resources but the parent template does not, will this return `global` or the Azure resource group? I suspect the latter, but we should check.

2022-08-01 17:23 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-swap-connector-resource/snippets/app.bicep
> +        DBCONNECTION: db.connectionString()
See note above on using the auto-injected environment variables instead of this value

2022-08-03 19:15 UTC, jkotalik commented on docs/content/getting-started/tutorial/webapp-initial-deployment/snippets/app.bicep
> +      image: 'radius.azurecr.io/webapptutorial-todoapp'
```suggestion
      image: 'radius.azurecr.io/tutorial/webapp:edge'
```

2022-08-03 19:16 UTC, jkotalik commented on docs/content/getting-started/tutorial/webapp-initial-deployment/snippets/mongo-container.bicep
> +}
The sample I was given has outputs from this module, is that supposed to be here?

2022-08-03 19:17 UTC, jkotalik commented on docs/content/getting-started/tutorial/webapp-swap-connector-resource/snippets/app-azure.bicep
> +    location: location
Azure resource group. Isn't this a module for cosmos db? Don't we want resourceGroup().location here?

2022-08-03 19:17 UTC, Reshrahim commented on docs/content/getting-started/tutorial/webapp-initial-deployment/snippets/mongo-container.bicep
> +}
yes this PR needs to be updated with the latest working code

2022-08-03 19:18 UTC, jkotalik commented on docs/content/getting-started/tutorial/webapp-swap-connector-resource/snippets/app-azure.bicep
> +    location: location
I would just remove the variable at the top and put resourceGroup().location here

2022-08-03 19:19 UTC, jkotalik commented on docs/content/getting-started/tutorial/webapp-swap-connector-resource/snippets/app.bicep
> +      image: 'radius.azurecr.io/webapptutorial-todoapp'
```suggestion
      image: 'radius.azurecr.io/tutorial/webapp:edge'
```

2022-08-04 15:26 UTC, AaronCrawfis requested changes

2022-08-04 15:26 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-initial-deployment/index.md
> +You can clone our [samples repo](https://github.com/project-radius/samples) which contains the source code of tutorial application and the bicep templates. It contains three bicep files
I don't believe we're ready to have cloning the samples repo be the main experience for the tutorial.

Right now, we have 450 people in our preview (number of people in the Teams team), but only 80 people in our GitHub org. When we send out the announcement they're going to land in the tutorial and 370 of them will need to request access. This is currently a manual process that requires one of the GitHub admins (me/Emily/Aman) to add them to the GitHub team.

For now I think the tutorial should be self-contained within the docs repo, and for the reference apps and quickstarts we can continue linking off to the GitHub org while we figure  out a better self-service way to access GitHub.

2022-08-04 15:26 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-initial-deployment/index.md
> +## Handoff
Headers should have blank lines afterwards

```suggestion
## Handoff

```

2022-08-04 15:26 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-initialize-environment/index.md
>  ## Initialize a Radius environment
```suggestion
## Initialize a Radius environment

```

2022-08-04 15:26 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-swap-connector-resource/_index.md
> +You need to also add the location parameter. This is intermediate step
What does "intermediate step" mean?

2022-08-04 15:26 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-swap-connector-resource/_index.md
> +Your final app.bicep file should look like below
```suggestion
Your final app.bicep file should look like the file below: 
```

2022-08-04 15:31 UTC, Reshrahim commented on docs/content/getting-started/tutorial/webapp-initial-deployment/index.md
> +You can clone our [samples repo](https://github.com/project-radius/samples) which contains the source code of tutorial application and the bicep templates. It contains three bicep files
This is a stop-gap for internal users to test. I agree the bicep files should be downloadable from the docs site. Created this issue - https://github.com/project-radius/docs/issues/236

2022-08-04 16:07 UTC, Reshrahim commented on docs/content/getting-started/tutorial/webapp-swap-connector-resource/_index.md
> +You need to also add the location parameter. This is intermediate step
Was a typo. updated it

2022-08-04 17:41 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-initial-deployment/index.md
> +The environment property depicts the environment that was initialized in the previous step for the app to land on. Currently the environment property is auto-injected by Radius when the application i
One other thing to think through is the change of having the user write/copy code and instead just read code. Usually with tutorials you want the user to write or copy/paste code to better learn and understand how the tooling/features work. Scrolling through code and reading doesn't provide the same level of concept teaching in my opinion. We should have users write/copy code to learn how Bicep autocomplete and validation works instead of providing the complete sample at the beginning. Complete samples at the beginning are what reference apps are for.

Definitely want to hear the thoughts of @project-radius/radius-pm to see how others feel.

2022-08-04 18:01 UTC, Reshrahim commented on docs/content/getting-started/tutorial/webapp-initial-deployment/index.md
> +The environment property depicts the environment that was initialized in the previous step for the app to land on. Currently the environment property is auto-injected by Radius when the application i
I believe we decided to move away from teaching bicep as per the issue - https://github.com/project-radius/docs/issues/100

The goals of the tutorial that we decided on are 

- Enough knowledge to map your own application in Radius
- Achieve portability via connectors between your local and cloud environments
- Understand the separation of concerns for the different personas involved in a deployment

We also had feedback from Donovan to provide instructions on how they can replace the bicep code with their own containers and resources which is tracked here - https://github.com/project-radius/docs/issues/233

I guess, new users would do a copy and paste of the tutorial anyways. They wouldn't want to write the app components unless they want to build their own application.

2022-08-04 18:50 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-initial-deployment/index.md
> +The environment property depicts the environment that was initialized in the previous step for the app to land on. Currently the environment property is auto-injected by Radius when the application i
> I guess, new users would do a copy and paste of the tutorial anyways. They wouldn't want to write the app components unless they want to build their own application.

There's still value in copying & pasting. You learn and add each piece individually, learning that particular concept instead of seeing everything together all at once and running `rad deploy`

2022-08-04 18:52 UTC, AaronCrawfis approved these changes

2022-08-04 18:54 UTC, merged