Updating mainline tutorial with some small updates
radius-project/docs pull request #231
Opened 2022-08-03 22:17 UTC by jkotalik

Small fixups to the tutorial experience I noticed when reading through it.

2022-08-03 22:31 UTC, Reshrahim commented
> Small fixups to the tutorial experience I noticed when reading through it.

Thank you @jkotalik for updating some of these. Appreciate the help!!

2022-08-03 22:33 UTC, Reshrahim commented on docs/content/getting-started/tutorial/_index.md
> +- Set up an Azure Environment. This is required if you want to deploy the second half of the tutorial to Azure:
I believe this should be Set up an Azure cloud provider. We did a scrub of azure env reference everywhere

2022-08-03 22:35 UTC, Reshrahim commented on docs/content/getting-started/tutorial/webapp-initial-deployment/index.md
> +Create a new file named `app.bicep` and paste the following to add a radius application.
This flow is changed in #224 where we are asking the users to clone the sample repo and the doc explains the components of app.bicep. The user would just deploy the file

2022-08-04 19:04 UTC, Reshrahim submitted a review, later dismissed

2022-08-04 20:10 UTC, Reshrahim approved these changes

2022-08-04 20:10 UTC, merged

2022-08-04 20:17 UTC, AaronCrawfis requested changes

2022-08-04 20:17 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/_index.md
> +- Set up an Azure cloud provider. This is required if you want to deploy the second half of the tutorial to Azure
I don't believe this should be a pre-requisite, as we don't get to environment initialization until a later step.

2022-08-04 20:17 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/_index.md
> +  - Create a [subscription and resource group](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal). Keep a hold of the subscription ID and resource
```suggestion
- [Azure subscription](https://azure.com) (optional - used in last tutorial step to deploy Azure resources)
```

2022-08-04 20:17 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-initial-deployment/index.md
> +The environment property depicts the environment that was initialized in the previous step for the app to land on. Radius will automatically inject the `environment` parameter into the bicep file dur
```suggestion
The **environment** property specifies the environmentId to deploy the application and other resources into. Since this was initialized in the previous step via the CLI, `rad deploy` will automatically inject the `environment` parameter into the Bicep file during deployment.
```

2022-08-04 20:17 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-initial-deployment/index.md
>  The location property defines where to deploy a resource within the targeted platform. It is currently a required property that we expect to remove in a future release. See [Resource Schema]({{< ref
```suggestion
The **location** property defines where to deploy a resource within the targeted platform. For self-hosted Kubernetes environments this value must be set to `'global'`. See [Resource Schema]({{< ref resource-schema >}}) for more info.
```

2022-08-04 20:17 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/webapp-swap-connector-resource/_index.md
> +
```suggestion
{{% alert title="Delete environment" color="warning" %}}
If you're done with testing, you can use the rad CLI to [delete an environment]({{< ref rad_env_delete.md >}}) to delete all Radius resources running on the Kubernetes Cluster.
{{% /alert %}}

{{% alert title="Cleanup Azure Resources" color="warning" %}}
Azure resources are not deleted when deleting a Radius environment, so to prevent additional charges, make sure to delete all resources from the resource group used.
{{% /alert %}}

{{% alert title="Delete other Kubernetes resources used" color="warning" %}}
Additional Kubernetes resources need to be cleaned up that were deployed for Mongo. Run the following commands to delete these resources:

```

2022-08-05 16:25 UTC, jkotalik commented on docs/content/getting-started/tutorial/_index.md
> +- Set up an Azure cloud provider. This is required if you want to deploy the second half of the tutorial to Azure
We should reorganize the tutorial then, currently it is required as part of the tutorial. We don't prompt the user later to call --reinstall or mention that the second half is optional.

2022-08-05 16:30 UTC, Reshrahim commented on docs/content/getting-started/tutorial/_index.md
> +- Set up an Azure cloud provider. This is required if you want to deploy the second half of the tutorial to Azure
Yes I am working on providing instructions for the reinstallation of the control plane with the cloud provider. Tracked here - https://github.com/project-radius/docs/issues/235#issuecomment-1206424780