Update Troubleshooting docs
radius-project/docs pull request #279
Opened 2022-08-11 18:32 UTC by mishrapratikshya

Fixes https://github.com/project-radius/docs/issues/226

2022-08-11 19:16 UTC, willdavsmith commented on docs/content/reference/troubleshooting-radius.md
> +To troubleshoot radius serice user has to fetch the logs from the radius service containers
```suggestion
To troubleshoot the Radius service, the user should fetch the logs from the Radius service containers.
```

2022-08-11 19:16 UTC, willdavsmith commented on docs/content/reference/troubleshooting-radius.md
> +2. Get the logs from radius appcore-rp, ucp and deployment engine container by using the pod names captured from the previous step and running the following command.
```suggestion
2. Get the logs from radius `appcore-rp`, `ucp` and `bicep-de` containers by using the pod names captured from the previous step and running the following command.
```

2022-08-11 19:16 UTC, willdavsmith commented on docs/content/reference/troubleshooting-radius.md
> +1. Run the kubectl command to list the applications running in your cluster under the namespace radius-system to get the pod details of appcore-rp, ucp and deployment engine.
```suggestion
1. Run the `kubectl` command to list the pods running in your cluster under the namespace `radius-system` to  see that `appcore-rp`, `ucp`, and `bicep-de` pods are running.
```

2022-08-11 19:16 UTC, willdavsmith commented on docs/content/reference/troubleshooting-radius.md
> +kubectl logs -f <deployment engine pod name> -n radius-system
```suggestion
kubectl logs -f <bicep-de pod name> -n radius-system
```

2022-08-11 19:16 UTC, willdavsmith commented on docs/content/reference/troubleshooting-radius.md
> +kubectl logs -f <ucp pod> -n radius-system
```suggestion
kubectl logs -f <ucp pod name> -n radius-system
```

2022-08-11 19:16 UTC, willdavsmith commented on docs/content/reference/troubleshooting-radius.md
> +
You can also get the logs without the pod names like so:
```
k logs -n radius-system -l control-plane=de
k logs -n radius-system -l control-plane=ucp
k logs -n radius-system -l control-plane=appcore-rp
```

2022-08-11 19:16 UTC, willdavsmith commented on docs/content/reference/troubleshooting-radius.md
> +Deploying an application to Azure with a service principle with incorrect scope returns an error from deployment engine
```suggestion
Deploying an application to Azure with a service principal with incorrect scope returns an error from deployment engine
```

2022-08-11 23:25 UTC, willdavsmith submitted a review, later dismissed

2022-08-12 16:54 UTC, emily-potyraj submitted a review, later dismissed
Looking good, thanks! 

I'm approving, but have have 1 non-blocking question, which is whether we should add a note about "In the future, the Radius CLI and Dashboard will have more native troubleshooting capabilities. For now, we still rely on kubernetes capabilities to help investigate issues."

2022-08-12 16:57 UTC, AaronCrawfis requested changes
Looking good! Couple formatting/wording suggestions but overall great content!

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +## Troubleshooting Radius Service
```suggestion
## Troubleshooting the Radius control-plane
```

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +To troubleshoot the Radius service, the user should fetch the logs from the Radius service containers.
```suggestion
To troubleshoot the Radius control-plane, begin by viewing the logs from the [control-plane services]({{< ref architecture >}}) within the `radius-system` namespace. The kubectl CLI can be used, or a graphical tool such as [Octant](https://octant.dev/).
```

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +```
Indent these 3 lines by 3 spaces in order to nest this code block under the numbered list (can't make a code suggestion due to the code block

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +```
Indent these 5 lines by 3 spaces

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +1. Run the `kubectl` command to list the pods running in your cluster under the namespace `radius-system` to  see that `appcore-rp`, `ucp`, and `bicep-de` pods are running.
```suggestion
1. Use the `kubectl` CLI to list the control-plane pods running in your cluster under the namespace `radius-system`. You should see the `appcore-rp`, `ucp`, and `bicep-de` pods running:
```

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +2. Get the logs from radius `appcore-rp`, `ucp` and `bicep-de` containers by using the following command.
```suggestion
2. Get the logs from the `appcore-rp`, `ucp` and `bicep-de` containers by using the following commands:
```

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +You can also get the logs by using the pod names captured from the previous step and running the following command.
```suggestion
   You can also get the logs by using the pod names captured from the previous step and running the following commands:
```

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +```
Indent this code block

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +3. Check for the text "panic" in the logs and if you find it open an issue at https://github.com/project-radius/radius by providing the details.
```suggestion
3. Look for the text "panic" or "error" in the logs, and if you find it inspect the error message. Also please open an issue at [project-radius/radius](https://github.com/project-radius/radius/issues/new?assignees=&labels=kind%2Fbug&template=bug.md&title=%3CBUG+TITLE%3E) with the details of your error and if possible, how to recreate.
```

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +To troubleshoot issues with the Azure cloud provider and deployments to user's Azure subscription and resource group, refer to ARM logs. Log in to https://portal.azure.com and within the target resou
```suggestion
To troubleshoot issues with the [Azure cloud provider]({{< ref providers >}}) and deployments to a Microsoft Azure subscription and resource group, refer to your [ARM activity logs](https://docs.microsoft.com/azure/azure-monitor/essentials/activity-log):

1. Visit https://portal.azure.com
1. Navigate to your target subscription and resource group
1. Select "Activity logs" from the menu
1. Inspect the logs for any errors of failed deployments

Note that Activity logs may take up to 10 minutes to be available in Azure.
```

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +## Examples
```suggestion
## Example: Troubleshooting a failed deployment
```

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +Deploying an application to Azure with a service principal with incorrect scope returns an error from deployment engine
```suggestion
In this example, a failure is returned after attempting to deploy a Bicep template that contains a Radius application plus Azure resources:
```

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +Deployment engine logs
```suggestion
This error isn't very descriptive. Let's take a look at the control-plane logs to see if they can tell us more:

```

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +kubectl logs -f bicep-de-6d4546df86-rhthn -n radius-system
```suggestion
kubectl logs -n radius-system -l control-plane=de
```

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +Azure.RequestFailedException: The client '81082ee4-ace0-4922-a80a-2c02cb0d2207' with object id '81082ee4-ace0-4922-a80a-2c02cb0d2207' does not have authorization to perform action 'Microsoft.Resource
```suggestion
Azure.RequestFailedException: The client 'APP_ID' with object id 'OBJECT_ID' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/SUBSCRIPTION_ID/resourcegroups/radius-rg-MZ94f' or the scope is invalid. If access was recently granted, please refresh your credentials.
```

2022-08-12 16:57 UTC, AaronCrawfis commented on docs/content/reference/troubleshooting-radius.md
> +```
Add the following section please:

```
This tells us the service principal that was configured with the Azure cloud provider was not properly configured on the target resource group. You can now add your service principal to your resource group and try your deployment again.

Also please make sure to [open an Issue](https://github.com/project-radius/radius/issues/new?assignees=&labels=kind%2Fbug&template=bug.md&title=%3CBUG+TITLE%3E) if you encounter a generic `Internal server error` message, so we can address the root error not being forwarded to the user.
```

2022-08-12 17:33 UTC, mishrapratikshya commented
> Looking good, thanks!
> 
> I'm approving, but have have 1 non-blocking question, which is whether we should add a note about "In the future, the Radius CLI and Dashboard will have more native troubleshooting capabilities. For now, we still rely on kubernetes capabilities to help investigate issues."

I think we should add it. @AaronCrawfis your thoughts?

2022-08-12 17:35 UTC, willdavsmith submitted a review, later dismissed

2022-08-12 17:57 UTC, AaronCrawfis approved these changes

2022-08-12 18:34 UTC, merged