Timeout policy page created
radius-project/docs pull request #288
Opened 2022-08-16 16:55 UTC by jasonviviano

## Description
Created a policy page to reflect the information collected in #194 

Closes #194

2022-08-16 16:56 UTC, jasonviviano commented
@jkotalik @youngbupark Let me know if the current page format makes sense from a developer perspective or if I'm missing any information whenever you have time.

2022-08-16 17:01 UTC, AaronCrawfis requested changes

2022-08-16 17:01 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/resource-policies/_index.md
> +---
I don't think `reference/resource-schema` is the right place, as this describes API behavior, not resource schema.

Instead, I'd create a new path under `reference/api` and place this as a child under the new API section. For now we can keep the API page pretty bare bones (basically blank), and then add on additional content later as we document more of the behavior of our APIs

2022-08-16 17:01 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/resource-policies/_index.md
> +title: "Resource timeout/retry policies"
```suggestion
title: "API timeout/retry policies"
```

2022-08-16 17:01 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/resource-policies/_index.md
> +description: "Learn the timeout/retry policies of Radius resources"
```suggestion
description: "Learn the timeout/retry policies of the Radius API"
```

2022-08-16 17:01 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/resource-policies/_index.md
> +### Deployment engine resources
```suggestion
### Deployment engine behavior
```

2022-08-16 17:01 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/resource-policies/_index.md
> +### Resource provider resources
```suggestion
### Resource provider behavior
```

2022-08-16 17:01 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/resource-policies/_index.md
> +#### Timeout times
```suggestion
#### Timeout durations
```

2022-08-16 17:01 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/resource-policies/_index.md
> +##### Applications.Core resource provider
We will need to make sure to have a process of how to update this table whenever a new resource is added to the app model. This page will quickly go out of date unless the dev docs say to update this when adding a new resource. Best solution would be to eventually auto-generate it. We should open an issue to track this.

2022-08-16 17:09 UTC, jasonviviano commented on docs/content/reference/resource-schema/resource-policies/_index.md
> +##### Applications.Core resource provider
Created this in the docs repo: https://github.com/project-radius/docs/issues/290

2022-08-16 17:16 UTC, jasonviviano commented on docs/content/reference/resource-schema/resource-policies/_index.md
> +---
Created the `reference/api` page and moved the timeout policy page let me know if this makes more sense for you.

2022-08-16 18:17 UTC, AaronCrawfis requested changes

2022-08-16 18:17 UTC, AaronCrawfis commented on docs/content/reference/api/_index.md
> +linkTitle: "rad API"
```suggestion
linkTitle: "Radius API"
```

`rad` is only for the CLI

2022-08-16 18:17 UTC, AaronCrawfis commented on docs/content/reference/api/_index.md
> +weight: 100
```suggestion
weight: 400
```

2022-08-16 18:17 UTC, AaronCrawfis commented on docs/content/reference/api/resource-policies/_index.md
> +| Default retry timeout for resource deployment | The name of your resource. | 12.5 minutes per resource | Retries on 5xx errors, 50 retry requests
In this table you say "name of your resource", but the column header says "Resource type". I'd be specific on which one you're referencing

2022-08-16 18:17 UTC, AaronCrawfis commented on docs/content/reference/api/resource-policies/_index.md
> +### Deployment engine behavior
I'd bump this header up from h3 to h2, as well as promote every header below this. I try not to have only one h2 on a given page. It's better to have multiple H2s and not nest too deep into h4/h5

2022-08-18 04:05 UTC, AaronCrawfis approved these changes

2022-08-18 04:05 UTC, merged