Reformatted AWS and terraform mentions in concept page (archi, connec…
radius-project/docs pull request #291
Opened 2022-08-16 17:43 UTC by jasonviviano

## Description
Reformatted architecture and connector concept pages to have a more generic reference to AWS and Terraform for now as per issue: #266. Added generic versions of the current diagrams and kept the old ones in file.

Closes #266

2022-08-16 18:12 UTC, AaronCrawfis requested changes
For `azure-imperative-generic.png` could you middle-align and center and middle justify "Other IAC tool deployments", as well as update it to read "Other IaC tool operations".

Also for `controlplane-services-generic.png` could you middle-align "Other IAC" and update it to "Other IaC"? Also update the font to Degoe UI Semibold

2022-08-16 18:12 UTC, AaronCrawfis commented on docs/content/concepts/architecture/index.md
> +<img src="controlplane-services-generic.png" alt="Diagram of the Project Radius control-plane services" width="700" />
If `controlplane-services.png` is no longer referenced could you delete it please?

2022-08-16 18:33 UTC, jasonviviano commented on docs/content/concepts/architecture/index.md
> +<img src="controlplane-services-generic.png" alt="Diagram of the Project Radius control-plane services" width="700" />
Updated and deleted `controlplane-services.png` should i also delete the old `azure-imperative.png`?

2022-08-16 19:02 UTC, kachawla commented on docs/content/concepts/architecture/index.md
> +The universal control plane (UCP) provides the front-door endpoint, authentication, authorization, and other central capabilities for a self-hosted Radius environment. When deploying to a Radius envi
Should we be explicit about which CLI?

```suggestion
The universal control plane (UCP) provides the front-door endpoint, authentication, authorization, and other central capabilities for a self-hosted Radius environment. When deploying to a Radius environment using a deployment JSON file (Bicep) or through single imperative commands (Radius CLI, other IaC tools), UCP handles the request and sends it to the appropriate plane.
```

2022-08-16 19:02 UTC, kachawla commented on docs/content/concepts/architecture/index.md
> +When using other IaC tools or the rad CLI to deploy and interact with Radius applications:
```suggestion
When using the rad CLI or other IaC tools to deploy and interact with Radius applications:
```

2022-08-16 19:02 UTC, kachawla commented on docs/content/concepts/architecture/index.md
>  In Microsoft Azure environments, Azure Resource Manager (ARM) is used instead of UCP.
@vinayada1 my understanding was that requests for all planes get routed through UCP, do we completely skip UCP in case of Azure env?

2022-08-16 19:02 UTC, kachawla commented on docs/content/concepts/connectors-concept/_index.md
>  <img src="connectors-example.png" alt="Diagram of example architecture using or Radius Conntector. Depicts a Radius Container connected to MongoDB Radius Connector, which can bind to an Azure CosmosD
Remove DynamoDB from here?

2022-08-16 19:02 UTC, kachawla commented on docs/content/concepts/connectors-concept/_index.md
> +For example, when a user specifies a MongoDB connector, that connector could bind to an Azure CosmosDB, services from other cloud providers, or a Mongo Container based on which platform is targeted.
`MongoDB services from other cloud providers` - would it make sense to explicitly call out mongo db here given that's what Mongo connector is supposed to work with? AWS DynamoDB shouldn't be tied to Mongo connector for example.

2022-08-16 19:05 UTC, kachawla commented on docs/content/concepts/architecture/index.md
> +<img src="controlplane-services-generic.png" alt="Diagram of the Project Radius control-plane services" width="700" />
Both `azure-imperative.png` and `controlplane-services-generic.png` above do not show that the app containers are deployed in same Kubernetes cluster as Radius services (UCP/DE/RP), should it be reflected there?

2022-08-16 19:07 UTC, AaronCrawfis commented on docs/content/concepts/architecture/index.md
>  In Microsoft Azure environments, Azure Resource Manager (ARM) is used instead of UCP.
This alludes to the upcoming Azure managed service environment, where UCP will not play a role (most likely). We should probably remove this information and only focus on self-hosted environments.

2022-08-16 19:07 UTC, AaronCrawfis commented on docs/content/concepts/architecture/index.md
> +<img src="controlplane-services-generic.png" alt="Diagram of the Project Radius control-plane services" width="700" />
Yeah if nothing is referencing it we should remove it

2022-08-16 19:22 UTC, kachawla commented on docs/content/concepts/architecture/index.md
>  In Microsoft Azure environments, Azure Resource Manager (ARM) is used instead of UCP.
Makes sense for Azure managed service. Agree, we should remove it until this is supported.

2022-08-16 19:39 UTC, jasonviviano commented on docs/content/concepts/architecture/index.md
> +<img src="controlplane-services-generic.png" alt="Diagram of the Project Radius control-plane services" width="700" />
Yeah they might be out of date as the diagrams I updated were from a previous iteration of docs. I can look into updating them. @AaronCrawfis do you think the diagrams should reflect the cluster deployment better?

2022-08-16 19:46 UTC, jasonviviano commented on docs/content/concepts/connectors-concept/_index.md
>  <img src="connectors-example.png" alt="Diagram of example architecture using or Radius Conntector. Depicts a Radius Container connected to MongoDB Radius Connector, which can bind to an Azure CosmosD
I didn't remove it from here as I thought in terms of diagram illustration this was probably ok to show that there's a wide ability of support for different MongoDB types. But if you believe we should add another name or just remove it completely I can.

2022-08-16 19:46 UTC, jasonviviano commented on docs/content/concepts/connectors-concept/_index.md
> +For example, when a user specifies a MongoDB connector, that connector could bind to an Azure CosmosDB, services from other cloud providers, or a Mongo Container based on which platform is targeted.
Changed it, let me know if this makes more sense.

2022-08-16 20:51 UTC, kachawla commented on docs/content/concepts/connectors-concept/_index.md
>  <img src="connectors-example.png" alt="Diagram of example architecture using or Radius Conntector. Depicts a Radius Container connected to MongoDB Radius Connector, which can bind to an Azure CosmosD
I see.. I think we should update the diagram in that case to show `Mongo DB on AWS` instead of `Dynamo DB` https://aws.amazon.com/quickstart/architecture/mongodb/. @AaronCrawfis do you know the context on why we have been mapping Dynamo DB with Mongo connector instead of AWS' support for Mongo DB?

2022-08-16 20:52 UTC, kachawla commented on docs/content/concepts/connectors-concept/_index.md
> +For example, when a user specifies a MongoDB connector, that connector could bind to an Azure CosmosDB, services from other cloud providers, or a Mongo Container based on which platform is targeted.
Looks good, thanks.

2022-08-18 04:07 UTC, AaronCrawfis commented on docs/content/concepts/connectors-concept/_index.md
>  <img src="connectors-example.png" alt="Diagram of example architecture using or Radius Conntector. Depicts a Radius Container connected to MongoDB Radius Connector, which can bind to an Azure CosmosD
This was just an early mistake in a diagram that I made that we are just now catching 😅. Agreed let's update the diagram.

2022-08-31 20:50 UTC, AaronCrawfis commented on docs/content/concepts/connectors-concept/_index.md
>  <img src="connectors-example.png" alt="Diagram of example architecture using or Radius Conntector. Depicts a Radius Container connected to MongoDB Radius Connector, which can bind to an Azure CosmosD
Updated diagram

2022-08-31 21:02 UTC, AaronCrawfis commented on docs/content/concepts/architecture/index.md
> +<img src="controlplane-services-generic.png" alt="Diagram of the Project Radius control-plane services" width="700" />
Updated the diagrams

2022-08-31 21:02 UTC, AaronCrawfis approved these changes

2022-08-31 21:38 UTC, merged