Updated Tutorials to include VSCode section
radius-project/docs pull request #32
Opened 2022-02-24 06:24 UTC by jasonviviano

## Description

- Added basic VSCode section to talk about the visualization feature of the applications to raise awareness of for users.
- Added new links for source code to tutorials as the previous were broken
- Created new tutorial folder for tutorials on [radiuspublic](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/66d1209e-1382-45d3-99bb-650e6bf63fc0/resourceGroups/assets/providers/Microsoft.Storage/storageAccounts/radiuspublic/containersList) for the links.
- Fixed minor markdown style errors and grammar errors if found.

## Issue
https://github.com/project-radius/docs/issues/25

2022-02-24 17:59 UTC, AaronCrawfis requested changes
Good start. Make sure you have a local docs environment running, there are a bunch of rendering issues that are better caught in your inner loop authoring experience.

Left some notes on the tabs,  those need to work to be clearer on the options.

2022-02-24 17:59 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/webapp/webapp-overview/index.md
> +You can download the source code [here](https://radiuspublic.blob.core.windows.net/tutorials/webapp.zip) if you want to see how the complete code.
```suggestion
You can download the source code [here](https://get.radapp.dev/tutorials/webapp.zip) if you want to see how the complete code.
```

Switching link to use the CDN endpoint

2022-02-24 17:59 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/webapp/webapp-initial-deployment/index.md
> +   <img src="todoapp-nodb.png" width="400" alt="screenshot of the todo application with no database">
This isn't rendering correctly. 
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/54363786/155579728-afb84837-03fe-4852-8ae2-88ce40e8ab3e.png">
Try adding a blank line to see if that fixes it:
```suggestion
   
   <img src="todoapp-nodb.png" width="400" alt="screenshot of the todo application with no database">
```

2022-02-24 17:59 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/webapp/webapp-initial-deployment/index.md
> +3. To view a representation of your application deployed you can visit your Azure resource group or the Kubernetes technology you rely on for visualizing Docker environments.
This doesn't make sense, the tab says rad CLI but the steps don't show any rad CLI steps.

Either:
   - rename this tab to Azure, and add ones for Kubernetes/local
   - Make this step for VS Code extension only and remove the tabs

2022-02-24 17:59 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/webapp/webapp-initial-deployment/index.md
> +- Add a todo item
These aren't rendering correctly
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/54363786/155580371-130dd2fc-683f-4d4f-9e29-750196f9b916.png">

2022-02-24 17:59 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/dapr-microservices/dapr-microservices-initial-deployment/index.md
> +{{< tabs "Radius CLI" "VSCode Extension" >}}
See notes from webapp tutorial. These tabs don't make sense because these aren't  rad CLI steps

2022-02-24 17:59 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/dapr-microservices/dapr-microservices-initial-deployment/index.md
> +1. Visit the [URL](http://localhost:3000/order) in your browser. For now you should see a message like:
Not rendering correctly
<img width="342" alt="image" src="https://user-images.githubusercontent.com/54363786/155580579-87fea337-5c36-4290-a863-b30c1aa9d2f0.png">

2022-02-24 17:59 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/dapr-microservices/dapr-microservices-overview/index.md
> +You can download the source code [here](https://radiuspublic.blob.core.windows.net/tutorials/dapr-microservices.zip) if you want to see the complete code.
```suggestion
You can download the source code [here](https://get.radapp.dev/tutorials/dapr-microservices.zip) if you want to see the complete code.
```

2022-03-01 19:16 UTC, jasonviviano commented on docs/content/user-guides/tutorials/dapr-microservices/dapr-microservices-initial-deployment/index.md
> +1. Visit the [URL](http://localhost:3000/order) in your browser. For now you should see a message like:
Reformatted based on the comments you brought up

2022-03-03 22:58 UTC, AaronCrawfis requested changes

2022-03-03 22:58 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/dapr-microservices/dapr-microservices-initial-deployment/index.md
> +1. Visit the [URL](http://localhost:3000/order) in your browser. For now you should see a message like:
I think we want to keep the URL visible, since we want users to know the URL they're visiting.

```suggestion
1. Visit the URL http://localhost:3000/order in your browser. For now, you should see a message like:
```

2022-03-03 22:58 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/dapr-microservices/dapr-microservices-initial-deployment/index.md
> +The following tips are  a preview of how the VS Code Radius extension can be deployed improve developer workflow. As we introduce additional features to the extension we will incorporate them into th
```suggestion
The following tips are a preview of how the VS Code Radius extension can be used to improve the developer workflow. As we introduce additional features to the extension, we will incorporate them into this section.
```

2022-03-03 22:58 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/dapr-microservices/dapr-microservices-initial-deployment/index.md
> +
```suggestion

## Next step

```

2022-03-03 22:58 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/dapr-microservices/dapr-microservices-initial-deployment/index.md
> +## VS Code Tips
```suggestion
## Interact with your application using the VS Code extension
```

2022-03-03 22:58 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/dapr-microservices/dapr-microservices-overview/index.md
> +You can download the source code [here](https://get.radapp.dev/tutorials/dapr-microservices.zip) if you want to see the complete code.
```suggestion
You can download the source code [here](https://get.radapp.dev/tutorials/edge/dapr-microservices.zip) if you want to see the complete code.
```

Long term we'll want to find a way to switch between edge and a versioned release in Hugo, but for now we can hardcode it

2022-03-03 22:58 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/webapp/webapp-initial-deployment/index.md
> +## VS Code Tips
```suggestion
## Interact with your application using the VS Code extension
```

2022-03-03 22:58 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/webapp/webapp-overview/index.md
> +You can download the source code [here](https://get.radapp.dev/tutorials/webapp.zip) if you want to see how the complete code.
```suggestion
You can download the source code [here](https://get.radapp.dev/tutorials/edge/webapp.zip) if you want to see how the complete code.
```

2022-03-07 20:53 UTC, AaronCrawfis requested changes
Good progress so far. Still have some  rendering isssues. Also, could you update all the screenshots to be cropped & shorter? I'd drag the "PR" extension up near the top. Right now all the screenshots are much too tall.

2022-03-07 20:53 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/webapp/webapp-add-database/index.md
> +1. To view a representation of your application deployed you can visit your Azure resource group or the Kubernetes technology you rely on for visualizing Docker environments.
```suggestion
1. To view a representation of your application deployed you can visit your Azure resource group or the Kubernetes technology you rely on for visualizing Docker environments.
```

This isn't rendering correctly. Make sure to run a Hugo server locally to check for issues with bullets/lists.

2022-03-07 20:53 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/webapp/webapp-add-database/index.md
> +1. To view a representation of your application deployed you can visit your Azure resource group or the Kubernetes technology you rely on for visualizing Docker environments.
This isn't a Radius CLI step. I'd update this to run `rad resource list` or  something like that. We don't want users going directly into the portal yet.

2022-03-07 20:53 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/webapp/webapp-add-database/index.md
>  {{< /tabs >}}
Something is weird with the tabs, it's not rendering correctly: 
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/54363786/157115848-b5d33087-4f4d-41df-babd-546b98f0de0d.png">

2022-03-15 19:27 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/webapp/webapp-add-database/index.md
> +We'll discuss template.bicep changes and then provide the full, updated file before deployment.
```suggestion
We'll discuss todo.bicep changes and then provide the full, updated file before deployment.
```

2022-03-15 19:28 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/webapp/webapp-add-database/index.md
> +
```suggestion
```

2022-03-15 19:28 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/webapp/webapp-add-database/index.md
> +
```suggestion
```

2022-03-15 19:29 UTC, AaronCrawfis commented on docs/content/user-guides/tutorials/webapp/webapp-add-database/index.md
> +
```suggestion
```

2022-03-15 19:30 UTC, AaronCrawfis approved these changes

2022-03-15 19:30 UTC, merged