Adding quickstart for deploying AWS MemoryDB using radius
radius-project/docs pull request #340
Opened 2022-09-27 21:32 UTC by vinayada1

2022-09-27 21:47 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +title: "Quickstart: Deploy MemoryDB for Redis cluster to AWS"
```suggestion
title: "Quickstart: Deploy AWS resources via Radius"
```

2022-09-27 21:48 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +linkTitle: "Deploy AWS MemoryDB for Redis"
```suggestion
linkTitle: "Deploy AWS resources"
```

2022-09-27 21:49 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +description: "Learn about using Radius to deploy MemoryDB for Redis cluster to AWS"
```suggestion
description: "Learn how to set up an AWS cloud provider and deploy an AWS MemoryDB for Redis via Radius" 
```

2022-09-27 21:53 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +## Step 1: Create AWS Access Key
Can we add this to the AWS account step in the prerequisites and have only the Radius-related activities as steps

2022-09-27 21:54 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +## Prerequisites
Would be good to add links to each of these as it'll help the user to navigate to the pre-requisites by checking clicking here

2022-09-28 17:22 UTC, willdavsmith commented
Should this PR be against `edge` branch instead of `v0.13`?

2022-09-28 17:22 UTC, AaronCrawfis commented
> Should this PR be against `edge` branch instead of `v0.13`?

Yep

2022-09-28 17:24 UTC, AaronCrawfis reviewed
Could you remove .DS_STORE from /getting-started?

2022-09-28 17:30 UTC, AaronCrawfis requested changes

2022-09-28 17:30 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +weight: 500
```suggestion
weight: 500
slug: "aws"
```

2022-09-28 17:30 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +1. Use the [`rad env init kubernetes` command]({{< ref rad_env_init_Kubernetes >}}) to initialize a new environment into your current kubectl context:
`rad env init kubernetes` is being deprecated in 0.14. We should switch to `rad init`

2022-09-28 17:30 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +   Follow the prompts to install the [control plane services]({{< ref architecture >}}), creates an [environment resource]({{< ref environments >}}), and creates a [local workspace]({{< ref workspace
```suggestion
   Follow the prompts to install the [control plane services]({{< ref architecture >}}), create an [environment resource]({{< ref environments >}}), and create a [local workspace]({{< ref workspaces >}}). You will be asked for:
```

2022-09-28 17:30 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +   -  **Add AWS provider** - Enter 'y'and follow the instructions. Provide a valid AWS region and the values obtained for IAM Access Key ID and IAM Secret Access Keys.
This interaction will be updated in `rad init` (selection instead of y/n)

2022-09-28 17:30 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +   - **Environment name** - The name of the environment to create. You can specify any name with lowercase letters, such as `myAWSenv`.
Instructions say lowercase but example has uppercase letters

2022-09-28 17:30 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +Here note that the bicep name and the clusterName specified in the bicep file should match. We are currently adding support to model and deploy other AWS resources. Stay tuned for more updates!
```suggestion
Note that the resource `name` and the `clusterName` are required to match.
```

- Using resource name instead of Bicep name
- Note on adding other AWS resources doesn't make sense in the same paragraph as talking about naming. That should go elsewhere, or in another paragraph/note

2022-09-28 17:30 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +## Step 4: Deploy the bicep file
```suggestion
## Step 4: Deploy the Bicep file
```

2022-09-28 17:30 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +Deploy the bicep file created in step 3 by the running the command below.
```suggestion
Deploy the Bicep file created in step 3 by the running [`rad deploy`]({{< ref rad_deploy >}}):
```

2022-09-28 17:30 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +Use the AWS CLI command below to verify that the cluster is deployed.
```suggestion
Use the AWS CLI to verify that the cluster is deployed:
```

2022-09-28 17:30 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +Alternatively, you could also use the [AWS Management Console](https://aws.amazon.com/console/) to verify the deployment of the cluster.
We should also add cleanup instructions, as well as instructions as how to consume this new resource from a Radius application/container

2022-09-28 18:01 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +1. Use the [`rad env init kubernetes` command]({{< ref rad_env_init_Kubernetes >}}) to initialize a new environment into your current kubectl context:
I think AWS cloud provider implementation should be ported over to 'rad init' before we make that change.(https://github.com/project-radius/radius/issues/3717). We did not prioritize it this sprint as we found some gaps (Issue list [here](https://teams.microsoft.com/l/message/19:a9bf4144077d450d9f53df95e5159e28@thread.tacv2/1663961179961?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=b33db407-e89b-4fb6-87cc-9b2f9f8ec265&parentMessageId=1663961179961&teamName=Project%20Radius%20Core%20Team&channelName=Scrum%20Team%20A&createdTime=1663961179961&allowXTenantAccess=false) )

2022-09-29 19:46 UTC, vinayada1 commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +1. Use the [`rad env init kubernetes` command]({{< ref rad_env_init_Kubernetes >}}) to initialize a new environment into your current kubectl context:
Looks like currently there are issues with rad init command #3827. Discussed this with @Reshrahim and the plan is to keep it as is and change it to rad init later

2022-09-29 19:46 UTC, vinayada1 commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +   -  **Add AWS provider** - Enter 'y'and follow the instructions. Provide a valid AWS region and the values obtained for IAM Access Key ID and IAM Secret Access Keys.
Looks like currently there are issues with rad init command #3827. Discussed this with @Reshrahim and the plan is to keep it as is and change it to rad init later

2022-09-29 19:50 UTC, vinayada1 commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +Alternatively, you could also use the [AWS Management Console](https://aws.amazon.com/console/) to verify the deployment of the cluster.
> Could you remove .DS_STORE from /getting-started?

Done

2022-09-29 21:49 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +---
This file should be renamed `index.md` and placed within a directory named `aws-memorydb-quickstart` in order to isolate it from the rest of the quickstart content

2022-09-30 17:11 UTC, jkotalik commented on docs/content/getting-started/quickstarts/snippets/aws-memorydb.bicep
> +  }
Formatting here seems off by (L5 and below needs to be left shifted once)

2022-09-30 17:11 UTC, jkotalik commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +   -  **Add AWS provider** - Enter 'y'and follow the instructions. Provide a valid AWS region and the values obtained for IAM Access Key ID and IAM Secret Access Keys.
```suggestion
   -  **Add AWS provider** - Enter 'y' and follow the instructions. Provide a valid AWS region and the values obtained for IAM Access Key ID and IAM Secret Access Keys.
```

2022-09-30 17:51 UTC, AaronCrawfis commented on .github/workflows/website.yaml
>    workflow_dispatch:
I think now that you're targeting edge, and your base branch is v0.13, it's picking up a bunch of changes that we don't want to get in. I'd rebase off of edge

2022-09-30 18:05 UTC, Reshrahim commented on .github/workflows/website.yaml
>    workflow_dispatch:
rebased

2022-09-30 18:08 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +---
yes moved to a separate folder

2022-09-30 18:20 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/aws-memorydb-quickstart.md
> +Alternatively, you could also use the [AWS Management Console](https://aws.amazon.com/console/) to verify the deployment of the cluster.
We learned from this issue #3844 that memory db cannot be accessed outside AWS without configuring VPN. We are figuring out what would be another resource that we could use in the context webapp as part of #3980. This quickstart could be v1 of deploying an AWS resource and the next version can cover on consuming this from an application /container once we figure out #3980

2022-09-30 22:48 UTC, AaronCrawfis requested changes

2022-09-30 22:48 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +title: "Quickstart: Deploy AWS resources via Radius"
```suggestion
title: "Quickstart: Deploy AWS resources"
```

"via Radius" is implicit since it's a Radius quickstart

2022-09-30 22:48 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +   -  **Add AWS provider** - Enter 'y'and follow the instructions. Provide a valid AWS region and the values obtained for IAM Access Key ID and IAM Secret Access Keys.
```suggestion
   -  **Add AWS provider** - Enter 'y' and follow the instructions. Provide a valid AWS region and the values obtained for IAM Access Key ID and IAM Secret Access Keys.
```

2022-09-30 22:48 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +## Step 5: Verify that the MemoryDB for Redis cluster has been created.
This quickstart feels incomplete to me until we have a way to actually access the MemoryDB cluster. The user running this quickstart will deploy the resource and say "cool, now how do I access this?".

Chatting with @vinayada1 it sounds like the EKS cluster will need to be in the same VPC, or the user will need to setup a VPN.

I think there are two options:

1. Add instructions on how to embed this cluster within the VPC of the EKS cluster from the environment.
2. Use a publicly accessible resource such as a S3 bucket instead

Then you can add a step to show how to pass the S3 bucket endpoint address to a container as an environment variable (you can ignore that it goes over the internet and is publicly accessible. We can add IAM support for the container and VPC support later)

2022-10-04 21:22 UTC, willdavsmith commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +## Step 5: Verify that the MemoryDB for Redis cluster has been created.
Updated this tutorial to deploy the MemoryDB to the same VPC as the EKS cluster.

2022-10-05 00:20 UTC, rynowak commented on docs/content/getting-started/quickstarts/_index.md
> +    <img src="./aws/AWS-logo.png" alt="AWS logo" width="200px">
This is a really nice logo, did you make it?

2022-10-05 00:23 UTC, rynowak commented on docs/content/getting-started/quickstarts/aws-quickstart/snippets/aws-memorydb.bicep
> +param eksClusterName string = 'your-eks-cluster-name' // Replace this with your EKS cluster name
I'd suggest making this a required parameter in `app.bicep` Then it has to be passed in at the command line. Right now it's easy for someone to forget about this.

2022-10-05 00:24 UTC, rynowak commented on docs/content/getting-started/quickstarts/aws-quickstart/snippets/aws-memorydb.bicep
> +
This is sooooo cool that this works 👍 gj @willdavsmith and @asilverman and @vinayada1

2022-10-05 00:27 UTC, rynowak commented on docs/content/getting-started/quickstarts/aws-quickstart/snippets/aws-memorydb.bicep
> +param eksClusterName string = 'your-eks-cluster-name' // Replace this with your EKS cluster name
@Reshrahim and the rest of Team B - would love to have a brainstorm about how we make this even better.

I don't want to block this PR - this feedback is more future-looking.

VPCs are a really central concept in AWS - should this be front and center? (eg: instead of providing the cluster name we provide the VPC name?).

Should we use the environment resource to store the VPC? I don't have an idea yet about **how** to make this automatic, but I'm asking if we should :) For example when authoring recipes for AWS, we're going to need access to the VPC.

Much ❤️ and I hope we're thinking about how to make this more streamlined.

2022-10-05 00:31 UTC, rynowak commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +## Step 5: Verify that the MemoryDB for Redis cluster has been created.
FYI something we're all going to have to get comfortable with ... AWS resources are hard to access.

"If you can't handle me at my worst, you don't deserve me at my best"

-- Jeff Bezos

2022-10-05 00:37 UTC, ryanwaite commented on docs/content/getting-started/quickstarts/aws-quickstart/snippets/aws-memorydb.bicep
> +param eksClusterName string = 'your-eks-cluster-name' // Replace this with your EKS cluster name
I just stumbled across this. VPCs are such a central concept in AWS, and they're crazy complicated. If you want to see the really hard stuff, check out PrivateLink. Ugh. We did customers little in the way of favors. I'd be happy to jump into some of the design review to help with VPC issues and general AWS stuff.

2022-10-05 15:07 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/aws-quickstart/snippets/aws-memorydb.bicep
> +param eksClusterName string = 'your-eks-cluster-name' // Replace this with your EKS cluster name
Thank you for the thoughts here. Capturing the feedback here as a design issue - https://github.com/project-radius/radius/issues/4023 

Team B will continue to explore more on this!

2022-10-05 16:01 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +## Step 4: Create a bicep file that uses MemoryDB
```suggestion
## Step 4: Create an app.bicep that uses the MemoryDB
```

2022-10-05 16:43 UTC, vinayada1 commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +1. To test your application, navigate to the public endpoint.
Fix numbering

2022-10-05 17:37 UTC, vinayada1 commented on docs/content/getting-started/quickstarts/aws-quickstart/snippets/app.bicep
> +  name: 'memorydb-module'
Add "existing" resource stuff

2022-10-05 17:54 UTC, vinayada1 commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +1. You can view the current context for kubectl by running:
Fix numbering below

2022-10-05 18:40 UTC, jkotalik commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +## Step 4: Create a bicep file that uses MemoryDB
Let's add the example where we have an existing memory db as well.

2022-10-05 18:52 UTC, jkotalik submitted a review, later dismissed

2022-10-05 19:48 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/snippets/aws-memorydb.bicep
> +param eksClusterName string = 'your-eks-cluster-name' // Replace this with your EKS cluster name
```suggestion
param eksClusterName string
```

2022-10-05 19:49 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/snippets/aws-memorydb.bicep
> +output memoryDBConnectionString string = 'rediss://${memoryDBCluster.properties.ClusterEndpoint.Address}:${memoryDBCluster.properties.ClusterEndpoint.Port}'
```suggestion
output memoryDBConnectionString string = 'redis://${memoryDBCluster.properties.ClusterEndpoint.Address}:${memoryDBCluster.properties.ClusterEndpoint.Port}'
```

2022-10-05 19:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/snippets/app.bicep
> +}
```suggestion
  params: {
    eksClusterName: 'YOUR-EKS-CLUSTER-NAME' // Replace this value
  }
}
```

2022-10-05 19:51 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/snippets/app.bicep
> +}
I've found that `rad resource expose containers` is a much simpler way to access a container in a quickstart, vs. adding in the concepts of gateways and routes. See here: https://radapp.dev/getting-started/quickstarts/environment-variables/#step-6-deploy-your-app

2022-10-05 19:53 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +1. To test your application, navigate to the public endpoint.
Markdown automatically increments the rendered number. Using `1.` for all items is preferred so it's easy to add items in later without needing to change all the downstream numbers 
![image](https://user-images.githubusercontent.com/54363786/194150541-04a4ab74-fc5e-413e-b025-a001146e3a3d.png)

2022-10-05 19:55 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +* How to deploy and view the status of an AWS resource
Are we viewing the status of an AWS resource in this quickstart?

2022-10-05 19:56 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +- Make sure you have an [AWS account](https://aws.amazon.com/premiumsupport/knowledge-center/create-and-activate-aws-account/0) and an [IAM user](https://docs.aws.amazon.com/IAM/latest/UserGuide/gett
```suggestion
- Make sure you have an [AWS account](https://aws.amazon.com/premiumsupport/knowledge-center/create-and-activate-aws-account/0) and an [IAM user](https://docs.aws.amazon.com/IAM/latest/UserGuide/getting-started_create-admin-group.html)
```
![image](https://user-images.githubusercontent.com/54363786/194150984-d1b804d4-7eb0-4cc3-bbb8-21a0346b0bee.png)

2022-10-05 19:58 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +Create the environment that you will be deploying your AWS resources to.
```suggestion
Create a [Radius environment]({{< ref environments >}}) where you will deploy your application.
```

AWS resources are not deployed into an environment, they're deployed to UCP. Only the application is deployed to the environment.

2022-10-05 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +This bicep file holds all of the information necessary to deploy a MemoryDB cluster to the same VPC as your EKS cluster. Deploying to the same VPC is the recommended way to access a MemoryDB cluster
This should be tweaked a bit to reflect that not all the information is here, as the EKS cluster name is being passed in as a parameter

```suggestion
This Bicep file defines a MemoryDB cluster, configuring it in the same VPC as your EKS cluster. Deploying to the same VPC is the recommended way to access a MemoryDB cluster from your EKS cluster.
```

2022-10-05 20:02 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +This bicep file deploys a publicly-accessible webapp which uses the MemoryDB we created in step 3 as a datastore.
```suggestion
This Bicep file defines a publicly-accessible webapp [container]({{< ref container >}}), which connects to the MemoryDB we created in step 3 and uses is as a datastore.
```

2022-10-05 20:02 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +{{< rad file="snippets/aws-memorydb.bicep" embed=true >}}
```suggestion

{{< rad file="snippets/aws-memorydb.bicep" embed=true >}}
```

Headers should have a space below them

2022-10-05 20:02 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +### app.bicep
```suggestion
### app.bicep

```

Headers should have a space beneath them

2022-10-05 20:03 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +   - Delete a todo item
Makes sure to add a cleanup section 

```suggestion
   - Delete a todo item
   
## Cleanup

```

2022-10-05 20:04 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +
```suggestion
```

2022-10-05 20:26 UTC, willdavsmith commented on docs/content/getting-started/quickstarts/aws-quickstart/snippets/aws-memorydb.bicep
> +output memoryDBConnectionString string = 'rediss://${memoryDBCluster.properties.ClusterEndpoint.Address}:${memoryDBCluster.properties.ClusterEndpoint.Port}'
this intentional, I think it specifies a redis connection with TLS: https://github.com/project-radius/samples/blob/e759c5d2a61485dc34b020cd5253fca4d0f69210/tutorial/src/server.ts#L65

2022-10-05 21:37 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/snippets/aws-memorydb.bicep
> +output memoryDBConnectionString string = 'rediss://${memoryDBCluster.properties.ClusterEndpoint.Address}:${memoryDBCluster.properties.ClusterEndpoint.Port}'
Perfect! Was wondering if that was the case

2022-10-05 21:41 UTC, willdavsmith commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +* How to deploy and view the status of an AWS resource
Updated this to 
```
This quickstart will teach you:
* How to create a Radius environment with an AWS cloud provider
* How to model an AWS resource in bicep
* How to use an AWS resource as part of your Radius application
``

2022-10-05 21:41 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +Alternatively, you could specify an existing MemoryDB resource to use:
I'd make this a tab instead of inline. With quickstarts when there's a branch in the road, it's best to have tabs represent the branches that you can switch between, vs. a linear path where you need to skip over parts once you make decisions.

2022-10-05 21:42 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +Alternatively, you could specify an existing MemoryDB resource to use:
See https://radapp.dev/contributing/contributing-docs/#tabbed-content

2022-10-07 21:35 UTC, willdavsmith commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +Alternatively, you could specify an existing MemoryDB resource to use:
Fixed

2022-10-07 22:05 UTC, jkotalik submitted a review, later dismissed

2022-10-07 22:40 UTC, Reshrahim submitted a review, later dismissed
Thank you @willdavsmit for running through all the feedback and making this work!!

Thanks to @vinayada1 and @asilverman too :)

2022-10-07 22:41 UTC, AaronCrawfis requested changes
Couple small updates

2022-10-07 22:41 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/aws-quickstart/index.md
> +Alternatively, you could specify an existing MemoryDB resource to use:
When saying "you could ..." it leaves the user asking "when would I use this?"

Instead, I'd say "If using your own custom subnets, supply them as a parameter:" (or something similar to that)

2022-10-07 22:42 UTC, AaronCrawfis commented
Also just opened https://github.com/project-radius/docs/pull/351 to fix the build issue

2022-10-10 15:55 UTC, AaronCrawfis approved these changes

2022-10-10 15:59 UTC, merged