minor language changes in tutorial
radius-project/docs pull request #384
Opened 2022-10-17 07:16 UTC by emily-potyraj

based on usability feedback

2022-10-17 16:07 UTC, DarqueWarrior submitted a review, later dismissed

2022-10-17 16:51 UTC, AaronCrawfis requested changes

2022-10-17 16:51 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/1-tutorial-environment/index.md
> +## Initialize a Radius Kubernetes environment
I'd be careful here because the environment is not platform-specific, the control-plane is. I think a better phrase would be:

```suggestion
## Initialize a Radius environment in Kubernetes
```

2022-10-17 16:51 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/1-tutorial-environment/index.md
> -   {{% alert title="💡 About namespaces" color="success" %}} When you initialize a Radius Kubernetes environment, Radius installs the control plane resources within    the `radius-system` namespace in
I think this is valuable information to have somewhere, about the distinction between the app namespace and the control-plane namespace.

Maybe something like "Note that this is separate from the `radius-system` namespace, where the [Radius control-plane services]({{< ref architecture >}}) run."

2022-10-17 17:14 UTC, emily-potyraj commented on docs/content/getting-started/tutorial/1-tutorial-environment/index.md
> +## Initialize a Radius Kubernetes environment
Please see line 26 below. Are you suggesting we scrub the docs and change all instances of "Radius Kubernetes environment" to "Radius environment in Kubernetes"?

2022-10-17 17:16 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/1-tutorial-environment/index.md
> +## Initialize a Radius Kubernetes environment
Yep, that's what I'm doing in https://github.com/project-radius/docs/pull/378 for this section

2022-10-20 05:32 UTC, emily-potyraj commented on docs/content/getting-started/tutorial/1-tutorial-environment/index.md
> +## Initialize a Radius Kubernetes environment
so just to triple-check: are we saying don't ever use the phrase "Radius Kubernetes environment" moving forward?

2022-10-20 05:39 UTC, emily-potyraj commented on docs/content/getting-started/tutorial/1-tutorial-environment/index.md
> -   {{% alert title="💡 About namespaces" color="success" %}} When you initialize a Radius Kubernetes environment, Radius installs the control plane resources within    the `radius-system` namespace in
I agree it's useful, but I'll pose a challenge to us. I don't know if this is a reflection on our docs or on the rad CLI functionality. 

What is the new Radius user going to do with this information about namespace? I agree that it's a useful detail, but at what point will it become important for them to know about? Is it important to the Day0 flow? Or even the Day 30, non-production flow? 

I probably didn't care about the `radius-system` namespace until I had to troubleshoot the control plane. But I'm definitely not remembering well enough to be counted as a new Radius user here. I'll keep an eye out to see if I can get more data in usability testing. 

For now, my thought is that 
1. If we did have a 30-second (or 5 min) flow in the docs: learning about the two namespaces - or even the Radius control plane itself - should probably not be included
2. For the 45-minute tutorial: ditto. Think about how we promote usage of codespaces, which already includes having radius installed. I think that indicates we're ok with people not having to think about the control plane during the tutorial. 

cc @rynowak

2022-10-20 22:02 UTC, emily-potyraj commented on docs/content/getting-started/tutorial/1-tutorial-environment/index.md
> -   {{% alert title="💡 About namespaces" color="success" %}} When you initialize a Radius Kubernetes environment, Radius installs the control plane resources within    the `radius-system` namespace in
for now, I will make the suggested language change to keep a note about namespaces in the tutorial. I will file a separate issue to debate whether new users should have to be aware of namespaces or the radius control plane.

2022-10-24 17:24 UTC, rynowak commented on docs/content/getting-started/tutorial/1-tutorial-environment/index.md
> -   {{% alert title="💡 About namespaces" color="success" %}} When you initialize a Radius Kubernetes environment, Radius installs the control plane resources within    the `radius-system` namespace in
I'm supportive of removing these details. I don't think the tutorial is the right place to explain things how Radius installation works.

2022-10-24 17:25 UTC, rynowak commented on docs/content/reference/limitations.md
> +Resources for a given type must currently have unique names within a [workspace]({{< ref workspaces >}}). For example, if two applications both have a `frontend` container resource, the first applica
I realize that this is fixing a broken link but it's pretty misleading. Workspaces are a client-side concept. You could have 5 workspaces that all point to the same resource group.

2022-11-16 20:42 UTC, AaronCrawfis approved these changes

2022-11-16 20:45 UTC, merged