Add extender resource
radius-project/docs pull request #39
Opened 2022-03-01 23:11 UTC by vinayada1

2022-03-07 20:40 UTC, AaronCrawfis requested changes

2022-03-07 20:40 UTC, AaronCrawfis commented on docs/content/resources/connectors/extender/_index.md
> +weight: 300
```suggestion
weight: 999
```

Let's place this at the bottom of the list for now

2022-03-07 20:40 UTC, AaronCrawfis commented on docs/content/resources/connectors/extender/snippets/extender.bicep
> +  name: 'myapp'
```suggestion
  name: 'myapp'
  
```

2022-03-07 20:40 UTC, AaronCrawfis commented on docs/content/resources/connectors/extender/snippets/extender.bicep
> +  }
```suggestion
  }
  
```

2022-03-07 20:40 UTC, AaronCrawfis commented on docs/content/resources/connectors/extender/snippets/extender.bicep
> +          TWILIO_NUMBER: twilio.properties.fromNumber
Is the intended design that you set `twilio.properties.properties.fromNumber`, but access `twilio.properties.fromNumber`?

2022-03-07 20:40 UTC, AaronCrawfis commented on docs/content/resources/connectors/extender/_index.md
> +{{< rad file="snippets/extender.bicep" embed=true marker="//SAMPLE" >}}
```suggestion
{{< rad file="snippets/extender.bicep" embed=true >}}
```

Since the code snippet doesn't have any markers you can omit this

2022-03-07 22:25 UTC, vinayada1 commented on docs/content/resources/connectors/extender/snippets/extender.bicep
> +          TWILIO_NUMBER: twilio.properties.fromNumber
Yes....the inner properties is at the same level as secrets.

2022-03-07 23:42 UTC, AaronCrawfis commented on docs/content/resources/connectors/extender/snippets/extender.bicep
> +          TWILIO_NUMBER: twilio.properties.fromNumber
Is there a technical limitation to needing to nest `properties`, or could we update the design so we can get and set `twilio.properties.*`?

2022-03-09 19:50 UTC, AaronCrawfis commented on docs/content/resources/connectors/extender/_index.md
> +| <key-value pairs> | Properties of the extender | Could be any key-value pairs - fromNumber: '222-222-2222'
```suggestion
| \<user-defined key-value pairs\> | User-defined properties of the extender. Can accept any key name except 'secrets'. | `fromNumber: '222-222-2222'`
```

Need to escape the </> characters. Also adding some clarification.

2022-03-10 19:12 UTC, vinayada1 commented on docs/content/resources/connectors/extender/snippets/extender.bicep
> +          TWILIO_NUMBER: twilio.properties.fromNumber
Fixed to remove extra properties

2022-03-11 00:33 UTC, AaronCrawfis approved these changes

2022-03-11 00:33 UTC, merged