Adding workload identity quickstarts
radius-project/docs pull request #411
Opened 2022-11-08 16:55 UTC by sk593

Adding quickstarts for workload identity support with containers and volume mounts. Work is tracked as part of the WI identity [feature](https://github.com/project-radius/radius/issues/4305) and references this documentation [task](https://github.com/project-radius/radius/issues/3592)

2022-11-08 19:59 UTC, youngbupark commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +- Connect a container to an Azure resource using workload identity
@AaronCrawfis @sk593 Will we add keyvault persistent volume doc separately?

2022-11-08 20:04 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +- Connect a container to an Azure resource using workload identity
Yep that will be a separate quickstart that @sk593 is also working on

Then there will separately be the reference page which is already written, just needs to be unhidden

2022-11-08 20:40 UTC, sk593 commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +- Connect a container to an Azure resource using workload identity
^I'll submit a separate PR for that quickstart once it's working

2022-11-08 20:50 UTC, AaronCrawfis requested changes

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +---
Could you rename this file to `_index.md` please? Changes how images are handled in hugo

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +linkTitle: "Container workload identity"
```suggestion
linkTitle: "Connect to Azure resources"
```

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +description: "Learn how to connect a container to an Azure resource using workload identity"
```suggestion
description: "Learn how to connect a container to an Azure resource with managed identities and RBAC" 
```

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +slug: 'container-wi'
```suggestion
slug: 'azure-connection'
```

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +- Connect a container to an Azure resource using workload identity
```suggestion
- Setup a Radius environment with an identity provider
- Define a connection to an Azure resource with Azure AD role-based access control (RBAC) assignments
- Leverage Azure managed identities to connect to an Azure resource
```

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +   - This quickstart is a Radius version of the [Azure AD workload identity quickstart](https://azure.github.io/azure-workload-identity/docs/quick-start.html)
```suggestion
- [rad CLI]({{< ref getting-started >}}) installed on your machine
- [Supported Kubernetes cluster]({{< ref kubernetes >}}) deployed with [Azure AD Workload Identity](https://azure.github.io/azure-workload-identity/docs/installation.html) installed
```

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +
```suggestion

The steps below will showcase a "rad-ified" version of the existing [Azure AD workload identity quickstart](https://azure.github.io/azure-workload-identity/docs/quick-start.html).

```

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +   rad env init kubernetes --environment default --provider-azure --provider-azure-resource-group <AZURE_RESOURCE_GROUP> --provider-azure-client-id <AZURE_CLIENT_ID> --provider-azure-client-secret <A
```suggestion
rad env init kubernetes -i
```

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +Begin by running `rad env init kubernetes` and configuring an Azure cloud provider:
```suggestion
Begin by running [`rad env init kubernetes`]({{< ref rad_env_init_kubernetes >}}). Make sure to configure an Azure cloud provider:
```

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +## Step 2: Define an app and a container
You'll need the user to define a Radius environment with the `identity` property set. I'd have step 2 be adding the import/params/environment, and then step 3 is adding the application, container, and KeyVault.

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +```bash
```suggestion
   ```bash
```

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +<img src="wi-secret-output.png" width=500px alt="Screeshot of output showing that the secret is now accessible with workload identity">
I'd make this a ```txt block instead of a screenshot

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/snippets/container-wi.bicep
> +param port int = 3000
No need to make this a parameter. I'd just hardcode it on the container definition

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/snippets/container-wi.bicep
> +param keyvaultTenantID string = subscription().tenantId
Does this need to be a parameter? I'd just hardcode the function on the Key Vault resource

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/snippets/container-wi.bicep
> +  name: 'someotherenv'
```suggestion
  name: 'iam-quickstart'
```

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/snippets/container-wi.bicep
> +      namespace: 'someotherenv'
```suggestion
      namespace: 'iamquickstart'
```

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/snippets/container-wi.bicep
> +}
```suggestion
}

```

2022-11-08 20:50 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/snippets/container-wi.bicep
> +  }
```suggestion
  }
  
```

2022-11-08 20:50 UTC, AaronCrawfis commented
Also you should target the `edge` branch instead of `v0.14`

2022-11-09 00:55 UTC, sk593 commented
> AaronCrawfis

Got it, is there a way to change the branch on this PR?

2022-11-09 01:01 UTC, sk593 commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +## Step 2: Define an app and a container
Added an additional step for this

2022-11-11 19:22 UTC, sk593 commented
Will re-open this PR with v0.15 as the target branch

2022-11-11 19:22 UTC, closed without merging