Adding container and key vault volume WI quickstarts
radius-project/docs pull request #423
Opened 2022-11-11 19:37 UTC by sk593

2022-11-11 19:39 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/_index.md
> +   ```
These 2 lines can drop the indentation (can't make a suggestion because it contains a ```)

2022-11-11 19:42 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/_index.md
> +Create a file named `app.bicep` and define a Radius environment with the identity property set:
```suggestion
Create a file named `app.bicep` and define a Radius environment with the [identity property]({{< ref environments >}}) set:
```

#412 adds a new section on the identity property. Adding the cross link now so once that gets merged it will reference it.

2022-11-11 19:42 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/_index.md
> +Add a Radius application, [container]({{< ref container >}}), and Key vault to your `app.bicep` file:
```suggestion
Add a Radius application, Radius [container]({{< ref container >}}), and an Azure Key Vault to your `app.bicep` file:
```

2022-11-11 19:43 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/_index.md
> +   ```
You can drop the indent on these lines as well

2022-11-11 19:43 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/_index.md
> +Deploy your app by specifying the OIDC issuer URL. To retrieve the OIDC issuer URL, follow the Azure Workload Identity installation guide.
```suggestion
Deploy your app by specifying the OIDC issuer URL. To retrieve the OIDC issuer URL, follow the [Azure Workload Identity installation guide](https://azure.github.io/azure-workload-identity/docs/installation.html).
```

2022-11-11 19:44 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/_index.md
> +```bash
```suggestion
   ```bash
```

2022-11-11 19:45 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/_index.md
> +```
These should be indented by 3 spaces because it's nested under a numbered list

2022-11-11 19:46 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/_index.md
> +Run the following command to delete your app and container:
I'd make this a numbered list, as you'll also need to add a step on deleting the keyvault. Can be a simple "make sure to delete the keyvault that was deployed via the Azure portal or az CLI

2022-11-11 19:46 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/snippets/container-wi-1.bicep
> +#disable-next-line no-hardcoded-env-urls
```suggestion
```

I don't believe this is needed as a default isn't specified

2022-11-11 19:48 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/snippets/container-wi-2.bicep
> +import radius as radius
I think you can collapse these down into 2 files and then use 2 separate markers (//ENVIRONMENT and //CONTAINER), instead of having 2 separate files

2022-11-11 19:49 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/_index.md
> +2. You should see the contents of the secret defined in your `app.bicep` file:
```suggestion
2. You should see the contents of the secret from your Key Vault:
```

Makes it a little clearer that the value is being read from the Key Vault itseslf

2022-11-11 20:01 UTC, AaronCrawfis requested changes

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/_index.md
> +title: "Quickstart: Mount a Key vault as a volume to a container"
```suggestion
title: "Quickstart: Mount an Azure Key Vault as a volume to a container"
```

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/_index.md
> +linkTitle: "Mount a Key vault as a volume"
```suggestion
linkTitle: "Persistent Key Vault volume"
```

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/_index.md
> +description: "Learn how to mount an Azure Key vault as a volume to a container"
```suggestion
description: "Learn how to mount an Azure Key Vault as a volume to a container" 
```

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/_index.md
> +slug: 'keyvault-wi'
```suggestion
slug: 'volume-keyvault'
```

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/_index.md
> +- [Supported Kubernetes cluster]({{< ref kubernetes >}}) deployed with [Azure AD Workload Identity](https://azure.github.io/azure-workload-identity/docs/installation.html) installed
@youngbupark does the user also need to install the Azure Key Vault CSI driver or do we install it for them? (Ideally they need to install it themselves and we don't do it)

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/_index.md
> +## Step 1: Run `rad env init kubernetes`
```suggestion
## Step 1: Initialize Radius
```

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/_index.md
> +## Step 1: Run `rad env init kubernetes`
```suggestion
## Step 1: Initialize Radius
```

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/_index.md
> +   ```
These can lose the indentation

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/_index.md
> +## Step 3: Define an app, container, Key vault, and volume
```suggestion
## Step 3: Define an app, container, Key Vault, and volume
```

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/_index.md
> +{{< rad file="snippets/keyvault-wi-2.bicep" embed=true marker="//VOLUME" >}}
For these steps I'd do the application, volume, and Azure Key Vault first, and then in the 2nd step add the container. They way you just paste the resources once and don't need to edit them.

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/_index.md
> +   ```
Indentation

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/_index.md
> +## Step 5: Verify access to the Key vault
```suggestion
## Step 5: Verify access to the mounted Azure Key Vault
```

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/_index.md
> +```bash
```suggestion
   ```bash
```

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/snippets/keyvault-wi-1.bicep
> +import radius as rad
I think you can combine this file into the other one and use a different marker (//ENVIRONMENT)

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/snippets/keyvault-wi-1.bicep
> +#disable-next-line no-hardcoded-env-urls
```suggestion
```

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/snippets/keyvault-wi-2.bicep
> +#disable-next-line no-hardcoded-env-urls
```suggestion
```

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/snippets/keyvault-wi-2.bicep
> +param location string = resourceGroup().location
```suggestion
param location string = 'global'

@description('Specifies the location for Azure resources')
param azLocation string = resourceGroup().location
```

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/snippets/keyvault-wi-2.bicep
> +@description('Specifies the location for resources.')
```suggestion
@description('Specifies the location for Radius resources.')
```

2022-11-11 20:01 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/snippets/keyvault-wi-2.bicep
> +  location: location
```suggestion
  location: azLocation
```

2022-11-11 20:39 UTC, sk593 commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/_index.md
> +- [Supported Kubernetes cluster]({{< ref kubernetes >}}) deployed with [Azure AD Workload Identity](https://azure.github.io/azure-workload-identity/docs/installation.html) installed
Oh yes, they do. I had added it but I must've deleted it when revising. I'll add a link for this

2022-11-11 21:24 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/snippets/container-wi.bicep
> +param azLocation string = 'westus3'
```suggestion
param azLocation string = resourceGroup().location
```

2022-11-11 21:27 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/_index.md
> +2. Then, add a Radius [container]({{< ref container >}}):
```suggestion
2. Then, add a Radius [container]({{< ref container >}}) with a volume mount for the Radius volume:
```

2022-11-11 21:27 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/_index.md
> +1. Add a Radius application, an Azure Key Vault, and a volume to your `app.bicep` file:
```suggestion
1. Add a Radius application, an Azure Key Vault, and a volume which uses the Key Vault to your `app.bicep` file:
```

2022-11-11 21:29 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/snippets/keyvault-wi.bicep
> +  name: 'vqs-${uniqueString(resourceGroup().id)}'
```suggestion
  name: 'myvolume'
```

2022-11-11 21:30 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/snippets/keyvault-wi.bicep
> +      args: ['-c', 'while true; do ls /var/secrets; sleep 10;done']
Instead of `ls /var/secrets`, I wonder if `cat /var/secrets/mysecret` would be better to show that it can read the secret value

2022-11-11 21:31 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/snippets/keyvault-wi.bicep
> +      }
Since this container doesn't expose an endpoint you can remove this

```suggestion
```

2022-11-11 21:31 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/snippets/keyvault-wi.bicep
> +    }
The volume mount is doing the connection, you don't need this

```suggestion
```

2022-11-11 21:32 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/snippets/keyvault-wi.bicep
> +        scope: rootScope
```suggestion
        scope: resourceGroup().id
```

2022-11-11 21:32 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/snippets/keyvault-wi.bicep
> +param rootScope string = resourceGroup().id
```suggestion
```

We can simplify this a little bit

2022-11-11 22:10 UTC, sk593 commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/snippets/keyvault-wi.bicep
> +      args: ['-c', 'while true; do ls /var/secrets; sleep 10;done']
I did try that but I was getting this output: 
<img width="591" alt="Screenshot 2022-11-11 at 2 02 13 PM" src="https://user-images.githubusercontent.com/42750942/201437784-ff0273d0-d9a4-491c-b169-18e54fad89e1.png">

I can debug more and see why because I agree this would probably be better

2022-11-16 20:56 UTC, AaronCrawfis approved these changes

2022-11-16 20:56 UTC, merged