another version of the first-application flow
radius-project/docs pull request #425
Opened 2022-11-22 00:33 UTC by emily-potyraj

2022-11-29 20:22 UTC, emily-potyraj commented
temporarily marking as "ready for review" against edge branch to trigger the website building.

2022-11-29 20:27 UTC, emily-potyraj commented
staging site it available at: 
https://wonderful-plant-020417a1e.azurestaticapps.net/getting-started/first-application/

page to review: Getting Started > Run your first application

2022-12-02 17:10 UTC, AaronCrawfis requested changes

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +The quickest way to get started using Radius is to install Radius and deploy your first Radius app.
The style of this sentence matches more of a description than it does the intro paragraph. I'd either move this into the description of the page or reword it to:

```suggestion
This guide offers the quickest way to get started using Radius. You'll walk through both installing Radius and running your first Radius app.
```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +(Estimated duration 10 min)
```suggestion
**Estimated duration 10 min**
```

Parentheses feel out of place, I think bold may make more sense

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +Radius workflows run inside Kubernetes. Bring whichever flavor of Kubernetes cluster you prefer.
```suggestion
The Radius control plane runs in your [Kubernetes]({{< ref kubernetes >}}) cluster. Make sure to have a supported cluster ready to go.

{{< button text="Supported clusters" page="kubernetes#supported-clusters" >}}
```

Not sure what a Radius workflow is

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +If you don't have a perferred way to create Kubernetes clusters, you might try using [k3d](https://k3d.io/v5.4.6/), which runs a minimal Kubernetes distribution in Docker.
Are we killing the Codespace option? I think that would offer the quickest way for users. If so we should still link to the supported clusters section. I wouldn't link to the k3d docs since it offers incomplete installation steps.

```suggestion
[k3d]({{< ref "kubernetes#supported-clusters" >}}) is a great option for running a lightweight Kubernetes distribution in Docker.
```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +### 2. Install Radius
```suggestion
### 2. Install the rad CLI
```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +### 2. Install Radius
Does this section intend to replace the Getting Started page where we already have installation instructions for the CLI? I'd be cautious to duplicate all that content and effectively have two divergent getting started guides.

Perhaps instead we revamp the getting started section and make a dedicated "Install rad CLI" page?

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +curl -fsSL "https://radiuspublic.blob.core.windows.net/tools/rad/install.sh" | /bin/bash -s edge
```suggestion
curl -fsSL "https://get.radapp.dev/tools/rad/install.sh" | /bin/bash
```

Switching to CDN link. Also we shouldn't use the edge build for the final version of this page

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +wget -q "https://radiuspublic.blob.core.windows.net/tools/rad/install.sh" -O - | /bin/bash -s edge
```suggestion
wget -q "https://get.radapp.dev/tools/rad/install.sh" -O - | /bin/bash
```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +$script=iwr -useb  https://radiuspublic.blob.core.windows.net/tools/rad/install.ps1; $block=[ScriptBlock]::Create($script); invoke-command -ScriptBlock $block -ArgumentList edge
```suggestion
iwr -useb "https://get.radapp.dev/tools/rad/install.ps1" | iex
```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +
```suggestion
```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +### 3. Launch a Radius environment
We're doing more than just launching a Radius environment in this step. I think "Initialize Radius" would make more sense.

```suggestion
### 3. Initialize Radius
```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +Create an empty directory to hold the app. Navigate into it.
```suggestion
Create a new directory for your app and navigate into it:

```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +cd first-application
```suggestion
mkdir demo && cd demoo
```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
>  ```bicep
I think the app description and deployment should be a separate step, there's too much currently in step 3

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
I think it's important to still show the output here. Perhaps we can make it part of a collapsible "output" section

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +> This file will run the `radius.azurecr.io/tutorial/demo` image. This image is published by the Radius team to a public registry, you do not need to create it.
Can this be a comment in the Bicep file instead?

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +- runs the application in a Kubernetes namespace
```suggestion
- Deploys the application to Kubernetes
```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +- opens a port-forward from localhost to port 3000 inside the container so you can navigate to the app's frontend UI.
```suggestion
- Creates a port-forward so you can navigate to the app's frontend UI
```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +- starts streaming container logs to the terminal
```suggestion
- Streams container logs to your terminal
```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +Access the application by opening [http://locahost:3000](http://localhost:3000) in a browser.
This should be part of its own step

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +### Bonus: Add a database to the app
I don't think this should be a "Bonus". It should be it's own step inline with the rest of the steps. It's confusing to say "Congrats! You're done. But not really. Keep going, but it's a bonus"

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +Instead of defining the Redis Cache resource yourself from scratch, you can leverage existing infrastructure templates, called [Recipes]({{< ref recipes >}}). The Radius community provides Recipes fo
```suggestion
You can leverage a Radius [Recipe]({{< ref recipes >}}) to automate the deployment of a lightweight, containerized Redis cache.
```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +Open `app.bicep` in your editor and replace the file contents with the below snippet.
```suggestion
Open `app.bicep` in your editor and replace the file contents with the below snippet:
```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +Re-run the app to launch the database.
This should be its own step

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +- You've connected the `demo` container to `redis` using an environment variable that Radius automatically sets.
```suggestion
The `redis` resource you just added deploys a new Redis cache to your environment. Your `demo` container can connect to this cache, which will automatically inject the connection details into your container's environment variables.
```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +Using the TODO page will update the saved state in Redis. Thanks to functionality defined in the Redis Recipe, you will see console output from the `redis` resource for each of these operations.
```suggestion
The TODO page will now persist your to-do items in Redis. You can verify your data is being persisted by referencing the logs in your terminal window.
```

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +Using the TODO page will update the saved state in Redis. Thanks to functionality defined in the Redis Recipe, you will see console output from the `redis` resource for each of these operations.
Should we also add a note on checking the environment variables page to see that the connection details were automatically set?

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
We should keep the dashboard section in. Or even better the dashboard can automatically launch as part of `rad run` instead of needing to call a special command.

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +If you'd like to delete your app, see [rad app delete]({{< ref rad_application_delete >}}).
This should be its own step and not be optional

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +In just a few minutes, you were able to add a Redis database to your app **without** having to learn Redis-specific info about programming model, security practices, or access management.
This should be part of a dedicated recap section

2022-12-02 17:10 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +{{< button text="Next step: Radius Quickstarts >>" page="getting-started/quickstarts" >}}
This should be part of a dedicated "Next steps" section or be rolled into a "Recap and next steps" section with the previous content

2022-12-07 17:29 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +If you don't have a perferred way to create Kubernetes clusters, you might try using [k3d](https://k3d.io/v5.4.6/), which runs a minimal Kubernetes distribution in Docker.
We don't have strong signal on codespaces. Literally **everyone** scrolls past it, and then says "maybe codespaces would be a good idea."

I think we should optimize for this content being shorter and presenting fewer choices.

2022-12-07 17:30 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
Do we have that capability?

2022-12-07 17:31 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +Access the application by opening [http://locahost:3000](http://localhost:3000) in a browser.
We intentionally combined a bunch of things into fewer steps from my original draft, and we both thought it flows a lot better.

2022-12-07 17:35 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
Some inline html should do the trick. Or we could write a dedicated shortcode if we don't want raw HTML in the pages

```html
<details>
    <summary>Details</summary>
    Something small enough to escape casual notice.
</details>
```

2022-12-07 17:37 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +If you don't have a perferred way to create Kubernetes clusters, you might try using [k3d](https://k3d.io/v5.4.6/), which runs a minimal Kubernetes distribution in Docker.
Based on our experiences and feedback on the current flow, we should cut everything that's not required from this page.  We already cut the VSCode extension. We should also cut codespaces.

2022-12-07 17:39 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +### 2. Install Radius
Why is the distinction important? `Install Radius` is a lot less complex to understand than `Install the rad CLI`. 

The goal is for this page to be self contained and streamlined. If we end up duplicating a small amount of content, that's fine.

2022-12-07 17:42 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +Radius workflows run inside Kubernetes. Bring whichever flavor of Kubernetes cluster you prefer.
I really do not want to see the term 'control plane' on this page. The audience does not know what that means.

I also agree on workflow, this isn't a term we use, and has a bunch of implications that compare radius to other systems it's not similar to.

2022-12-07 17:44 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +Using the TODO page will update the saved state in Redis. Thanks to functionality defined in the Redis Recipe, you will see console output from the `redis` resource for each of these operations.
We had this originally and cut it because it seems non-critical. I'm on the fence about whether this point in the workflow is the right time to bring it back.

2022-12-07 17:53 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +Using the TODO page will update the saved state in Redis. Thanks to functionality defined in the Redis Recipe, you will see console output from the `redis` resource for each of these operations.
Makes sense. Although since the environment variables page is the default landing page, people will see it regardless

2022-12-07 23:06 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
This feels like a really good thing for us to start doing w/ output.

2022-12-07 23:08 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +- runs the application in a Kubernetes namespace
No. We're being specific in using the word run. 

Previously this said `deploy`. The feedback we got is that people have different connotations to the word `deploy`. We're also having users run the command `rad run` and the mismatch is something we also got feedback on 😆

2022-12-07 23:10 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +- opens a port-forward from localhost to port 3000 inside the container so you can navigate to the app's frontend UI.
Why is create better than open? Which is more obvious?

I **do** think it's important include the port number here. We want that to be unambiguous.

2022-12-07 23:11 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +### Bonus: Add a database to the app
I agree. I think the thing we should settle is whether this is going to be on the same page or not.

2022-12-07 23:12 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +Instead of defining the Redis Cache resource yourself from scratch, you can leverage existing infrastructure templates, called [Recipes]({{< ref recipes >}}). The Radius community provides Recipes fo
We're being intentional here in hyping up the community provided nature of recipes. Recipes is the main thing we really want to pop from this doc.

2022-12-07 23:13 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +- You've connected the `demo` container to `redis` using an environment variable that Radius automatically sets.
> Your `demo` container can connect to this cache

This language implies that there's more for the user to do, but we've already done the work to wire things up.

2022-12-07 23:13 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
Either way the dashboard section will be removed when this is merged. We don't have the dashboard yet.

2022-12-07 23:15 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +cd first-application
This is intentional. The container is called demo. We want to avoid the application and container being named the same thing.

I'm open to suggestions also long as we avoid this problem.

2022-12-07 23:17 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
>  ```bicep
We're trying to limit the number of steps. Feedback from showing early drafts of this is that it felt long because there were too many steps, and that some of the steps were insignificant. 

Consolidating things into chunky steps was one of the big changes from my draft to emily's and it felt really good to make that change.

2022-12-07 23:18 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
I'm not yet convinced that introducing the dashboard this early helps, which is the thing we should be debating.

2022-12-08 01:03 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +Using the TODO page will update the saved state in Redis. Thanks to functionality defined in the Redis Recipe, you will see console output from the `redis` resource for each of these operations.
is it worth changing the default landing page of the app?

2022-12-08 01:07 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +### 2. Install Radius
+1 to having a small amount of duplicated content. 

I see this page as less of a guide on how to use Radius and more of a sequence to follow to feel like you did something with Radius. IMO we can still have a whole Install the CLI page elsewhere in addition to this page so that we have two views of that content. For example, we want people to easily learn how to install the VS Code extension once they decide to use Radius, but we intentionally left it off this page because we only want essentials here. Ditto for instructions on installing other releases of the CLI.

2022-12-08 01:09 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +If you don't have a perferred way to create Kubernetes clusters, you might try using [k3d](https://k3d.io/v5.4.6/), which runs a minimal Kubernetes distribution in Docker.
I like the idea of this page saying "we assume you've got a cluster." 
If we want to provide one additional hint for people who don't happen to have a cluster, that seems nice and lightweight.

What do we think about not mentioning k3d or any specific distros here but instead pointing users to codespaces as our one hint?

2022-12-08 01:14 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +Radius workflows run inside Kubernetes. Bring whichever flavor of Kubernetes cluster you prefer.
Haha so let's hunt for a phrase we all like 🙂

Maybe 
1. "Radius runs inside Kubernetes."
2. "Radius deploys apps into your Kubernetes cluster."
3. "The Radius service runs in a Kubernetes cluster."  <-- yes, I know it's more than 1 service, but "services" could be concept overload. 
4. "Make sure you have a Kubernetes cluster ready where you can set up Radius." <-- is "set up" generic enough? "use Radius"?

2022-12-08 01:19 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
The target punchline that this flow has been aiming towards is "Radius is the easiest way for you to deploy and manage cloud-native apps." 

@AaronCrawfis - is there a "wow" we hope the Dashboard can hit towards that goal (without introducing more low-level concepts) that haven't been hit by the rest of the flow?

2022-12-08 20:05 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +### 2. Install Radius
leaving as generically "install Radius" for now. Let's put it out there and get feedback on whether readers want more info here.

2022-12-08 20:11 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +cd first-application
I'll condense it into 1 command but use the name `first-application`

2022-12-08 20:18 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
I love the idea of a shortcode for it and doing that more on other pages. Filed https://github.com/project-radius/docs/issues/440 for that change so we don't block this PR on it.

2022-12-08 20:20 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +> This file will run the `radius.azurecr.io/tutorial/demo` image. This image is published by the Radius team to a public registry, you do not need to create it.
Good suggestion. Let's be on the lookout for possibly making this change in the future. Some of the usability feedback we got about the Tutorial was users wanting to know where the image in the tutorial app was coming from, so let's lean towards being super explicit about it for now and see how that's received.

2022-12-08 20:21 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +- opens a port-forward from localhost to port 3000 inside the container so you can navigate to the app's frontend UI.
Current text for now will be a compromise: 
> Creates a port-forward from localhost to port 3000 inside the container so you can navigate to the app's frontend UI.

2022-12-08 20:23 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +### Bonus: Add a database to the app
Good point. 
Let's put the header like so for now:
> 5. Add a database to the app

2022-12-08 20:24 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +Instead of defining the Redis Cache resource yourself from scratch, you can leverage existing infrastructure templates, called [Recipes]({{< ref recipes >}}). The Radius community provides Recipes fo
combined language from both suggestions for now.

2022-12-08 20:28 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +Re-run the app to launch the database.
agreed now that we are numbering the "add database" step as #5.

2022-12-08 21:37 UTC, shalabhms commented on docs/content/getting-started/first-application/_index.md
> +Radius workflows run inside Kubernetes. Bring whichever flavor of Kubernetes cluster you prefer.
"workflow" is very heavy term and subjected to different understandings.  One suggestion would be to just use "Radius runs on Kubernetes" . "Inside Kubernetes" might give an understanding that Radius is part of Kubernetes runtime.

2022-12-08 21:37 UTC, shalabhms commented on docs/content/getting-started/first-application/_index.md
> +Radius workflows run inside Kubernetes. Bring whichever flavor of Kubernetes cluster you prefer.
"whichever flavor" phrase is very open term.  One suggestion could be to phrase simply - " Get your Kubernetes cluster ready"

2022-12-08 21:37 UTC, shalabhms commented on docs/content/getting-started/first-application/_index.md
> +### 2. Install Radius
I agree to keep the same phrase - "Install Radius"

2022-12-08 21:37 UTC, shalabhms commented on docs/content/getting-started/first-application/_index.md
> +curl -fsSL "https://radiuspublic.blob.core.windows.net/tools/rad/install.sh" | /bin/bash -s edge
Just wondering about the Tabs order for OS type . Can we have them ordered as usage wise - like "Linux" as the first tab.

2022-12-08 21:37 UTC, shalabhms commented on docs/content/getting-started/first-application/_index.md
> +### 2. Install Radius
In the description though, we can say (suggestion)- "This will install the Radius CLI to interact with Radius"

2022-12-08 21:37 UTC, shalabhms commented on docs/content/getting-started/first-application/_index.md
> +cd first-application
Can we use name as "my-app" ?

2022-12-08 21:37 UTC, shalabhms commented on docs/content/getting-started/first-application/_index.md
> +### Bonus: Add a database to the app
My suggestion is to keep it on the same page only.

2022-12-08 21:37 UTC, shalabhms commented on docs/content/getting-started/first-application/_index.md
> +Re-run the app to launch the database.
Instead of "launch", how about "add" ? Like "Re-run the app to add the database"

2022-12-08 21:51 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +curl -fsSL "https://radiuspublic.blob.core.windows.net/tools/rad/install.sh" | /bin/bash -s edge
tabs order for OS type has been a hot item :)
We got lots of strong feedback from users so far that not putting the Mac tab was surprising (and sometimes even frustrating). 

Let's leave the current tab order as is now downstream of that previous feedback and see what users say now. We definitely heard that Windows shouldn't be the first tab (both because of usage volume and because it leans us into appearing "Microsoft-y"). But perhaps we'll hear that we should bump Linux to be ahead of Mac.

2022-12-08 22:43 UTC, AaronCrawfis requested changes
Liking the simplicity and single page. But will need some link fixes and some additional work for the Redis Link to complete it out with what we have today

2022-12-08 22:43 UTC, AaronCrawfis commented on docs/content/getting-started/tutorial/_index.md
> +toc_hide: true
We will also need to do a find and replace for `{{< ref tutorial >}}` and turn it into `{{< ref first-application >}}`

2022-12-08 22:43 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +{{% /pageinfo %}}
If we're now hiding the tutorial this should be removed

2022-12-08 22:43 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +```bicep
This should be a snippet instead of embedded directly in the page

2022-12-08 22:43 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +```bicep
This should also be an embedded snippet instead of directly in the page

2022-12-08 22:43 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
In the future the dashboard will show the app diagram with information about what's actually running each piece. Since this is replacing the tutorial now we can add this in the future

2022-12-08 22:43 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +What else do you want to build? Visit our Recipe catalog << link to catalog >> to explore all the available building blocks.
This line should be removed

2022-12-08 22:43 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +    mode: 'recipe'
Recipes aren't available yet so we'll need to switch to using a module or embedding Kubernetes resources here.

2022-12-08 22:43 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +To delete your app, see [rad app delete]({{< ref rad_application_delete >}}).
There will also need to be a cleanup step here for the Kubernetes resources since they aren't deleted with the application

2022-12-08 23:21 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +**Estimated duration 10 min**
```suggestion
**Estimated time to complete: 10 min**
```

2022-12-08 23:21 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +### 2. Install Radius
I agree with calling it the "Radius CLI" as "rad CLI" might be interpreted as the rad 🤙 CLI (i.e. merely an adjective describing some CLI as "radical").

2022-12-08 23:21 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +> You may be prompted for your sudo password during installation, as the installer places the `rad` binary under `/usr/local/bin`. If you are unable to sudo you can install the rad CLI to another dir
```suggestion
> You may be prompted for your admin password (`sudo`) during installation, as the installer places the `rad` binary under `/usr/local/bin`. If you are unable to use `sudo`, you can install the rad CLI to another directory by setting the `RADIUS_INSTALL_DIR` environment variable with your desired install path.
```

2022-12-08 23:21 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +Verify the rad CLI is installed correctly by running `rad version`.
recommend adding an example of the console output that shows a correct installation.

2022-12-08 23:21 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +Initialize Radius. For this example, accept all the default options (press ENTER to confirm).
```suggestion
Initialize Radius. For this example, accept all the default options (press ENTER to confirm):
```

2022-12-08 23:21 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +Initialize Radius. For this example, accept all the default options (press ENTER to confirm).
might also consider showing the console output for what the default options confirmation looks like.

2022-12-08 23:21 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +In addition to starting Radius services in your Kubernetes cluster, this initialization command creates a default application `app.bicep` as your starting point. It contains a single container defini
```suggestion
In addition to starting Radius services in your Kubernetes cluster, this initialization command creates a default application called `app.bicep` as your starting point. It contains a single container definition named `demo`. 
```

2022-12-08 23:21 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +> This file will run the `radius.azurecr.io/tutorial/demo` image. This image is published by the Radius team to a public registry, you do not need to create it.
Maybe put the comment above the Bicep file so that the reader can get some context before looking at the file?

2022-12-08 23:21 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +- Creates a port-forward from localhost to port 3000 inside the container so you can navigate to the app's frontend UI.
```suggestion
- Creates a port-forward from localhost to port 3000 inside the container so you can navigate to the app's frontend UI
```

2022-12-08 23:21 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +It's easy to build on the default app and add more resources to the app.
I don't know the exact context of where this tutorial will be positioned in the Radius docs, but this statement feels like it has the potential to sound condescending for the user given that it assumes they have the same definition of "easy". Perhaps linking to instructions/docs about these "easy" tasks might help here?

2022-12-08 23:21 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +### 6. Re-run the app to add the database.
```suggestion
### 6. Re-run the app to add the database
```

2022-12-08 23:21 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +Open your browser to [http://locahost:3000](http://localhost:3000) again to test out the application.
```suggestion
Open your browser and navigate to [http://locahost:3000](http://localhost:3000) again to test out the application. 
```

2022-12-08 23:21 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +The TODO page will now persist your to-do items in Redis. You can verify your data is being persisted by referencing the logs in your terminal window.
suggest showing an example of the terminal output to let the user know what to look for in the logs in case they're not familiar with Redis.

2022-12-08 23:21 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +Press CTRL+C when you're finished with the website.
```suggestion
When you're finished with this tutorial, you can terminate the application by pressing CTRL+C in the terminal that your Radius app is running.
```

2022-12-08 23:21 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +What else do you want to build? Visit our Recipe catalog << link to catalog >> to explore all the available building blocks.
```suggestion
What else can you build with Radius? Visit our Recipe catalog << link to catalog >> to explore all the available building blocks. 
```

2022-12-08 23:22 UTC, willtsai commented
added some comments and suggestions -- feel free to use or drop anything as you see fit.

2022-12-09 20:50 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +{{% /pageinfo %}}
Yes. This is ready to be removed if we're about to merge it.

2022-12-09 20:51 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +What else do you want to build? Visit our Recipe catalog << link to catalog >> to explore all the available building blocks.
We should remove the mentions of recipes and redis all together. This was here so we could debate what to include - but it's not ready to use so it needs to be removed.

2022-12-09 20:52 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +    mode: 'recipe'
No, we should cut it altogether until its ready.

2022-12-09 20:53 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +> You may be prompted for your sudo password during installation, as the installer places the `rad` binary under `/usr/local/bin`. If you are unable to sudo you can install the rad CLI to another dir
@emily-potyraj - can we find a way to cut this section? This seems like something the CLI install script should just tell the user instead of us putting it in docs.

2022-12-09 20:55 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +Press CTRL+C when you're finished with the website.
Saying that this "terminates the application" or "in the teminal that your Radius app is running" are misleading, none of these are accurate. 

What do think is important to communicate here beyond "CTRL+C to exit"?

2022-12-09 20:58 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +If you don't have a perferred way to create Kubernetes clusters, you might try using a [Radius codespace](https://aka.ms/ProjectRadius/Codespace), which provides a cluster with Radius pre-installed.
I don't think we can/should mention the codespace here at all. We've had issues getting networking to work and I'm not sure if the story is any better now that we use port-forwards.

2022-12-09 20:59 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +}
Need to update this to match reality. We need to include API Version, location, and application property.

2022-12-09 21:00 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +
We should cut off at this point. Recipes are still a work in progress.

2022-12-09 21:02 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +
I'm not sure that we should cut off here. Our tagline is "your app is more than just Kubernetes". If we just have a single container in our primary getting started experience, then your app is still just Kubernetes, but with an added abstraction layer. I know having a module/inline Bicep for Redis and then wiring it up to the Link sucks, but it's what backs up our entire premise until recipes are available

2022-12-09 21:03 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +
(so we should keep the Link but drop the recipe until it's ready)

2022-12-09 22:40 UTC, willtsai commented on docs/content/getting-started/first-application/_index.md
> +Press CTRL+C when you're finished with the website.
I guess my concern is that the user might try to "CTRL+C" from within the browser window, which most certainly will not exit the app. I guess if "terminate" isn't the right word, then "exit" or "close" or "stop" might work?

2022-12-10 00:17 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +Radius workflows run inside Kubernetes. Bring whichever flavor of Kubernetes cluster you prefer.
current version of this sentence based on several people's feedback: 
"Radius runs inside Kubernetes."

2022-12-10 00:20 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +To delete your app, see [rad app delete]({{< ref rad_application_delete >}}).
filed new issue to find a place for those steps in our docs: https://github.com/project-radius/docs/issues/445

2022-12-10 00:23 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +> You may be prompted for your sudo password during installation, as the installer places the `rad` binary under `/usr/local/bin`. If you are unable to sudo you can install the rad CLI to another dir
Filed this new issue to debate where this statement should live. https://github.com/project-radius/docs/issues/446

Until we do make that CLI change, though, IMO we need to leave it here. We got specific usability feedback from people that if we require sudo, they at least want an explicit heads up about it.

2022-12-10 00:39 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +Initialize Radius. For this example, accept all the default options (press ENTER to confirm).
fyi filed https://github.com/project-radius/radius/issues/4852 to think about whether users should even be prompted to select an environment

2022-12-10 00:48 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +Press CTRL+C when you're finished with the website.
compromise sentence: "Press CTRL+C in your terminal when you're finished with the website."

2022-12-10 00:48 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +If you don't have a perferred way to create Kubernetes clusters, you might try using a [Radius codespace](https://aka.ms/ProjectRadius/Codespace), which provides a cluster with Radius pre-installed.
SGTM. Switched back to 
"If you don't have a perferred way to create Kubernetes clusters, you might try using [k3d](https://k3d.io/v5.4.6/), which runs a minimal Kubernetes distribution in Docker."
for now. 

Let's try to get it to using codespaces eventually once we think that path is super foolproof. 
cc @AaronCrawfis

2022-12-10 00:53 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +
removing recipes for now

2022-12-10 00:54 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +The TODO page will now persist your to-do items in Redis. You can verify your data is being persisted by referencing the logs in your terminal window.
removed the Recipes part for now anyways

2022-12-10 01:10 UTC, emily-potyraj commented on docs/content/getting-started/first-application/_index.md
> +What else do you want to build? Visit our Recipe catalog << link to catalog >> to explore all the available building blocks.
fyi, since this section was removed for now (since recipes functionality isn't ready yet), I didn't change this line for now.

2023-01-30 21:35 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +In addition to starting Radius services in your Kubernetes cluster, this initialization command creates a default application `app.bicep` as your starting point. It contains a single container defini
This isn't quite right, the application isn't named `app.bicep`. I'll polish this up separately.

2023-01-30 21:37 UTC, rynowak commented on docs/content/getting-started/first-application/_index.md
> +- Creates a port-forward from localhost to port 3000 inside the container so you can navigate to the app's frontend UI.
Fixed locally, thanks!

2023-01-31 00:42 UTC, AaronCrawfis commented on docs/content/getting-started/first-application/_index.md
> +### Recap and next steps
```suggestion
### Recap and next steps

```

2023-01-31 00:52 UTC, AaronCrawfis submitted a review, later dismissed

2023-01-31 09:07 UTC, rynowak commented
Bypassing CI - I had to fix a typo after @AaronCrawfis approved

2023-01-31 09:07 UTC, merged