Docs on kubernetes metadata extension
radius-project/docs pull request #430
Opened 2022-12-01 00:22 UTC by Reshrahim

Separate PR to include extensions schema changes on container, environment, and application (no application reference page exists today)

2022-12-06 22:26 UTC, AaronCrawfis requested changes

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/_index.md
> +title: "Kubernetes Platform"
```suggestion
title: "Kubernetes platform"
```

Titles are usually sentence cased, and platform isn't a proper noun

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/_index.md
> -Project Radius can be installed and run on top of Kubernetes clusters. This allows you to deploy and manage Radius applications across any cloud or on-premises cluster.
This intro sentence can be kept in this page instead of being removed.

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/cluster.md
> +---
I'd rename this page "supported-clusters" instead of "cluster"

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/cluster.md
> +title: "Kubernetes cluster"
```suggestion
title: "Supported Kubernetes clusters"
```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/cluster.md
> +description: "Learn how to setup Kubernetes cluster"
```suggestion
description: "Learn how to setup Radius on supported Kubernetes clusters"
```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/cluster.md
> +
```suggestion
```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/cluster.md
> +{{< /tabs >}}
This content should be added back to the original page, as it's not specific to the context of supported clusters

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +title: "Kubernetes Metadata"
```suggestion
title: "Set Kubernetes metadata"
```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +description: "Learn how to use Kubernetes concepts of labels and annotations in Radius"
```suggestion
description: "Learn how to configure Kubernetes labels and annotations for generated objects"
```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +weight: 10
```suggestion
weight: 20
```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +## Kubernetes Labels and Annotations
```suggestion
## Kubernetes labels and annotations 

```

Sentence case + headers should have line underneath

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +## Kubernetes Metadata Extension in Radius
```suggestion
## KubernetesMetadata extension

```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +Project Radius enables you to retain or use your own defined tagging scheme for Kubernetes resources using Kubernetes labels and annotations. This enables users to incrementally adopt Radius for micr
```suggestion
Project Radius enables you to retain or use your own defined tagging scheme for Kubernetes resources using Kubernetes labels and annotations. This enables users to incrementally adopt Radius for microservices built in the Kubernetes ecosystem using the Kubernetes native metadata concepts without having to do additional customization.
```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +You can set the labels and annotations on an environment or an application or a container resource using the Kubernetes metadata extension type. All the set labels and annotation will be added to the
```suggestion
You can set labels and annotations on an environment, application, or container using the KubernetesMetadata extension. The Kubernetes objects output from your resources (Deployments, Pods, etc.) will get the defined metadata.
```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +Below is an example of how to set labels and annotations on an environment. The same can be set at the application or container resource
```suggestion
### Example

Here is an example of how to set labels and annotations at the environment layer. All resources within the environment with Kubernetes object outputs will gain this metadata:
```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +```
This should be a {{< rad >}} shortcode

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +In the above example, the labels at the deployment and pod include :
```suggestion
Once deployed, containers deployed in this environment will gain these labels. For example:

```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +```
I think this would be better if framed as a `kubectl describe` command, or a screenshot of Lens.

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +## Cascading Kubernetes Metadata to Various Resources
```suggestion
## Cascading metadata

```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +## Cascading Kubernetes Metadata to Various Resources
This should also be placed before the example

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +Kubernetes metadata are applied to the Radius resources in a cascading order. For eg : You can set the labels and annotations at an environment level and have it cascaded to all of the application an
```suggestion
Kubernetes metadata can be applied at the environment, application, or container layers. Metadata cascades down from the environment to the application to the container. For example, you can set the labels and annotations at an environment level and all containers within the environment will gain these labels and annotations.
```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +You can also override the labels and annotations set at an environment resource either at an application or container level.
```suggestion
### Collision behavior

If metadata is set at both the environment or application layer, in addition to the container layer, the keys will be combined, with conflicts being won at the lowest level. For example, if the 'myapp.myteam.contact' label is set at both the application and container layers, the value set at the container layer will win.
```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +Lets consider an example where the service team wants to override the contact information that was set at the environment level.
```suggestion
### Example

Lets consider an example where the service team wants to override the contact information that was set at the environment level.
```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +```
This should be a {{< rad >}} shortcode

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +```
Similar to above, I think this would be better framed as a kubectl command or Lens screenshot

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +Container/Service has the highest precedence, than applications and environment
```suggestion
```

I'd defer to the section above on collision behavior

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +
```suggestion
```

I don't think this header makes sense.

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +### Reserved Key Prefix
```suggestion
## Reserved keys

```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +### Order of Extensions processing
```suggestion
## Order of extension processing

```

2022-12-06 22:26 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/metadata.md
> +Radius already uses extensions type to add a Dapr sidecar and to manually scale on containers. The order in which they are executed is as follows from first to last:
```suggestion
Other extensions may set Kubernetes metadata. For example, the `daprSidecar` extension sets the `dapr.io/enabled` annotation, as well as some others. This may cause issues in the case of conflicts.

The order in which extensions are executed is as follows, from first to last:
```

2022-12-08 04:38 UTC, lakshmimsft commented on docs/content/operations/platforms/kubernetes/_index.md
> -Project Radius can be installed and run on top of Kubernetes clusters. This allows you to deploy and manage Radius applications across any cloud or on-premises cluster.
updated

2022-12-08 04:43 UTC, lakshmimsft commented on docs/content/operations/platforms/kubernetes/_index.md
> +title: "Kubernetes Platform"
updated

2022-12-08 04:44 UTC, lakshmimsft commented on docs/content/operations/platforms/kubernetes/cluster.md
> +---
updated

2022-12-08 04:44 UTC, lakshmimsft commented on docs/content/operations/platforms/kubernetes/cluster.md
> +description: "Learn how to setup Kubernetes cluster"
updated

2022-12-08 04:44 UTC, lakshmimsft commented on docs/content/operations/platforms/kubernetes/metadata.md
> +
updated

2022-12-08 04:45 UTC, lakshmimsft commented on docs/content/operations/platforms/kubernetes/metadata.md
> +### Reserved Key Prefix
currently updated to ### Reserved keys per discussion with Reshma

2022-12-08 04:46 UTC, lakshmimsft commented on docs/content/operations/platforms/kubernetes/metadata.md
> +### Order of Extensions processing
updated to ### Order of extension processing per discussion with Reshma

2022-12-08 04:48 UTC, lakshmimsft commented on docs/content/operations/platforms/kubernetes/metadata.md
> +Radius already uses extensions type to add a Dapr sidecar and to manually scale on containers. The order in which they are executed is as follows from first to last:
updated

2022-12-08 19:35 UTC, Reshrahim commented on docs/content/operations/platforms/kubernetes/metadata.md
> +Container/Service has the highest precedence, than applications and environment
Updated this content to overriding behavior. There is a useful usecase around that behavior as the example calls out and hence called the title as overriding behavior instead of collision

2022-12-09 17:00 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/snippets/env.bicep
> +          'env.key2': 'envValue2'
Prefixing these with `env` now causes them not to conflict with the lower levels. They were purposefully meant to conflict

2022-12-09 17:01 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/snippets/env.bicep
> +          'env.key2': 'envValue2'
```suggestion
          'key1': 'envValue1'
          'key2': 'envValue2'
```

2022-12-09 17:01 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/snippets/env.bicep
> +          'app.key2': 'appValue2'
```suggestion
          'key1': 'appValue1'
          'key2': 'appValue2'
```

2022-12-09 17:01 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/snippets/env.bicep
> +          'con.key2': 'containerValue2'
```suggestion
          'key2': 'containerValue2'
```

2022-12-09 18:03 UTC, jkotalik commented on docs/content/operations/platforms/kubernetes/_index.md
> +Project Radius can be installed and run on top of Kubernetes clusters. This allows you to deploy and manage Radius applications across any cloud or on-premises cluster.
Is there a link to the kubernetes-install doc from here?

2022-12-12 20:46 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/_index.md
> +Project Radius can be installed and run on top of Kubernetes clusters. This allows you to deploy and manage Radius applications across any cloud or on-premises cluster.
Added

2022-12-12 20:46 UTC, AaronCrawfis approved these changes

2022-12-12 20:50 UTC, merged