Update index.md
radius-project/docs pull request #432
Opened 2022-12-02 18:37 UTC by nithyatsu

2022-12-02 22:42 UTC, AaronCrawfis requested changes

2022-12-02 22:42 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/core-schema/gateway/index.md
> +
```suggestion
```

2022-12-02 22:42 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/core-schema/gateway/index.md
> +| sslPassThrough| y | Determines if the gateway passthrough the TLS traffic to backend server. Currently only `true` is supported. | `true`
```suggestion
| sslPassthrough | n | Configures the gateway to passthrough encrypted SSL traffic to the target container. Disables route-based matching and routing. Defaults to 'false'. | `true`
```

2022-12-02 22:42 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/core-schema/gateway/index.md
> +| sslPassThrough| y | Determines if the gateway passthrough the TLS traffic to backend server. Currently only `true` is supported. | `true`
Doesn't this value default to "false" if omitted?

2022-12-02 22:42 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/core-schema/gateway/index.md
> +
```suggestion
```

2022-12-05 18:25 UTC, nithyatsu commented on docs/content/reference/resource-schema/core-schema/gateway/index.md
> +| sslPassThrough| y | Determines if the gateway passthrough the TLS traffic to backend server. Currently only `true` is supported. | `true`
it defaults to true if omitted...

2022-12-05 20:50 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/core-schema/gateway/index.md
> +| [tls](#TLS) | n | TLS Configurations of the gateway. | [See below](#properties)
This should go under the `Properties` section, as it's nested under properties and not inline with it

2022-12-05 20:52 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/core-schema/gateway/index.md
> +
```suggestion
```

Let's incorporate this into the Description of `sslPassthough`. Added a suggestion, but feel free to update with additional context if needed.

2022-12-13 01:31 UTC, closed without merging