Updates to Kubernetes Metadata docs
radius-project/docs pull request #441
Opened 2022-12-08 22:29 UTC by AaronCrawfis

1. Split Kubernetes installation into second page
2. Simplify snippets and example
3. Switch to Deployment description
4. Make example have more self-describing keys/values

2022-12-08 22:32 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +---
This content wasn't really part of "supported clusters", so I moved it out into a dedicated page on Kubernetes installation

2022-12-08 22:33 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/index.md
> +{{< tabs Environment Application Container >}}
Made these an inline tab group so users can see how the extension looks on each resource type, before diving into the specific behavior.

2022-12-08 22:34 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/index.md
> +## Example
I combined the example into one flow and one file, and made the keys/values a little more self-describing so users don't need to track what values can from which layer

2022-12-09 14:29 UTC, Reshrahim requested changes

2022-12-09 14:29 UTC, Reshrahim commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/index.md
> +{{< tabs Environment Application Container >}}
This is good and the user has examples on how this works against different resources

2022-12-09 14:29 UTC, Reshrahim commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/index.md
> +### Conflicts
I wouldn't want to call this a conflict instead it is an overriding behavior that MBCP wants. Also feel that the example of infra ops setting up certain fields and dev overriding them helped portray the use case better

2022-12-09 14:29 UTC, Reshrahim commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/index.md
> +## Example
This helps remove redundancy but feel that the example I had before portrays a real-time use case that can resonate well with the audience

2022-12-09 14:36 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/index.md
> +## Example
Yeah I was going back and forth myself on this. The tradeoff is definitely between real-world example to show _why_ labels and annotations can be used, vs. teaching _how_ labels and annotations can be used. Perhaps we can find a way to layer in both, to both teach the why and the how in one example. (why I kept the prometheus annotation in the example) With the prior example wasn't sure why a team would want to label the team name and override that. Perhaps we can still leverage the prometheus example to have the developer override a default port or default value

2022-12-09 14:39 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/index.md
> +### Conflicts
Ah gotcha. Yeah let's definitely come up with a way to include a real world example. For the heading totally get the term preference, although conflict resolution is also a common term for features like this. Perhaps:

```suggestion
### Conflicts and overrides
```

2022-12-09 14:39 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/index.md
> +In the case where layers have conflicting keys (_i.e. Application and Contaienr both specify a `myapp.team.name` label_), the last level to process wins out (container). The metadata specified on the
```suggestion
In the case where layers have conflicting keys (_i.e. Application and Contaienr both specify a `myapp.team.name` label_), the last level to process wins out and overrides other values (container). The metadata specified on the container will override the metadata specified on the application or environment.
```

2022-12-09 14:50 UTC, Reshrahim commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/index.md
> +## Example
So a customer told us that their administrator sets up some labels and annotations and the service level engineer overrides them and they also mentioned that this is for troubleshooting/ auditing. So what I did is to translate this use case into an example where the infra ops sets up a support contact/ team name at a generic level for all the apps and services in the environment and then developer or the team owning say the frontend service can override the generic contact info with his team contact at the container level

2022-12-09 15:10 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/index.md
> +## Example
Added back in the real-world example with some simplifications, as well as an explanation

2022-12-09 15:26 UTC, Reshrahim commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/snippets/env.bicep
> +          'team.contact.email': 'ops@example.com'
```suggestion
          'team.contact.email': 'ops'
```
'@' is not supported by Kubernetes labels regex

2022-12-09 15:27 UTC, Reshrahim commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/snippets/env.bicep
> +          'team.contact.email': 'frontend-eng@example.com'
```suggestion
          'team.contact.email': 'frontend-eng'
```

2022-12-09 16:23 UTC, merged