Adding AWS RDS reference app
radius-project/docs pull request #452
Opened 2022-12-19 19:07 UTC by willdavsmith

* Added reference app that uses RDS as a backing container for a Wordpress site

2022-12-19 22:46 UTC, AaronCrawfis requested changes
Please also remove the updates to the docsy submodule

2022-12-19 22:46 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/aws-rds/index.md
> +linkTitle: "Deploying an AWS RDS-backed Wordpress site with Radius"
```suggestion
linkTitle: "WordPress on AWS"
```

linkTitles should be as short as possible to prevent wrapping in the sidebar:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/54363786/208540549-4065cb99-0e3b-4b9f-8e12-fbd242eb978a.png">

2022-12-19 22:46 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/aws-rds/index.md
> +title: "Deploying an AWS RDS-backed Wordpress site with Radius"
```suggestion
title: "Deploy an AWS RDS-backed WordPress site"
```

Spelling, and Radius is redundant

2022-12-19 22:46 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/aws-rds/index.md
> +description: "Learn about how to use Radius to deploy a Wordpress site that uses an AWS RDS database"
```suggestion
description: "Learn about how to use Radius to deploy a WordPress site that uses an AWS RDS database"
```

2022-12-19 22:46 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/aws-rds/index.md
> +* How to model and deploy container apps on AWS
This is somewhat deceiving, as we're just running the containers on EKS & Kubernetes, not directly on AWS. I'd recommend:

```suggestion
* How to model and deploy containers in Radius
```

2022-12-19 22:46 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/aws-rds/index.md
> +* How to model AWS RDS resources in Bicep
```suggestion
* How to model an AWS RDS resource in Bicep
```

2022-12-19 22:46 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/aws-rds/index.md
> +> Note: the `--remote-port` flag is set because the port exposed by the `wordpress` image is `80`.
This breaks your numbering. 

```suggestion
   Note: the `--remote-port` flag is set because the port exposed by the `wordpress` image is `80`.
```

2022-12-19 22:46 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/aws-rds/index.md
> +weight: 500
```suggestion
weight: 600
```

2022-12-19 22:46 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/aws-rds/snippets/app.bicep
> +}
If this is `existing` then I'd add a comment that this is leveraging the eks cluster created as part of the prerequisites. Also I'd use a more generic name, or remove the default parameter value alltogether

2022-12-20 17:31 UTC, willdavsmith commented
Closing in favor of https://github.com/project-radius/docs/pull/453

2022-12-20 17:31 UTC, closed without merging