Adding AWS RDS reference app
radius-project/docs pull request #453
Opened 2022-12-20 17:28 UTC by willdavsmith

* Added AWS RDS reference app

2023-01-03 18:05 UTC, jkotalik commented on docs/content/getting-started/reference-apps/aws-rds/index.md
> +* An RDS instance of a MySQL database, along with a subnet group resource. The setup here ensures that the RDS instance is deployed to the same subnet group and VPC as your EKS cluster, and additiona
Separate RDS and Subnet into different bullets

2023-01-03 18:06 UTC, jkotalik submitted a review, later dismissed

2023-01-03 20:55 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/_index.md
> +{{% /card %}}
These cards now auto-generated (just upmerged this change into edge from v0.16). You can remove this change.

Also please rename `aws-rds.png` to `icon.png`

2023-01-09 22:02 UTC, AaronCrawfis requested changes

2023-01-09 22:02 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/aws-rds/snippets/app.bicep
> +param databaseIdentifier string
For these params could you add an @description block that provides info on how to pick a name? Either a link to an AWS docs page or inline details would be good. Specifically if this needs to be globally unique or account unique, what are the character/naming restrictions, and other considerations

2023-01-09 22:02 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/aws-rds/snippets/app.bicep
> +param databaseIdentifier string
Could we also move them up to the top so all the params are together? Usually the convention is to put all params, especially required params, at the top of a Bicep file

2023-01-23 18:18 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/aws-rds/index.md
> +   Note: the `--remote-port` flag is set because the port exposed by the `wordpress` image is `80`.
Is there an issue with port forwarding to 80?

2023-01-23 18:18 UTC, AaronCrawfis approved these changes

2023-01-26 22:02 UTC, merged