Developer Guide Recipes
radius-project/docs pull request #462
Opened 2023-01-24 18:41 UTC by jasonviviano

## Description
Structure
- Overview
- Recipe Capabilities 
- Example
- Further info

2023-01-27 01:37 UTC, shalabhms commented on docs/content/author-apps/recipes/_index.md
> +Recipes are templates stored in container registries that can be deployed by [Links]({{< ref links-concept >}}) once a Recipe has been registered in a Radius environment. Their purpose is to facilita
I think it would be good to mention about what template is or simplistic say `bicep template` to minimum for now.

2023-01-27 01:39 UTC, shalabhms commented on docs/content/author-apps/recipes/_index.md
> +Recipes are templates stored in container registries that can be deployed by [Links]({{< ref links-concept >}}) once a Recipe has been registered in a Radius environment. Their purpose is to facilita
I think it would be good to mention about what template is or simplistic say `bicep template` to minimum for now.

2023-01-27 01:40 UTC, shalabhms commented on docs/content/author-apps/recipes/_index.md
> +Recipes are templates stored in container registries that can be deployed by [Links]({{< ref links-concept >}}) once a Recipe has been registered in a Radius environment. Their purpose is to facilita
I think re-order the statements. Like it would be to first state what Recipes solving the problem and then how it does.

2023-01-27 01:43 UTC, shalabhms commented on docs/content/author-apps/recipes/_index.md
> +Recipes are templates stored in container registries that can be deployed by [Links]({{< ref links-concept >}}) once a Recipe has been registered in a Radius environment. Their purpose is to facilita
```suggestion
Recipes enables  **separation of concerns** between infrastructure teams and developers by allowing for a **automated infrastructure deployment** that doesn't require developers to pick up infrastructure resource expertise.
Recipe is a bicep template stored in container registry that can be deployed by [Links]({{< ref links-concept >}}) once a Recipe has been registered in a Radius environment. 
```

2023-01-27 01:50 UTC, shalabhms commented on docs/content/author-apps/recipes/_index.md
> +| **Names** | Assign specific names to templates to enable discovery and usability throughout your Radius environment |
This should be just "Name" as we are specific to one Recipe in the context, right?

2023-01-27 01:53 UTC, shalabhms commented on docs/content/author-apps/recipes/_index.md
> +| **Parameters** | Define parameters inside a Recipe for user customizability and pass in values either through your Radius environment or through individual Links.
how about specific mentioning - 'resource configuration parameters`

2023-01-27 01:58 UTC, shalabhms commented on docs/content/author-apps/recipes/_index.md
> +Manage link recipes Link recipes automate the deployment of infrastructure and configuration of links with [**rad recipe**]({{< ref rad_recipe >}}):
redundant phrasing - link recipes..

2023-01-27 01:59 UTC, shalabhms commented on docs/content/author-apps/recipes/_index.md
> +rad recipe list
how about order change to =>  register, list, unregister

2023-01-27 02:00 UTC, shalabhms commented on docs/content/author-apps/recipes/_index.md
> +List link recipes within an environment with [**rad recipe list**]({{< ref rad_recipe_list >}})
"Link" is a feature , so suggested to use as uppercasing `Link` to avoid verb 'link'. Applicable everywhere.

2023-01-27 03:29 UTC, kachawla commented on docs/content/author-apps/recipes/_index.md
> +Recipes are templates stored in container registries that can be deployed by [Links]({{< ref links-concept >}}) once a Recipe has been registered in a Radius environment. Their purpose is to facilita
I think the first few lines need to be focused on what problem is being addressed by recipe in simple words to keep a user's attention without confusing them. As soon as we start bringing in container registry and other implementation details, we can throw a new user off on a different path of why container registry etc.

I'm thinking something like - 
`Recipes simplify how ITOps and developers work together, by making it easier for IT operators to manage and share infrastructure templates in an organization, and developers to easily deploy infrastructure.`

Now we provide a diagram flow of steps needed for how recipes achieve this.

```
------------------------------------------------         ------------------------------------------------
| ITOps team                                   |        | Development team                                                         |
|                                              |        |      
| 1. Create infrastructure templates (recipes) |        | 1. Consume the recipes registered by ops team         |
| 2. Register recipes created in step 1 to     |        |     in a Radius application.
| a Radius environment,                        |        | 2. Deploy the application in the Radius environment |
------------------------------------------------        |     created by the ops team. 
                                                         -----------------------------------------------------|
```

Now we can start diving into specifics of each step on how it works.
After that, I think it will also be valuable to call out things that a developer doesn't need to worry about by using Recipes. For example, developer doesn't need to know where to get infrastructure templates from; developer doesn't need to do any auth setup to deploy the infrastructure.

2023-01-27 18:29 UTC, kachawla commented on docs/content/author-apps/recipes/_index.md
> +{{% /alert %}}
I think putting this above overview might confuse users before they even know how Recipes are used and Links are related to Recipes.

2023-02-06 18:11 UTC, AaronCrawfis requested changes
Really good start! Couple small suggestions on how to tighten it up and prep it for merge, and then follow it up with the admin guide

2023-02-06 18:11 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +description: "Use Recipes for infrastructure deployment in your Radius application"
```suggestion
description: "Automate infrastructure deployment for your resources with Radius resources"
```

Instead of "[Feature] does [Task]", I'd frame this description as "Accomplish [Task] with [Feature]". Helps sell to the user that Recipes helps them with their task, instead of starting with the feature name which is new to them.

2023-02-06 18:11 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +Recipes enable a **separation of concerns** between infrastructure teams and developers by allowing for a **automated infrastructure deployment** that doesn't require developers to have infrastructur
```suggestion
Recipes enable a **separation of concerns** between infrastructure teams and developers by **automating infrastructure deployment**. Developers select the resource they want in their app (_Mongo Database, Redis Cache, Dapr State Store, etc._), and infrastructure teams codify how these resources should be deployed and configured (_lightweight containers, Azure resources, AWS resources, etc._). When a developer deploys their application and its resources, Recipes deploy the backing infrastructure and bind it to the developer's resources.
```

2023-02-06 18:11 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +You can use any Recipes integrated into your Radius environment by  identifying them by name when defining a Link.
```suggestion
### Select the Recipe that meets your needs

Recipes can be created for any environment, from dev to prod. Simply specify `mode: 'recipe'` in your resource, and select the Recipe you want to run:
```

2023-02-06 18:11 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +```
This should be a `{{< rad ... >}}` shortcode, instead of an inline Bicep block. You can checkout another page to see an example.

2023-02-06 18:11 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +List Recipes within an environment with [**rad recipe list**]({{< ref rad_recipe_list >}})
```suggestion
Use [**rad recipe list**]({{< ref rad_recipe_list >}}) to view the Recipes available to you in your environment.
```

2023-02-06 18:11 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +```
Please switch to a `rad` shortcode instead of inline Bicep

2023-02-06 18:11 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +You can customize Recipes by passing resource configuration parameters inside your Link.
```suggestion
Recipes can be customized with parameters, allowing developers to fine-tune infrastructure to meet their specific needs:
```

2023-02-06 18:11 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +- `Applications.Link/redisCaches`
```suggestion
We currently support the following resources for Recipes. Support for additional resources is actively being worked on.

- `Applications.Link/redisCaches`
```

2023-02-06 18:11 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +```
I'd cut this out for now, as there are examples above of how to do each part of a Recipe. We can revisit the example once we build out the quickstart.

2023-02-06 18:11 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +- To learn more about how to create your own custom Recipe visit the administrative Recipe guide.
I'd remove this line for now, and then add it back in as part of the administrator guide. With each individual PR we don't want to go into a "broken" state once it's merged. In this case, if this PR is merged we're now referencing a non-existent page, until the other PR is merged.

I'd recommend:

- Submit this PR that is self-contained and doesn't reference non-existent pages
- Create administrator guide that is based off of this branch, so you can add in the admin guide and the references from the developer guide to the admin guide
- PR both. At first the admin guide PR will include both sets of changes. Once the dev guide PR is merged, then the admin guide will auto-update to only show the admin changes.

2023-02-06 18:24 UTC, rynowak commented on docs/content/author-apps/recipes/_index.md
> +```
Yes, we put Bicep code in external files so we can verify that it's correct as part of the build. Then we know if a sample gets out of date.

2023-02-07 17:41 UTC, AaronCrawfis requested changes

2023-02-07 17:41 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +description: "Automate infrastructure deployment for your resources with Radius resources"
```suggestion
description: "Automate infrastructure deployment for your resources with Radius recipes"
```

2023-02-07 17:41 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +```
```suggestion
```

2023-02-07 17:41 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +- To learn more about how to create your own custom Recipe visit the administrative Recipe guide.
```suggestion
```

2023-02-09 01:16 UTC, kachawla commented on docs/content/author-apps/recipes/_index.md
> +Recipes can be created for any environment, from dev to prod. Simply specify `mode: 'recipe'` in your resource, and select the Recipe you want to run:
```suggestion
Recipes can be used in any environment, from dev to prod. Simply specify `mode: 'recipe'` in your [Link resource](https://docs.radapp.dev/author-apps/links/), and select the Recipe you want to run:
```

2023-02-09 01:16 UTC, kachawla commented on docs/content/author-apps/recipes/_index.md
> +- `Applications.Link/redisCaches`
```suggestion
- `Applications.Link/redisCaches`
- `Applications.Link/mongoDatabases`
- `Applications.Link/daprStateStores`
```

2023-02-09 01:16 UTC, kachawla commented on docs/content/author-apps/recipes/_index.md
> +Follow the administrative Recipe guide for information on how to add a Recipe to your Radius environment.
Link to `administrative Recipe guide` will be helpful here

2023-02-09 15:36 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +Recipes can be created for any environment, from dev to prod. Simply specify `mode: 'recipe'` in your resource, and select the Recipe you want to run:
One thing we should be careful with is limiting Recipes to Links. Although that is 100% the implementation today, we want to prepare ourselves for when Recipes support any resource. It'll be hard to reframe this later once we change our implementation and need to change everyone's understanding later.

```suggestion
Recipes can be used in any environment, from dev to prod. Simply specify `mode: 'recipe'` in your Recipe-supported resource, and select the Recipe you want to run:
```

2023-02-09 15:39 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +- `Applications.Link/redisCaches`
We should probably have a table describing if there's value-backed support and resource-backed support (or are they one in the same?). 

Not sure exactly how we tell that to customers and explain the nuance, but I'm concerned we may get into a situation where someone sees the Redis Recipe experience in the new first app page, and want to recreate that for Mongo, only to hit a wall

2023-02-09 15:39 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +Follow the administrative Recipe guide for information on how to add a Recipe to your Radius environment.
We won't be able to do that until the admin guide PR, since that's a follow-up PR.

We should probably just remove this example section for now, and revisit it through a Recipes quickstart.

2023-02-10 17:44 UTC, kachawla commented on docs/content/author-apps/recipes/_index.md
> +      parameters: {
Will it help if we also add a note on how a developer can get list of parameters that can be set for a recipe?

2023-02-10 18:05 UTC, kachawla commented on docs/content/author-apps/recipes/_index.md
> +- `Applications.Link/redisCaches`
@AaronCrawfis With the way everything is implemented, I think all recipe types (value backed, resource backed) should be supported on all link types that we added support for so far. @mishrapratikshya is doing a quick test to validate that this is true.

2023-02-10 18:41 UTC, AaronCrawfis requested changes

2023-02-10 18:41 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +Recipes can be used in any environment, from dev to prod. Simply specify `mode: 'recipe'` in your [Link resource](https://docs.radapp.dev/author-apps/links/), and select the Recipe you want to run:
Please use a {{< ref links >}} shortcode instead of directly linking to the page

2023-02-10 18:41 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +
```suggestion
```

2023-02-10 18:41 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +
```suggestion
```

2023-02-10 18:41 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +Visit [**rad recipe**]({{< ref rad_recipe_show >}}).
```suggestion
You can use [**rad recipe show**]({{< ref rad_recipe_show >}}) to view the parameters available to you in a Recipe.
```

2023-02-10 18:41 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +
```suggestion
Recipes currently support the following resources. Support for additional resources is actively being worked on.
```
Avoid using first person (I/We/Us)

2023-02-10 18:41 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +|-----|
```suggestion
| Supported resources | 
|---------------------|
```

2023-02-10 18:41 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +
```suggestion
```

2023-02-10 18:44 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +{{< rad file="snippets/recipe-link-example.bicep" embed=true marker="//BASIC" >}}
Please make sure to commit and push these files, they're currently missing

2023-02-10 18:49 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/snippets/recipe-link-example.bicep
> +//BASIC
There will be a couple Bicep validation errors that will need to be addressed:

- There needs to be an `import radius as rad` statement at the top
- You'll need to add `environment` and `application` parameters to the file, and add them to the Links.

2023-02-10 18:50 UTC, AaronCrawfis commented on docs/content/author-apps/recipes/_index.md
> +      parameters: {
Note has been added

2023-02-10 19:00 UTC, AaronCrawfis approved these changes

2023-02-10 19:11 UTC, merged