Admin Guide for Recipes
radius-project/docs pull request #464
Opened 2023-01-26 19:17 UTC by jasonviviano

## Description

- Overview
- Features
          - Input context parameter
          - Output values contract
          - Output resource contract
- Example
          - How to author a recipe template
          - How to publish a recipe template
          - How to register a recipe

2023-01-27 05:13 UTC, shalabhms commented on docs/content/operations/recipes-creation/_index.md
> +Recipes are templates stored in container registries that can be deployed by [Links]({{< ref links-concept >}}) once a Recipe has been registered in a Radius environment. They simplify operational wo
Same comment as I mentioned on the Developer Guide PR. It would be good to state what problem Recipes is solving and then state how it it solving. 

So a reordering might help here

```suggestion
Recipes enables  **separation of concerns** between infrastructure teams and developers by allowing for a **automated infrastructure deployment** that doesn't require developers to pick up infrastructure resource expertise.
Recipe is a bicep template stored in container registry that can be deployed by [Links]({{< ref links-concept >}}) once a Recipe has been registered in a Radius environment. 
```

2023-01-27 05:14 UTC, shalabhms commented on docs/content/operations/recipes-creation/_index.md
> +| `context` | The `context` parameter is an object that contains information about the Link calling the recipe and is passed to a template automatically by Radius. The following properties can be fou
Please add the description of these properties inline here - `resource`, `application`, `environment`, `runtime`

2023-01-27 05:15 UTC, shalabhms commented on docs/content/operations/recipes-creation/_index.md
> +title: "Radius recipes"
```suggestion
title: "Radius Recipes"
```

2023-02-06 18:58 UTC, AaronCrawfis requested changes
Great start! Added some notes on how to streamline this

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +linkTitle: "Recipes"
```suggestion
linkTitle: "Author Recipes"
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +title: "Radius Recipes"
```suggestion
title: "Author Custom Radius Recipes"
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +description: "Learn how to automate infrastructure deployment with Recipes"
```suggestion
description: "Learn how to author custom Recipe templates to automate infrastructure deployment"
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +
```suggestion
```

This info is covered in the Recipes dev page, I'd remove this and instead add a reference below (see below comment)

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +Recipes enables  **separation of concerns** between infrastructure teams and developers by allowing for a **automated infrastructure deployment** that doesn't require developers to pick up infrastruc
```suggestion
Recipes enable a **separation of concerns** between infrastructure teams and developers by **automating infrastructure deployment**.

Learn more in the Recipes overview page:

{{< button page="recipes" text="Recipes overview" >}}
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +## Recipe features
```suggestion
## Author a custom Recipe

This page will describe how to author and publish a custom Recipe template, letting you define how infrastructure should be deployed and configured within your environment.
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +
```suggestion
### Select an Infrastructure as Code language

Today, Recipes only support the Bicep IaC language. Your custom Recipe template will begin with a new Bicep file, which will contain all of the resources you want to automatically deploy for each resource that runs the Recipe.

```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +
I think a full reference table would be better at the bottom of the page, instead of a smaller top-level table here.

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> + You can leverage the `context` parameter which contains information about the Link deploying the recipe and is passed automatically by the Radius server in order to have multiple Links relying on a
```suggestion
### Ensure your resource names are **unique** and **repeatable**
Recipe will be called by multiple many resources and need to be generalized templates. The resources inside of a Recipe cannot interfere or overwrite each other. To make sure you don't accidently overwrite or corrupt your infrastructure, you will want to make sure **each resource in your Recipe contains unique names**.
Additionally, every time an application is deployed, Recipes are re-evaluated and deployed. Because IaC languages like Bicep are idempotent, if there are no changes to the template then nothing is re-deployed or re-configured. To make sure Recipes can be re-run, **each resource needs a repeatable name that is the same every time it is deployed**.
To make naming easy, a `context` parameter is automatically injected into your template.
It contains information about the backing resource which you can use to generate unique and repeatable names:
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +You can create any [parameter type supported by Bicep](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/parameters) for your Recipe to allow for developers or custom Radius enviro
```suggestion
### Add parameters for Recipe customization (optional)

You can optionally choose to add parameters to your Recipe to allow developers or operators to specify additional configuration. Parameters can be set both when a Recipe is added to an environment by an operator, or by a developer when the Recipe is called.

You can create any [parameter type supported by Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/parameters):
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +param <parameter-name> <parameter-data-type> = <default-value>`
```suggestion
@description('A custom parameter that can be set by a developer or operator')
param myParam string = 'default value'` 
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +Any property utilized in [Link schemas]({{< ref link-schema >}}) can be added to a `value` object as a property.
```suggestion
### Output the target infrastructure

Once you've defined your backing infrastructure, you'll need to output it from your IaC template so it can be "wired-up" to the resource that called the Recipe.

Recipes allow you to either specify `values` or `resource`:

{{< tabs Values Resource >}}

{{% codetab %}}
When you output a `values` object, all of the individual properties will be directly mapped to the resource calling the Recipe. This allows you that most control over the resource being created within the application.

Simply define an object that matches the schema of the resource calling the Recipe. For example, for an `Application.Link/redisCaches` resource, a Recipe would output:
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +#### Example
```suggestion
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +  password: ''
Should these be nested under a `secrets` property?

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +#### Example
```suggestion
Some Radius resources, such as Links, may support automatically mapping infrastructure via a resource ID. Refer to the backing resource's documentation to know what infrastructure is supported.

For supported infrastructure and resources, you can simply output the resource ID as a string, and the properties will automatically configured. For example, `Applications.Link/redisCaches` supports auto-mapping of `Microsoft.Cache/redis`:

```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +output resource string = memoryDBCluster.id
```suggestion
resource azureCache `Microsoft.Cache/redis@2022-06-01' = {...}

output resource string = azureCache.id
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +If you specify both `values` and `resource` objects, any configuration inside the `values` object will override what is set by the `resource` object.
```suggestion
If you specify both `values` and `resource`, `resource` will be used first and then `values` will override.
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +
```suggestion
```

I'd remove this as it's now redundant

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +### Store your Bicep file in a OCI compliant registry
```suggestion
### Store your template in a Bicep registry
```

I think for now let's use the exsiting "Bicep registry" term that's already well-understood for Bicep authors and in the Bicep documentation.

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +Example:
```suggestion
Recipes leverage [Bicep registries](https://learn.microsoft.com/azure/azure-resource-manager/bicep/private-module-registry) for template storage. Once you've authored a Recipe, you can publish it to your preferred OCI-compliant registry.

For private registries, make sure the cloud provider configured in your Radius environment has pull permissions for your container registry.

You can use the `az bicep publish` to easily publish your Recipe Bicep template:
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +az bicep publish --file <YOUR-FILENAME>.bicep --target
```suggestion
az bicep publish --file myrecipe.bicep --target myregistry.azurecr.io/recipes/myrecipe:v1
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +```
```suggestion
```bash
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +### Register your Recipe with your Radius environment
```suggestion
### Register your Recipe with your environment
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +
```suggestion

Now that your Recipe Bicep template has been stored within your Bicep registry, you can add it your Radius environment to be used by developers. This allows you to mix-and-match templates for each of your environments such as dev, canary, and prod.

Recipes can be added via the rad CLI, or via an environment Bicep definition:

```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +```
```suggestion
```bash
```

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +
Also please add a Bicep environment template example here too.

2023-02-06 18:58 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +- Visit the Recipe developer guide for more information.
```suggestion

- Visit the Recipe developer guide for more information.
```

This should also be a `{{< ref >}} to this page (make sure this PR is based off of the dev PR branch, or wait until that is merged and then pull in the latest changes from `edge`)

2023-02-07 17:46 UTC, AaronCrawfis requested changes

2023-02-07 17:46 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +
```suggestion
```

2023-02-07 17:46 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +### Ensure your resource names are **unique** and **repeatable**
```suggestion
### Ensure your resource names are **unique** and **repeatable**

```

2023-02-07 17:46 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +Recipe will be called by multiple many resources and need to be generalized templates. The resources inside of a Recipe cannot interfere or overwrite each other. To make sure you don't accidently ove
```suggestion
Recipes need to be generalized templates, as multiple resources can run each Recipe. The resources inside of a Recipe cannot interfere or overwrite each other. To make sure you don't accidentally overwrite or corrupt your infrastructure, you will want to make sure **each resource in your Recipe contains unique names**.

```

2023-02-07 17:46 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +Additionally, every time an application is deployed, Recipes are re-evaluated and deployed. Because IaC languages like Bicep are idempotent, if there are no changes to the template then nothing is re
```suggestion
Additionally, every time an application is deployed, Recipes are re-evaluated and re-deployed. Because IaC languages like Bicep are idempotent, if there are no changes to the template, then nothing is changed. To make sure Recipes can be re-run, **each resource needs a repeatable name that is the same every time it is deployed**.

```

2023-02-07 17:46 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +It contains information about the backing resource which you can use to generate unique and repeatable names:
```suggestion
To make naming easy, a `context` parameter is automatically injected into your template. It contains information about the backing resource which you can use to generate unique and repeatable names.

For example, you can use `context.resource.id` to generate a unique and repeatable name:

{{< rad file="snippets/=template.bicep" embed="true" marker="//NAME" >}}
```

2023-02-07 17:46 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +
```suggestion
```

2023-02-09 01:47 UTC, kachawla commented on docs/content/operations/recipes-creation/_index.md
> +  password: ''
Yes. And host and port nested under `values`. https://github.com/project-radius/radius/blob/main/test/functional/corerp/resources/testdata/recipes/test-recipes/redis-recipe-value-backed.bicep#L61-L73

2023-02-10 23:49 UTC, AaronCrawfis approved these changes

2023-02-10 23:49 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +
```suggestion
```

Be careful not to have repeated blank lines

2023-02-10 23:49 UTC, AaronCrawfis commented on docs/content/operations/recipes-creation/_index.md
> +
```suggestion

```

2023-02-10 23:52 UTC, merged