Quickstart for Recipes
radius-project/docs pull request #493
Opened 2023-02-27 22:18 UTC by jasonviviano

Thank you for helping make the Radius documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.radapp.dev/contributing/docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description
Quickstart for Recipes.

### Outline

- Intro blurb
- Prerequisite
    - Kubernetes
- Overview about Recipes
    - Developer guide link
- Application overview
- Initialize Kubernetes env
    - Note about AWS/Azure
- Dev Recipes Explained
- Consume Recipes in your application
    - 3 tabs
        - Local
        - Azure
        - AWS
- Next Steps.
    - Point to Admin Recipe Doc

## Dependencies

- https://github.com/project-radius/recipes/pull/4

## Issue reference
https://dev.azure.com/azure-octo/Incubations/_workitems/edit/5853

2023-02-27 23:07 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +   - **Environment name** - The name of the environment to create. You can specify any name with lowercase letters, such as `mycoolenv`.
env called `azure`

2023-02-27 23:09 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +   - **Namespace** - When an application is deployed, this is the namespace where your containers and other Kubernetes resources will be run. By default, this will be in the `default` namespace.
Remove namespace mention

2023-04-03 18:09 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +linkTitle: "Deploy Recipes in your Radius Application"
```suggestion
linkTitle: "Recipes"
```

linkTitles should be 4 words or less, preferably 1-2

2023-04-03 18:13 UTC, willtsai commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +- [Supported Kubernetes clusters]({{< ref kubernetes >}})
```suggestion
- A supported [Kubernetes cluster]({{< ref kubernetes >}})
```

2023-04-03 18:21 UTC, willtsai commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +[Recipes]({{< ref recipes >}}) enable a separation of concerns between infrastructure teams and developers by automating infrastructure deployment.
"enable a separation of concerns between infrastructure teams and developers" -- can the same thing be said about Radius in general? Is there something more specific about Recipes that allow you to take the features of Radius one step further? If so, would be good to introduce that here. Also, talk about why Recipes are beneficial and how they can help infra teams and developers.

2023-04-03 18:21 UTC, willtsai commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +Recipes are a collection of infrastructure resources that can be deployed as part of a Radius application. Currently Recipes can be written in [Bicep](https://docs.microsoft.com/en-us/azure/azure-res
suggest taking away the "How?" section and header

```suggestion
Specifically, Recipes are a collection of infrastructure resources that can be deployed as part of a Radius application. Currently Recipes can be written in [Bicep](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview) and can be stored in [Azure Container Registries](https://azure.microsoft.com/en-us/products/container-registry/).
```

2023-04-03 18:21 UTC, willtsai commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +The Radius community provides Recipes for running commonly used application dependencies, including Redis.
Recommend elaborating on the community aspect of Recipes if that's an important strategy for Recipes (i.e. continuing growth of Recipes provided by contributors)

2023-04-03 18:21 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +-  The **frontend** [container]({{< ref container >}}) resource which contains:
Do we want to explain the container defn here? This will anyways be covered in a separate guide for containers under the developer section which we can cross link here.

I think explaining the todoapp outside of Radius terms and then mapping it to Radius components would be good here

2023-04-03 18:26 UTC, AaronCrawfis requested changes

2023-04-03 18:26 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +description: "Learn how to use community 'dev' Recipes and your custom made Recipes in a Radius Environment"
```suggestion
description: "Learn how to use Radius Recipes within your application"
```

2023-04-03 18:26 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +
```suggestion
```

Duplicate blank lines

2023-04-03 18:26 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +- [Supported Kubernetes clusters]({{< ref kubernetes >}})
```suggestion
- [Supported Kubernetes cluster]({{< ref kubernetes >}})
```

A prerequisite needs to tell the user what they need or what to do. "Supported clusters" (plural), should be "Supported cluster" (singular) because the user only needs one

2023-04-03 18:26 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +Recipes are a collection of infrastructure resources that can be deployed as part of a Radius application. Currently Recipes can be written in [Bicep](https://docs.microsoft.com/en-us/azure/azure-res
This is too specific for the quickstart, and should instead be in the Recipes overview page.

Instead, I'd suggest making it a bit more succinct

```suggestion
[Recipes]({{< ref recipes >}}) enable a separation of concerns between infrastructure teams and developers by automating infrastructure deployment. Developers define _what_ they need (_Redis, Mongo, etc._), and operators define _how_ it will be deployed (_Azure/AWS/Kubernetes infrastructure_).
```

2023-04-03 18:26 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +- The **db** [Link resource]({{< ref link-schema >}}) provides an abstraction for an infrastructure resource through its API, allowing the backing resource type to be swapped out without changing the
I think this is too much reading. Perhaps a shorter version will work:

```suggestion
## Application overview

This application is a simple to-do list which stores and visualized to-do items. It consists of a frontend [container]({{< ref container >}}) and a backend [Redis Link]({{< ref links >}}):

<img src="recipe-quickstart-diagram.png" alt="Screenshot of the todoapp with Kubernetes, Azure and AWS Redis Cache options" style="width:100%" >
```

2023-04-03 18:26 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +## Step 1: Initialize a Radius environment
Headers should have a blank line under them

```suggestion
## Step 1: Initialize a Radius environment

```

2023-04-03 18:26 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +
Too much reading. Perhaps we can shorten this a little bit:

(note that because my suggestion has ``` in it you'll need to open the raw markdown and manually copy and paste)
```
1. Begin in a new directory for your application:
   ```bash
   mkdir recipes
   cd recipes
   ```
2. Initialize a new environment with [`dev` Recipes]({{< ref "recipes#use-community-dev-recipes" >}}):
   ```bash
   rad init --dev
   ```
```

2023-04-03 18:26 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +### Community `dev` Recipes
```suggestion
### `dev` Recipes
```

We don't yet have a community aspect to these, so let's hold off on the term "community" for now

2023-04-03 18:26 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +|`redis-azure`| provisions a new Azure cache for Redis |
Too much reading on this, let's see if we can shorten it a bit:

(Note my suggestion has ``` so you'll need to open the raw markdown)

```
[`dev` Recipes]({{< ref "recipes#use-community-dev-recipes" >}}) allow you to quickly get up and running with infrastructure for your [Links]({{< ref links >}}). You can view this with [`rad recipe list`]({{< ref rad_recipe_list >}}):

```bash
rad recipe list 
```

You should see a table of available Recipes (_with more to be added soon_):
```
NAME              TYPE                              TEMPLATE
redis-aws         Applications.Link/redisCaches     radius.azurecr.io/recipes/rediscaches/aws:1.0
redis-kubernetes  Applications.Link/redisCaches     radius.azurecr.io/recipes/rediscaches/kubernetes:1.0
redis-azure       Applications.Link/redisCaches     radius.azurecr.io/recipes/rediscaches/azure:1.0
```
```

2023-04-03 19:40 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +{{< button text="Learn more about Recipes" page="recipes" newtab="true" >}}
This looks out of place. Can we merge this to overview section calling it out explicitly like "Learn more about recipes here"

2023-04-10 17:51 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +slug: "recipes"
```suggestion
slug: "recipes"
categories: "Quickstart"
tags: ["Azure", "AWS", "Recipes"]
```

2023-04-10 18:20 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/recipe-quickstart-diagram.png
We should remove the gateway and HTTP route from this image, as it's not in the Bicep file

2023-04-10 18:29 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/snippets/app.bicep
> +      name: ''
This needs to be updated

2023-04-10 19:50 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +tags: ["Azure", "AWS", "Recipes"]
```suggestion
```

2023-04-11 01:11 UTC, kachawla commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +```
`mongo-azure` dev recipe is registered as well currently.. do we plan to remove that or just not including it in this doc?

2023-04-11 01:11 UTC, kachawla commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +Update the recipe name to `redis-azure` to use the Redis Cache container.
Should this be "to use the Redis cache on Azure"?

2023-04-11 16:39 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +Update the recipe name to `redis-aws` to use the Redis Cache container.
```suggestion
Update the recipe name to `redis-aws` to use the Amazon MemoryDB for Redis.
```

2023-04-12 15:49 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +```
Yeah, for this doc, since it's leveraging Redis Cache it should be ok to filter the list right now. Especially since if we stuck to keeping it always up to date it would mean constantly including every new Recipe added to `dev` Recipes regardless of if they matter in the current quick-start.

2023-05-12 18:27 UTC, AaronCrawfis requested changes

2023-05-12 18:27 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +<img src="recipe-quickstart-diagram.png" alt="Screenshot of the todoapp with Kubernetes, Azure and AWS Redis Cache options" style="width:100%" >
100% is too big for a diagram like this. Let's use something like 1000px instead.

2023-05-12 18:27 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +
```suggestion
```

This line is somewhat repetitive compared to the next line. We can probably just remove it.

2023-05-12 18:27 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +2. Initialize a new environment with [`dev` Recipes]({{< ref "recipes#use-community-dev-recipes" >}}):
As written this makes it seem like `--dev` is a Dev Recipes flag, which it isn't (it's a dev flag for a dev environment). Maybe something like this will work:

```suggestion
2. Initialize a new dev environment, which is pre-loaded with lightweight dev Recipes:
```

2023-05-12 18:27 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +[`dev` Recipes]({{< ref "recipes#use-community-dev-recipes" >}}) allow you to quickly get up and running with infrastructure for your [Links]({{< ref links >}}). You can view this with [`rad recipe l
```suggestion
   [`dev` Recipes]({{< ref "recipes#use-community-dev-recipes" >}}) allow you to quickly get up and running with infrastructure for your [Links]({{< ref links >}})._
   3. Use [`rad recipe list`]({{< ref rad_recipe_list >}}) to view the Recipes in your dev environment:
```

2023-05-12 18:27 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +```
This should all be indented to match the 3rd bullet above

2023-05-12 18:27 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +   ```bash
I'd remove the bash part here so it renders with a light background instead of dark

2023-05-12 18:27 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +3. Port-forward the container to your machine with `rad resource expose`:
I'd add a step where you run `kubectl get pods -n default-webapp` to show that the Recipe has deployed Kubernetes pods for db

2023-05-12 18:27 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +```
This should be indented

2023-05-12 18:27 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +4. Visit `localhost:3000` in your browser.
I'd add some more instructions here on what the user is expected to do (interact with the site?)

2023-05-12 18:27 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +Update the recipe name to `redis-aws` to use the Amazon MemoryDB for Redis and pass the eksClusterName as parameter to the recipe.
I'd add a note that the adding the EKS name is a temporary workaround

2023-05-12 18:27 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +   Completed            demo-memorydb-cluster AWS.MemoryDB/Cluster
Is this displayed to the user? I don't think Recipe information is forwarded.

2023-05-15 16:21 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +You should see a table of available Recipes (_with more to be added soon_):
Ryan N clarified that dev recipes are meant only for non-cloud resources. Any cloud resource recipe that exists in the dev recipe path needs to be moved. 

So users will need to register these cloud recipes in their environment as an additional step until the time we bring the recipe packs feature

2023-05-30 18:00 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +   Completed            demo-memorydb-cluster AWS.MemoryDB/Cluster
yes updated this

2023-05-30 18:46 UTC, Reshrahim commented
@AaronCrawfis / @jasonviviano - Memory DB gets deployed via AWS recipe but the application is not able to connect to it. I believe this required a change in webapp - Is this the change https://github.com/project-radius/samples/pull/170 ?

2023-06-02 18:10 UTC, jasonviviano commented
@Reshrahim @AaronCrawfis Let me know if this format is still alright now that AWS references have had to be removed for now.

Context: https://github.com/project-radius/samples/pull/233#issuecomment-1574106108

2023-06-02 19:03 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +<img src="recipe-quickstart-diagram.png" alt="Screenshot of the todoapp with Kubernetes, Azure and AWS Redis Cache options" style="width:1000px" >
This still references AWS redis cache. We can either remove it or mark it as coming soon

2023-06-02 19:49 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +<img src="recipe-quickstart-diagram.png" alt="Screenshot of the todoapp with Kubernetes, Azure and AWS Redis Cache options" style="width:1000px" >
I think we'll be ok if we leave it in. This image is meant to be illustrative anyways. Good catch though!

2023-06-02 20:03 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +<img src="recipe-quickstart-diagram.png" alt="Screenshot of the todoapp with Kubernetes, Azure and AWS Redis Cache options" style="width:1000px" >
Added a small note!

2023-06-05 17:25 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +
```suggestion
> **Note**: An AWS walkthrough will be added to Step 3 in the future however Recipes do support AWS resources.

```

2023-06-05 18:17 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +tags : ["Recipe"]
Can we make this plural for consistency? We can also add the tag "Azure" as this covers Azure recipes

2023-06-05 18:19 UTC, AaronCrawfis requested changes

2023-06-05 18:19 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +tags : ["Recipe"]
```suggestion
tags : ["recipes"]
```

2023-06-05 18:19 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/snippets/app.bicep
> +param environment string
Could you include a description here please?

2023-06-05 18:19 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/snippets/app.bicep
> +param location string = 'global'
Also a description here

2023-06-05 18:19 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/snippets/app.bicep
> +      name: 'redis-kubernetes'
This should use the default recipe

2023-06-05 22:13 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +> **Note**: An AWS walkthrough will be added to Step 3 in the future however Recipes do support AWS resources.
```suggestion
```

2023-06-05 22:17 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +   [`dev` Recipes]({{< ref "recipes#use-community-dev-recipes" >}}) allow you to quickly get up and running with infrastructure for your [Links]({{< ref links >}})._
```suggestion
   [`dev` Recipes]({{< ref "recipes#use-community-dev-recipes" >}}) provide a set of Recipes that allow you to quickly get up and running with lightweight containerized infrastructure.
```

2023-06-05 22:18 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +   ```
```suggestion
   You should see a table of available Recipes (_with more to be added soon_):
   ```bash
   NAME          TYPE                              TEMPLATE
   default       Applications.Link/redisCaches     radius.azurecr.io/recipes/dev/rediscaches:v0.21
   ```
```

2023-06-05 22:20 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +
```suggestion
3. List your Kubernetes Pods to see the infrastructure container deployed by the Recipe:

```

2023-06-05 22:20 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +
```suggestion
 <img src="todoapp.png" width="1000" alt="screenshot of the todo application">
```

2023-06-05 22:21 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> + <img src="todoapp.png" width="1000" alt="screenshot of the todo application">
```suggestion

 <img src="todoapp.png" width="1000" alt="screenshot of the todo application">
 
```

2023-06-05 22:23 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +> *This step needs an Azure subscription to deploy the application which would incur some costs. Add the required cloud provider (Azure) to your environment in order to deploy an Azure recipe*
```suggestion
> *This step requires an Azure subscription to deploy cloud resources, which will incur costs. You will need to add the [Azure cloud provider]({{< ref providers >}}) to your environment in order to deploy Azure resources and leverage Azure Recipes.*
```

2023-06-05 22:26 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +{{< button text="Learn more about configuring Cloud providers" page="providers#configure-a-cloud-provider" newtab="true" >}}
```suggestion
{{< button text="Add a cloud provider" page="providers#configure-a-cloud-provider" newtab="true" >}}
```

2023-06-05 22:30 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +   rad recipe register azure -e default  --template-path radius.azurecr.io/recipes/rediscaches/azure:1.0 --link-type Applications.Link/redisCaches --template-kind bicep
```suggestion
   rad recipe register azure --environment default --template-kind bicep --template-path radius.azurecr.io/recipes/azure/rediscaches:0.21 --link-type Applications.Link/redisCaches 
```

2023-06-05 22:32 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +   Update the Recipe name given to the resource to `azure` to use the Redis cache on Azure .
Let's make this it's own step as "Update your resource to use the azure Recipe"

2023-06-05 22:34 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +   This will deploy the application into your environment and launch the container resource for the frontend website. This operation may take some time, since it is deploying a Redis Cache resource t
```suggestion
   This operation may take some time, as the 'azure' Recipe is deploying an Azure Cache for Redis resource into your Azure subscription. It will then update your 'db' resource to use the Azure Redis. Once completed you should see the following resources deployed at the end of `rad deploy`:
```

2023-06-05 22:36 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +1. If you're done with testing, you can use the rad CLI to [delete an environment]({{< ref rad_env_delete.md >}}) to delete all Radius resources running on your cluster.
We should check to see if deleting an environment also deletes an application.

2023-06-05 22:37 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +2. Azure resources are not deleted when deleting a Radius environment, so to prevent additional charges, make sure to delete all resources created in this quickstart. For Azure, this includes the Azu
```suggestion
2. Azure resources are not currently deleted when deleting a Radius environment. To prevent additional charges, make sure to delete the Azure Cache for Redis using the [Azure portal](https://portal.azure.com).
```

2023-06-05 22:37 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +* How to author your own Recipes
```suggestion
```

2023-06-05 22:38 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/snippets/app.bicep
> +    }
The user doesn't need to type 'default', they can leverage the default functionality

2023-06-05 22:39 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +   rad init --dev
Here we should tell the user not to scaffold an application

2023-06-05 22:41 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +{{< rad file="snippets/app.bicep" embed=true >}}
We should add some callouts to the user, such as "Here you can see a frontend container talking to a Redis database, where the Redis database is using the default Recipe. This could also either be in the Bicep itself as a comment

2023-06-05 23:04 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +
Have to add a snippet for switching the resource to `azure` recipe

2023-06-05 23:06 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +1. If you're done with testing, you can use the rad CLI to [delete an environment]({{< ref rad_env_delete.md >}}) to delete all Radius resources running on your cluster.
Confirmed on codespace with first-app

2023-06-06 17:17 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +   ```
```suggestion
   ```bash
```

2023-06-06 17:18 UTC, jasonviviano commented
@AaronCrawfis @Reshrahim Updated with all feedback incorporated let me know if anything else is missing!

2023-06-06 17:52 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> + <img src="todoapp.png" width="1000" alt="screenshot of the todo application">
```suggestion
 <img src="todoapp.png" width="500" alt="screenshot of the todo application">
```
The image looks elongated.

2023-06-06 17:54 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +{{< rad file="snippets/app.bicep" embed=true >}}
```suggestion
   {{< rad file="snippets/app.bicep" embed=true >}}
```

2023-06-06 17:56 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +You've now deployed your application to your Kubernetes cluster!
nit: indent this line so that its part of step 2

2023-06-06 17:56 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +1. Port-forward the container to your machine with [`rad resource expose`]({{< ref rad_resource_expose>}})
```suggestion
4. Port-forward the container to your machine with [`rad resource expose`]({{< ref rad_resource_expose>}})
```

2023-06-06 17:57 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-recipe/index.md
> +1. Visit [localhost:3000](http://localhost:3000) in your browser. You should see a page like
```suggestion
5. Visit [localhost:3000](http://localhost:3000) in your browser. You should see a page like
```

2023-06-06 17:58 UTC, Reshrahim commented
> @AaronCrawfis @Reshrahim Updated with all feedback incorporated let me know if anything else is missing!

Looks good to me except for some lines need to be indented

2023-06-06 17:59 UTC, jasonviviano commented
> > @AaronCrawfis @Reshrahim Updated with all feedback incorporated let me know if anything else is missing!
> 
> Looks good to me except for some lines need to be indented

Updated!

2023-06-06 19:34 UTC, Reshrahim submitted a review, later dismissed

2023-06-07 00:41 UTC, AaronCrawfis submitted a review, later dismissed

2023-06-07 00:42 UTC, AaronCrawfis approved these changes

2023-06-07 00:44 UTC, merged