Moving s3 as a basic quickstart to model AWS resources
radius-project/docs pull request #509
Opened 2023-03-21 21:40 UTC by Reshrahim

Thank you for helping make the Radius documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.radapp.dev/contributing/docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Based on the feedback from the team, making the S3 reference app as the basic AWS quickstart where we teach users how to model a simple s3 bucket and then have a separate quickstart to dig deep into leveraging recipes for AWS resources.

This PR would cover only changes to s3 quickstart and will separately update the existing PR on  adding recipes support to quickstart via radius-project/radius#499 

## Issue reference

2023-03-24 19:24 UTC, AaronCrawfis requested changes

2023-03-24 19:24 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-recipes/_index.md
> +tags: "memorydb"
Would it be possible to decouple the categories and tags from this PR on the AWS quickstart? Love the new taxonomies work, but want to make sure we can finalize on that experience separately than this page.

2023-03-24 19:24 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-recipes/_index.md
@jasonviviano how do you see this quickstart working with your existing recipes quickstart that's in progress?

I'd love to keep this as simple as possible, where we have one recipes quickstart instead of separate quickstarts for AWS Recipes, Azure Recipes, and Dev Recipes.

2023-03-24 19:24 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +description: "Learn about how to model AWS S3 resources in Bicep and Radius"
```suggestion
title: "Quickstart: Use AWS resources in your app"
linkTitle: "Use AWS resources"
description: "Learn about how to add AWS resources to your application and deploy them with Radius"
```

For titles it's best to use verbs and actions that align with what the developer is trying to do. "Model and deploy" is more talking about how they're doing it instead of what they're doing. Maybe something like "Quickstart: Use AWS resources in your app" would be better.

2023-03-24 19:24 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +This reference app will show you:
```suggestion
This quickstart will show you:
```

2023-03-24 19:24 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +## Prerequisites
```suggestion
## Prerequisites

```

Headers should have a trailing new line

2023-03-24 19:24 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +## Step 1: Create an EKS Cluster
```suggestion
## Step 1: Create an EKS Cluster

```

2023-03-24 19:24 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +   {{% /alert %}}
Since we're using `rad init`, which lists your kubeconfig contexts, we can omit this step

```suggestion
```

2023-03-24 19:24 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    rad deploy ./app.bicep -p aws_access_key_id=<AWS_ACCESS_KEY_ID> -p aws_secret_access_key=<AWS_SECRET_ACCESS_KEY> -p aws_region=<REGION> -p bucket=<BUCKET_NAME>
Can we see if there's a way to make this quickstart not need to pass in all the connection information as parameters?

- The bucket name should be injected in the Bicep file
- The region should also ideally be injected through the Bicep file (although not sure if it's part of the properties)
- Access Key is tricky because ideally we would have an new IAM role and key in the Bicep file as well. We don't want to use the same control-plane key as the data-plane key in the container. Can we add an IAM role in Bicep?

2023-03-24 19:45 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +description: "Learn about how to model AWS S3 resources in Bicep and Radius"
I am reverting back to original AWS quickstart title. Also some of our quickstarts just have the topic as title like environmnent variables, dapr and do not have have verbs or actions with them. If we want to have verbs and actions in titles, we need to make sure they are consistently followed.

2023-03-24 19:52 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-recipes/_index.md
For AWS, we need to give some additional instructions on provisioning the cluster in availability zones where memory db is supported and make sure the eks cluster information is passed in while deploying

Would definitely be great if we can have one app.bicep leverage Azure/AWS/K8s recipes deployable across Azure/AWS/K8s

2023-03-24 19:55 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-recipes/_index.md
> +tags: "memorydb"
removed

2023-03-24 20:07 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    rad deploy ./app.bicep -p aws_access_key_id=<AWS_ACCESS_KEY_ID> -p aws_secret_access_key=<AWS_SECRET_ACCESS_KEY> -p aws_region=<REGION> -p bucket=<BUCKET_NAME>
Bucket names can be directly injected. We do not support direct connections with AWS resources yet and I believe we need the IAM roles for service accounts support to do direct connections with AWS resources. 

Maybe we can pass these via a parameter file and leave it to the user to use the same control plane key or use a different one?

2023-03-27 19:42 UTC, kachawla commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    rad deploy ./app.bicep -p aws_access_key_id=<AWS_ACCESS_KEY_ID> -p aws_secret_access_key=<AWS_SECRET_ACCESS_KEY> -p aws_region=<REGION> -p bucket=<BUCKET_NAME>
@Reshrahim is there a reason to not support direct connections to AWS resources with the expectation that RBAC setup needs to be done by the operator until we automate that?

2023-03-27 19:44 UTC, kachawla commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    rad deploy ./app.bicep -p aws_access_key_id=<AWS_ACCESS_KEY_ID> -p aws_secret_access_key=<AWS_SECRET_ACCESS_KEY> -p aws_region=<REGION> -p bucket=<BUCKET_NAME>
@AaronCrawfis for region, if we are passing resource ARN for the id that the container is connecting to, then that would be enough to parse the region from it.

2023-03-27 19:47 UTC, kachawla commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    rad deploy ./app.bicep -p aws_access_key_id=<AWS_ACCESS_KEY_ID> -p aws_secret_access_key=<AWS_SECRET_ACCESS_KEY> -p aws_region=<REGION> -p bucket=<BUCKET_NAME>
> @Reshrahim is there a reason to not support direct connections to AWS resources with the expectation that RBAC setup needs to be done by the operator until we automate that?

Re-reading your comment above, "Bucket names can be directly injected", I think you meant we can inject bucket name through direct connections. If that's what you meant, then ignore my comment :), but we should consider updating this quickstart in that case.

2023-03-27 20:01 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    rad deploy ./app.bicep -p aws_access_key_id=<AWS_ACCESS_KEY_ID> -p aws_secret_access_key=<AWS_SECRET_ACCESS_KEY> -p aws_region=<REGION> -p bucket=<BUCKET_NAME>
> @Reshrahim is there a reason to not support direct connections to AWS resources with the expectation that RBAC setup needs to be done by the operator until we automate that?

This was a hard cut for public release due to cost and priority. We need to integrate AWS IRSA(IAM roles for service accounts) support to automatically manage Iam roles and permissions between the user app and the AWS services

2023-03-27 20:09 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    rad deploy ./app.bicep -p aws_access_key_id=<AWS_ACCESS_KEY_ID> -p aws_secret_access_key=<AWS_SECRET_ACCESS_KEY> -p aws_region=<REGION> -p bucket=<BUCKET_NAME>
> > @Reshrahim is there a reason to not support direct connections to AWS resources with the expectation that RBAC setup needs to be done by the operator until we automate that?
> 
> Re-reading your comment above, "Bucket names can be directly injected", I think you meant we can inject bucket name through direct connections. If that's what you meant, then ignore my comment :), but we should consider updating this quickstart in that case.

Sorry for the confusion. I meant bucket name can directly be keyed in the file as 'mys3bucket' instead of bringing it as a parameter.

2023-03-27 20:38 UTC, kachawla commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    rad deploy ./app.bicep -p aws_access_key_id=<AWS_ACCESS_KEY_ID> -p aws_secret_access_key=<AWS_SECRET_ACCESS_KEY> -p aws_region=<REGION> -p bucket=<BUCKET_NAME>
> > @Reshrahim is there a reason to not support direct connections to AWS resources with the expectation that RBAC setup needs to be done by the operator until we automate that?
> 
> This was a hard cut for public release due to cost and priority. We need to integrate AWS IRSA(IAM roles for service accounts) support to automatically manage Iam roles and permissions between the user app and the AWS services

I was suggesting supporting direct connections without Radius automating RBAC/IAM service roles. One of the main benefits of direct connections is the ability to automate injecting container env vars at container deploy time. For non secret properties that are accessible through resource id (bucket name, region), we can support them through direct connections without automating IAM setup.

2023-03-28 13:29 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    rad deploy ./app.bicep -p aws_access_key_id=<AWS_ACCESS_KEY_ID> -p aws_secret_access_key=<AWS_SECRET_ACCESS_KEY> -p aws_region=<REGION> -p bucket=<BUCKET_NAME>
> > > @Reshrahim is there a reason to not support direct connections to AWS resources with the expectation that RBAC setup needs to be done by the operator until we automate that?
> > 
> > 
> > This was a hard cut for public release due to cost and priority. We need to integrate AWS IRSA(IAM roles for service accounts) support to automatically manage Iam roles and permissions between the user app and the AWS services
> 
> I was suggesting supporting direct connections without Radius automating RBAC/IAM service roles. One of the main benefits of direct connections is the ability to automate injecting container env vars at container deploy time. For non secret properties that are accessible through resource id (bucket name, region), we can support them through direct connections without automating IAM setup.

Interesting! In the current [app.bicep](https://github.com/project-radius/docs/blob/reshma/awsquickstarts/docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/app.bicep) we directly inject the access key, secret, bucket name and region as env variables in the container. Is there a cleaner/better way to do this?

2023-03-30 18:45 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-aws-recipes/_index.md
It would be a good idea to also have a small section for a diagram and a quick blurb about the application before jumping into the steps here, to make users not familiar with Bicep understand what's happening better even if it's a basic app.

2023-03-31 19:24 UTC, AaronCrawfis requested changes

2023-03-31 19:24 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-recipes/_index.md
>  Create an EKS cluster by using the `eksctl` CLI. This command will create a cluster in the `us-west-2` region, as well as a VPC and the Subnets, Security Groups, and IAM Roles required for the cluste
Can we find a way to make the region configurable instead of hardcoding `us-west-2`?

2023-03-31 19:24 UTC, AaronCrawfis commented on docs/config.toml
> +
Let's tackle tags as part of your other PR, and have this PR focus on the AWS quickstart

2023-03-31 19:24 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +```
Since we're using S3, is an EKS cluster a hard requirement? Would any other cluster work?

2023-03-31 19:24 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    rad deploy ./app.bicep -p aws_access_key_id=<AWS_ACCESS_KEY_ID> -p aws_secret_access_key=<AWS_SECRET_ACCESS_KEY> -p aws_region=<REGION>
We should try to avoid mixing IAM roles for control plane and data plane operations.

Would it be possible to add an IAM role in app.bicep and use the new Access Key ID and Secret Access Key?

2023-04-03 17:29 UTC, Reshrahim commented on docs/config.toml
> +
updated

2023-04-03 17:31 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-recipes/_index.md
Hid the aws recipes quickstart and will merge the content over to #493

2023-04-03 17:45 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +```
I think there might be ways to make it work but also thinking if we shd pursue the path as users will mostly prefer to have compute and data in the same provider to avoid ingress and egress costs

2023-04-03 17:50 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    rad deploy ./app.bicep -p aws_access_key_id=<AWS_ACCESS_KEY_ID> -p aws_secret_access_key=<AWS_SECRET_ACCESS_KEY> -p aws_region=<REGION>
Need to explore this a bit. While we have the option to model an IAM role in bicep today, need to validate this to see if there is a way we could have separate keys for the control plane and data plane operations

2023-04-03 21:27 UTC, rynowak commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    rad deploy ./app.bicep -p aws_access_key_id=<AWS_ACCESS_KEY_ID> -p aws_secret_access_key=<AWS_SECRET_ACCESS_KEY> -p aws_region=<REGION>
This could be possible if IRSA relies on annotations and labels, but I don't think it does. We'd have to create a service account for the pods and register it with IRSA. Right now we don't expose a way to configure the service account for the pods we create.

This could be unblocked by the K8s incremental adoption work, but then there's a heavy amount of IRSA tech that would leak into the app until we actually build the features.

2023-04-28 23:02 UTC, vinayada1 commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/app.bicep
>      AccessControl: 'PublicRead'
This should be 'Private' now

2023-04-28 23:04 UTC, vinayada1 commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/app.bicep
>      AccessControl: 'PublicRead'
Why are we hardcoding the bucket name?

2023-05-01 01:06 UTC, ytimocin commented on docs/config.toml
> +category = "categories"
nit: there is an extra space right after "categories" and not sure if that is intentional.

2023-05-01 16:18 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/app.bicep
>      AccessControl: 'PublicRead'
Hardcoded it so that the user need not pass in this as a parameter. May be can assign a default bucket name to the parameter and use that

2023-05-01 16:28 UTC, Reshrahim commented on docs/config.toml
> +category = "categories"
this got rebased with edge

2023-05-01 18:25 UTC, willtsai requested changes

2023-05-01 18:25 UTC, willtsai commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +* How to use a sample application to interact with AWS S3
```suggestion
- How to model an AWS S3 resource in Bicep
- How to use a sample application to interact with AWS S3
```
extremely tiny nitpick to use consistent style of MD bullet points

2023-05-01 18:25 UTC, willtsai commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    - [Create an IAM AWS access key](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html) and copy the AWS Access Key ID and the AWS Secret Access Key to a secure locatio
incomplete sentence ("...you can...")

2023-05-01 18:25 UTC, willtsai commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    - Configure your CLI with [`aws configure`](https://docs.aws.amazon.com/cli/latest/reference/configure/index.html), specifying your configuration values
does the user need to set all of the configuration values or just a required subset will suffice? might be good to clarify this.

2023-05-01 18:25 UTC, willtsai commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +
recommend adding a screenshot of the CLI interactive UI with all the required "answers" shown.

2023-05-01 18:25 UTC, willtsai commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    Make sure to create a different[IAM AWS access key](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html) for data plane operations. These are used so the container we
```suggestion
    Make sure to create a different [IAM AWS access key](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html) for data plane operations. These are used so the container we are deploying can connect to AWS. 
```

2023-05-01 18:25 UTC, willtsai commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +1. If you're done with testing, you can use the rad CLI to [delete an environment]({{< ref rad_env_delete.md >}}) to delete all Radius resources running on the EKS Cluster.
```suggestion
1. When you're done with testing, you can use the rad CLI to [delete an environment]({{< ref rad_env_delete.md >}}) to delete all Radius resources running on the EKS Cluster.
```

2023-05-01 18:25 UTC, willtsai commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +2. Cleanup AWS Resources - AWS resources are not deleted when deleting a Radius environment, so to prevent additional charges, make sure to delete all resources created in this reference app. You can
```suggestion
2. Cleanup AWS Resources - AWS resources are not deleted when deleting a Radius environment, so make sure to delete all resources created in this reference app to prevent additional charges. You can delete these resources in the AWS Console or via the AWS CLI. Instructions to delete an AWS S3 Bucket are available [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/delete-bucket.html).
```

2023-05-01 18:30 UTC, willtsai commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +
recommend adding a screenshot to show what the application frontend should look like

2023-05-08 17:39 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    - Configure your CLI with [`aws configure`](https://docs.aws.amazon.com/cli/latest/reference/configure/index.html), specifying your configuration values
user is required to set all of the values (4 values) and the linked doc calls those out

2023-05-08 19:54 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +
added

2023-05-08 19:58 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +
Feel like the screenshot wouldn't make much value here as the credentials will all be masked and it will be reading the same as above

2023-05-08 19:58 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    - [Create an IAM AWS access key](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html) and copy the AWS Access Key ID and the AWS Secret Access Key to a secure locatio
updated

2023-05-08 20:09 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-recipes/_index.md
>  Create an EKS cluster by using the `eksctl` CLI. This command will create a cluster in the `us-west-2` region, as well as a VPC and the Subnets, Security Groups, and IAM Roles required for the cluste
I am not sure if we can make this configurable as we don't have an option for the user to get this info in Bicep. 
@willdavsmith / @vinayada1 - Thoughts?

2023-05-08 20:20 UTC, vinayada1 submitted a review, later dismissed

2023-05-08 21:16 UTC, rynowak commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    Make sure to create a different [IAM AWS access key](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html) for data plane operations. These are used so the container w
This should be it's own step IMO. We should also explain why two users are needed.

2023-05-08 21:17 UTC, rynowak commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +
Alternatively the user can use `rad run`. That will automatically open a port-forward.

2023-05-08 21:18 UTC, rynowak commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/app.bicep
> +param bucket string ='mys3bucketrun'
will this work? Do bucket names need to be globally unique?

2023-05-08 23:24 UTC, willtsai requested changes

2023-05-08 23:24 UTC, willtsai commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/s3appdiagram.png
looks like there's an erroneous spellcheck warning in this screenshot

2023-05-09 14:49 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/app.bicep
> +param bucket string ='mys3bucketrun'
yes they need to be globally unique across accounts and across regions. Let me update it to an unique string

2023-05-09 15:07 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +
Tried rad run and the app doesn't load. Could see the log stream but couldn't load the app at localhost:5234

frontend-f759c894b-k4t74 › frontend
frontend-f759c894b-k4t74 frontend info: Microsoft.Hosting.Lifetime[14]
frontend-f759c894b-k4t74 frontend       Now listening on: http://[::]:5234
frontend-f759c894b-k4t74 frontend info: Microsoft.Hosting.Lifetime[0]
frontend-f759c894b-k4t74 frontend       Application started. Press Ctrl+C to shut down.
frontend-f759c894b-k4t74 frontend info: Microsoft.Hosting.Lifetime[0]
frontend-f759c894b-k4t74 frontend       Hosting environment: Production
frontend-f759c894b-k4t74 frontend info: Microsoft.Hosting.Lifetime[0]
frontend-f759c894b-k4t74 frontend       Content root path: /app/

2023-05-09 15:17 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/s3appdiagram.png
updates. thanks for catching it

2023-05-09 15:31 UTC, AaronCrawfis requested changes
Left some comments.

I'm also thinking we're missing an opportunity to showcase the Bicep tooling features for AWS resources. One of the goals of this quickstart should be to show why doing AWS resources in Bicep is worth a user's time, and using ctrl + space to show all available properties would be a big win. For S3 the `AccessControl` property would be a perfect place to show the intellisense on what values are available.

2023-05-09 15:31 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +   <img src="./s3appdiagram.png" alt="Screenshot of the sample application to interact with s3 bucket " width=400>
This isn't rendering correctly:
<img width="768" alt="image" src="https://github.com/project-radius/docs/assets/54363786/60516901-e5df-452d-9705-80bae9e04050">

You may need an extra new line or an explicit `<br>` element

2023-05-09 15:31 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/app.bicep
> +param application string
This will only work if the application has already been created, or if you explicitly tell the user to create the application in their directory as part of `rad init`. Is that the intended flow?

2023-05-09 15:31 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/app.bicep
> +param aws_region string = 'us-east-2'
Why do we have a default if the instructions tell the user to explicitly pass in a region parameter?

2023-05-09 15:31 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +    Make sure to create a different [IAM AWS access key](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html) for data plane operations. These are used so the container w
Agreed. Does the user also need to setup the correct IAM role? Or is the default to create an IAM key with full access?

2023-05-09 15:31 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/app.bicep
> +  alias: bucket
We should have some information on what `alias` is, and why it's useful

2023-05-09 15:31 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/app.bicep
> +param application string
These should have descriptions as well

2023-05-09 15:43 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +{{< rad file="snippets/app.bicep" embed=true >}}
I think too may things are in this step. I think a better option would be to split this out into 1 step on the AWS resource, talking about the intellisense experience, and then another step on the Radius resource(s) that connect to the AWS resource. Currently the AWS pieces get lost in a giant paste block.

2023-05-09 16:13 UTC, Reshrahim commented
> Left some comments.
> 
> I'm also thinking we're missing an opportunity to showcase the Bicep tooling features for AWS resources. One of the goals of this quickstart should be to show why doing AWS resources in Bicep is worth a user's time, and using ctrl + space to show all available properties would be a big win. For S3 the `AccessControl` property would be a perfect place to show the intellisense on what values are available.

Our intellisense today shows only the required properties. We do not show anything on the values. User has to go to the docs to understand this. Can separate modeling of S3 from app.bicep to to show bicep support for AWS resources and link up the AWS resource library for more info

2023-05-09 16:50 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +{{< rad file="snippets/app.bicep" embed=true >}}
Separated the steps now to talk about s3 bucket separately from the app. Can you take a look ?

2023-05-09 16:50 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/app.bicep
> +param application string
updated

2023-05-09 16:51 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/app.bicep
> +param aws_region string = 'us-east-2'
removed. thanks for catching it

2023-05-09 16:51 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +   <img src="./s3appdiagram.png" alt="Screenshot of the sample application to interact with s3 bucket " width=400>
updated

2023-05-09 17:45 UTC, willtsai submitted a review, later dismissed

2023-05-15 18:11 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +{{< rad file="snippets/app.bicep" embed=true >}}
In this example the user would be duplicating the s3 bucket. Instead we could have the users append the file with the Radius resources

2023-05-15 18:13 UTC, willtsai commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +## Step 4: Deploy the application
```suggestion
## Step 6: Deploy the application
```

2023-05-15 18:18 UTC, willtsai commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +## Step 5: Cleanup
```suggestion
## Step 7: Cleanup
```

2023-05-15 19:19 UTC, AaronCrawfis requested changes

2023-05-15 19:19 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/s3.bicep
> +@description('The name of your S3 bucket.The AWS S3 Bucket name must follow the [following naming conventions](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html).')
Bicep descriptions don't follow markdown conventions

```suggestion
@description('The name of your S3 bucket.The AWS S3 Bucket name must follow the naming conventions described at https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html')
```

2023-05-15 19:19 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/s3.bicep
> +param bucket string ='mys3bucket-${uniqueString(resourceGroup().id)}'
```suggestion
param bucket string ='mys3bucket-${uniqueString(resourceGroup().id)}'

```

2023-05-15 19:19 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> + Make sure to create a different [IAM AWS access key](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html) for the container to connect to the S3 bucket. It is recommende
On this are we creating a new IAM AWS access key for the same user? And does that mean both keys have the same level of access (essentially owner?)

If so, we should create a new IAM user that is separate from the human user, which can only write to S3, and have a key for that. Having two keys for the same user negates the point of having separate keys.

If not I might be missing where we say that this access key can only write to S3 buckets

2023-05-15 19:34 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-recipes/_index.md
>  Create an EKS cluster by using the `eksctl` CLI. This command will create a cluster in the `us-west-2` region, as well as a VPC and the Subnets, Security Groups, and IAM Roles required for the cluste
Is this the region from when you run `aws configure`? Perhaps this string can say "... in your default region from your AWS configuration".

2023-06-05 17:21 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> + Make sure to create a different [IAM AWS access key](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html) for the container to connect to the S3 bucket. It is recommende
Discussed this and agreed to use the same IAM key for both the control plane and data plane operations with an alert that this is not a recommended approach

2023-06-06 22:33 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-recipes/_index.md
>  Create an EKS cluster by using the `eksctl` CLI. This command will create a cluster in the `us-west-2` region, as well as a VPC and the Subnets, Security Groups, and IAM Roles required for the cluste
updated

2023-06-27 22:35 UTC, AaronCrawfis requested changes

2023-06-27 22:35 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +```bicep
This should be a rad shortcode

2023-06-27 22:35 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +@description('Radius environment')
Could you make this more descriptive and match how we do environment description in the first app experience?

2023-06-27 22:35 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +```bicep
Also it might be better to have the user just do one copy & paste instead of two separate copy and pastes, especially because there's no actions between them.

2023-06-27 22:35 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/app.bicep
>  resource s3 'AWS.S3/Bucket@default' = {
```suggestion

resource s3 'AWS.S3/Bucket@default' = {
```

2023-06-27 22:35 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/app.bicep
>  resource app 'Applications.Core/applications@2022-03-15-privatepreview' = {
```suggestion

resource app 'Applications.Core/applications@2022-03-15-privatepreview' = {
```

2023-06-27 22:35 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/snippets/s3.bicep
> +resource s3 'AWS.S3/Bucket@default' = {
```suggestion

resource s3 'AWS.S3/Bucket@default' = {
```

2023-06-27 22:35 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws/index.md
> +hide_summary: true
What are these for?

2023-06-28 13:01 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +```bicep
made it a separate file with markers

2023-06-28 13:04 UTC, Reshrahim commented on docs/content/getting-started/quickstarts/quickstart-aws/index.md
> +hide_summary: true
Good catch. I hid the existing AWS quickstart instead of removing it to reference back. Can delete the folder altogether, now that the new quickstart is ready.

2023-06-28 14:13 UTC, Reshrahim commented on docs/content/author-apps/platform-resources/aws/index.md
> -categories: "Concept"
cleaning up only AWS-related docs with an overview category for content to show up under further reading. Will do separate PR to cleanup others

2023-06-30 19:54 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws-s3/_index.md
> +
@Reshrahim could you open a bug with steps to reproduce please?

2023-06-30 19:55 UTC, AaronCrawfis submitted a review, later dismissed

2023-07-03 18:20 UTC, willtsai approved these changes

2023-07-03 18:20 UTC, merged