Add taxonomy tags to organize content
radius-project/docs pull request #516
Opened 2023-03-28 20:43 UTC by Reshrahim

Thank you for helping make the Radius documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.radapp.dev/contributing/docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description
This PR leverages the concept of taxonomies in Hugo. Created a shortcode to categorize content on a page by tags taxonomy. Testing the shortcode with quickstart

![image](https://user-images.githubusercontent.com/61033581/229573443-e23e32f0-44a8-4938-b650-13a642afc3c1.png)

Separate PRs to follow on adding categories to organize by type of content (quickstarts vs how-tos) and also by both categories and tags 

This will be useful with reference apps/samples as there is an influx of the content 

## Issue reference
#515

2023-03-30 16:58 UTC, AaronCrawfis requested changes
This is AWESOME!!

On the term "categories", I'm wondering if we can make sure we're using the right term.

A category to me is one of:
  - Quickstart
  - How-To Guide
  - Concept

where the category describes what kind of document this is.

I think "Topic" might be better, which describes what topic is within the document.

2023-03-30 16:58 UTC, AaronCrawfis commented on docs/content/author-apps/dapr-resource/dapr-buildingblocks.png
Are all the Dapr directories meant to be renamed?

2023-03-30 16:58 UTC, AaronCrawfis commented on docs/layouts/shortcodes/categorize.html
> +      {{end}}
There's a missing `</div>` and the end here

2023-03-30 16:58 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/_index.md
> +{{<categorize>}}
```suggestion
{{< categorize >}}
```

Also this is AWESOME!!

2023-03-30 17:25 UTC, Reshrahim commented
> This is AWESOME!!
> 
> On the term "categories", I'm wondering if we can make sure we're using the right term.
> 
> A category to me is one of:
> 
> * Quickstart
> * How-To Guide
> * Concept
> 
> where the category describes what kind of document this is.
> 
> I think "Topic" might be better, which describes what topic is within the document.

Yeah, I just experimented with categories but we can definitely adjust them to our needs. Categories and Tags are available as default taxonomies and we can also add custom taxonomy

So category can represent the type of content (concept/how-to/quickstart guide) whereas tags/topics can represent the keywords related to content 

We can also make the shortcode organize content either by category or tags based on the level eg: Getting started section / Quickstarts

2023-03-30 18:04 UTC, jasonviviano commented
Hey, do we have to edit anything in the `config.toml`? I was looking at the documentation website and for a customized `series` tag we'd have to add in something like below, not sure if this requires something similar?

```
taxonomies:
  category: categories
  series: series
  tag: tags
 ```

Currently the `config.toml` only has:

```
# Taxonomies
[taxonomies]
category = "categories"
```

So not sure if tags would also work correctly right now.

2023-03-30 20:21 UTC, Reshrahim commented
> Hey, do we have to edit anything in the `config.toml`? I was looking at the documentation website and for a customized `series` tag we'd have to add in something like below, not sure if this requires something similar?
> 
> ```
> taxonomies:
>   category: categories
>   series: series
>   tag: tags
> ```
> 
> Currently the `config.toml` only has:
> 
> ```
> # Taxonomies
> [taxonomies]
> category = "categories"
> ```
> 
> So not sure if tags would also work correctly right now.

so defaults are categories and tags which would work without this config in `config.toml` too. If you want to add custom taxonomy terms like series/topic we need to put it in `config.toml` like above

2023-03-30 20:25 UTC, Reshrahim commented on docs/content/author-apps/dapr-resource/dapr-buildingblocks.png
yup it wasn't allowing the category to be `dapr` as the content folder under developer guides also reads the same as the URL generation for the site conflicts

2023-03-30 20:30 UTC, Reshrahim commented on docs/content/author-apps/dapr-resource/dapr-buildingblocks.png
but the URL generated has `categories/dapr` which shouldn't conflict. let me check further

2023-03-31 15:02 UTC, Reshrahim commented on docs/layouts/shortcodes/categorize.html
> +      {{end}}
updated

2023-04-03 16:17 UTC, Reshrahim commented on docs/content/author-apps/dapr-resource/dapr-buildingblocks.png
Looks like this is a known limitation from Hugo. Content section cannot be the same as the taxonomy. So we either use a different name for dapr content section or we use different taxonomy for dapr related pages

2023-04-03 16:26 UTC, AaronCrawfis commented on docs/layouts/shortcodes/categorize.html
> +      {{end}}
I'm still seeing a missing a </div> that doesn't close the card-pane div from line 1

2023-04-03 16:28 UTC, Reshrahim commented on docs/layouts/shortcodes/categorize.html
> +      {{end}}
pushing the change now! missed to commit

2023-04-03 16:40 UTC, AaronCrawfis requested changes
Looking good!

Added some casing notes and a note on the Dapr resources section.

Could you also add a file to `content/tags` with frontmatter? The tags page currently doesn't have a sidebar on the left side of the page, so a user could get lost. Adding a page with just frontmatter will cause the sidebar to be loaded.

2023-04-03 16:40 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-dapr/_index.md
> +tags : ["dapr"]
Could we use proper casing for brands?

```suggestion
tags : ["Dapr"]
```

2023-04-03 16:40 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-container-wi/index.md
> +tags: ["azure","containers"]
```suggestion
tags: ["Azure","containers"]
```

2023-04-03 16:40 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-aws/index.md
> +tags: ["aws"]
```suggestion
tags: ["AWS"]
```

2023-04-03 16:40 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/index.md
> +tags: ["azure","containers"]
```suggestion
tags: ["Azure","containers"]
```

2023-04-03 16:40 UTC, AaronCrawfis commented on docs/content/author-apps/dapr-resource/dapr-buildingblocks.png
Could we rename this section to `dapr-resources` and add a slug for `dapr` please?

2023-04-03 16:54 UTC, Reshrahim commented
> Looking good!
> 
> Added some casing notes and a note on the Dapr resources section.
> 
> Could you also add a file to `content/tags` with frontmatter? The tags page currently doesn't have a sidebar on the left side of the page, so a user could get lost. Adding a page with just frontmatter will cause the sidebar to be loaded.

something like this ?
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/61033581/229576525-27778027-a939-4e69-a1f7-ab00d150114f.png">

2023-04-03 18:40 UTC, AaronCrawfis commented on docs/content/_index.md
> +      <a href="{{< ref dapr-resources >}}"><img src="dapr-logo.svg" alt="Dapr logo" style="width:40%"></a>
could we do a search and make sure there aren't any other {{< ref dapr >}} we need to change?

2023-04-03 19:15 UTC, Reshrahim commented on docs/content/_index.md
> +      <a href="{{< ref dapr-resources >}}"><img src="dapr-logo.svg" alt="Dapr logo" style="width:40%"></a>
yes did a quick pass..no other dapr references

2023-04-06 18:37 UTC, AaronCrawfis commented on docs/content/author-apps/dapr-resources/index.md
Could we try adding a slug for `dapr` on this page?

2023-04-06 18:56 UTC, AaronCrawfis approved these changes

2023-04-06 18:56 UTC, merged