add doc for rad install kubernetes --set option
radius-project/docs pull request #521
Opened 2023-03-29 20:50 UTC by nithyatsu

Thank you for helping make the Radius documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.radapp.dev/contributing/docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Add set command documentation to capture valid values which can be set. 

## Issue reference

Partially addresses https://github.com/project-radius/docs/issues/318

2023-03-29 23:20 UTC, AaronCrawfis commented
@nithyatsu could you update the title to be more specific on what's being added/updated? 

("Adding docs on --set command")

2023-03-30 00:14 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +| `global.prometheus.path` | `"/metrics"` | Metrics endpoint
@nithyatsu is there a reason this value needs "" quotes around the value, unlike the others?

2023-03-30 00:15 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +### Available Helm configuration
@nithyatsu is there a "source of truth" for these properties in our Helm chart? I'm wondering if we can automate the generation of this table somehow (outside the scope of this PR)

2023-03-30 01:01 UTC, nithyatsu commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +### Available Helm configuration
great idea! basically its constructed from radius/deploy/Chart/values.yaml file in our radius repo. The commented out sections are valid possibilities in the file too.

2023-03-30 01:12 UTC, nithyatsu commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +| `global.prometheus.path` | `"/metrics"` | Metrics endpoint
Just happens to be a string, enclosed in quotes in the values.yaml too..

2023-03-30 01:31 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +### Available Helm configuration
Awesome! Made a note in #318 and we can tackle later. Thanks!

2023-03-30 01:31 UTC, AaronCrawfis approved these changes

2023-03-30 01:32 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +| `ucp.tag`                  |  radius.azurecr.io/appcore-rp | set this variable to tag of radius rp image                                      |
@nithyatsu can you update these default values so they're not all appcore-rp? Thanks!

2023-03-30 01:32 UTC, AaronCrawfis requested changes
Added a note on default values

2023-03-30 16:27 UTC, youngbupark reviewed
Thanks for the update

2023-03-30 16:27 UTC, youngbupark commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +`rad install kubernetes --set global.zipkin.url=http://jaeger-collector.radius-monitoring.svc.cluster.local:9411/api/v2/spans,radius-rp.publicEndpointOverride=localhost:8081`
```suggestion
`rad install kubernetes --set global.zipkin.url=http://jaeger-collector.radius-monitoring.svc.cluster.local:9411/api/v2/spans,rp.publicEndpointOverride=localhost:8081`
```

2023-03-30 16:27 UTC, youngbupark commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +|`radius-rp.publicEndpointOverride` | ""      |set this variable to the public endpoint of the Kubernetes cluster |
```suggestion
| `rp.image`          |  radius.azurecr.io/appcore-rp | set this variable to location of radius rp image                                |
| `rp.tag`            |  radius.azurecr.io/appcore-rp | set this variable to tag of radius rp image                                      |  
|`rp.publicEndpointOverride` | ""      |set this variable to the public endpoint of the Kubernetes cluster |
```

2023-03-30 16:27 UTC, youngbupark commented on docs/content/operations/platforms/kubernetes/supported-clusters.md
> +rad install kubernetes --set radius-rp.publicEndpointOverride=localhost:8081
```suggestion
rad install kubernetes --set rp.publicEndpointOverride=localhost:8081
```

2023-03-30 16:27 UTC, youngbupark commented on docs/content/operations/platforms/kubernetes/supported-clusters.md
> +rad install kubernetes --set radius-rp.publicEndpointOverride=localhost:8080
```suggestion
rad install kubernetes --set rp.publicEndpointOverride=localhost:8080
```

2023-03-30 16:36 UTC, nithyatsu commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +| `ucp.tag`                  |  radius.azurecr.io/appcore-rp | set this variable to tag of radius rp image                                      |
updated.

2023-03-30 16:37 UTC, nithyatsu commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +`rad install kubernetes --set global.zipkin.url=http://jaeger-collector.radius-monitoring.svc.cluster.local:9411/api/v2/spans,radius-rp.publicEndpointOverride=localhost:8081`
updated all radius-rp to rp.

2023-03-30 16:45 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +| `ucp.tag`                  |  radius.azurecr.io/appcore-rp | set this variable to tag of radius rp image                                      |
Still seeing `appcore-rp`:
<img width="227" alt="image" src="https://user-images.githubusercontent.com/54363786/228907186-89fde8f2-9dc4-4eb0-9afa-11700e754895.png">

2023-03-30 17:13 UTC, nithyatsu commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +| `ucp.tag`                  |  radius.azurecr.io/appcore-rp | set this variable to tag of radius rp image                                      |
hmm, we havent updated the image name, since that would need update to image ( basically make the image with new name and the changes associated with that.. ) should we do that too?

2023-03-30 17:17 UTC, jasonviviano commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +`rad install kubernetes --set global.zipkin.url=http://jaeger-collector.radius-monitoring.svc.cluster.local:9411/api/v2/spans,rp.publicEndpointOverride=localhost:8081`
Hey for aesthetic purposes I think changing this to the below would work better since it's a long command and even on my Mac laptop screen the sentence turns to about 3-4 lines, can't use the suggestion option with the code block :(

For example: 
```
rad install Kubernetes --set global.zipkin.url=http://jaeger-collector.radius-monitoring.svc.cluster.local:9411/api/v2/spans,rp.publicEndpointOverride=localhost:8081
```

2023-03-30 17:19 UTC, youngbupark commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +| `ucp.tag`                  |  radius.azurecr.io/appcore-rp | set this variable to tag of radius rp image                                      |
At least, we need to make the image and tag name consistent with those in our chart.

https://github.com/project-radius/radius/blob/fb2a1d0b7e283b0053ad02d1aaeab2ca2512b55f/deploy/Chart/values.yaml#L1-L14

2023-03-30 17:20 UTC, jasonviviano commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +|`rp.publicEndpointOverride` | ""      |set this variable to the public endpoint of the Kubernetes cluster |
Should the default value here be `None` like in `global.zipkin.url` above or ""?

2023-03-30 17:28 UTC, nithyatsu commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +| `ucp.tag`                  |  radius.azurecr.io/appcore-rp | set this variable to tag of radius rp image                                      |
just updated, did not realize I made all image/ tag have same values and description.

2023-03-30 17:43 UTC, nithyatsu commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +|`rp.publicEndpointOverride` | ""      |set this variable to the public endpoint of the Kubernetes cluster |
here it is "". For global.zipkin.url, setting it enables the feature AND provides the trace url.

2023-03-30 17:44 UTC, nithyatsu commented on docs/content/operations/platforms/kubernetes/kubernetes-install.md
> +`rad install kubernetes --set global.zipkin.url=http://jaeger-collector.radius-monitoring.svc.cluster.local:9411/api/v2/spans,rp.publicEndpointOverride=localhost:8081`
updated

2023-03-30 17:50 UTC, AaronCrawfis approved these changes

2023-03-30 17:53 UTC, merged