Categorize by both category and tags
radius-project/docs pull request #534
Opened 2023-04-07 23:31 UTC by Reshrahim

Thank you for helping make the Radius documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.radapp.dev/contributing/docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

This PR covers the next iteration of leveraging taxonomies in our docs

1. Added categories to determine the type of document (Quickstart/Reference-app/How-to). Separate iteration can be done to cover other types of docs (Concepts doc, schema doc etc)

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/61033581/230691605-a427a841-5f0f-433a-8698-9ae7085da7d8.png">

2. Added shortcode to categorize by the type of document (Category) and also by content metadata (Tags)

- Categorize quickstarts by tags 
  ![image](https://user-images.githubusercontent.com/61033581/230691731-4f45722a-2b9e-4524-8cdf-c2d879847b98.png)

- Categorize reference-apps by tags 
- ![image](https://user-images.githubusercontent.com/61033581/230691813-b58da9db-41f1-4ab6-a46d-648b65c8f16d.png)

-  Categorize all types of docs by a tag 
- ![image](https://user-images.githubusercontent.com/61033581/230691850-58fbc839-0d11-4069-88b3-55d8710962b9.png)

## Issue reference
#515

2023-04-08 01:09 UTC, AaronCrawfis commented
This is AWESOME!

As part of this, could we update the docs contribution guidelines with definitions of what is a quickstart, and what is a how-to guide? I'm wondering if we might find they are pretty similar and we could maybe combine them 🤔. But not sure. We might also find they serve separate purposes.

2023-04-10 15:41 UTC, Reshrahim commented
> This is AWESOME!
> 
> As part of this, could we update the docs contribution guidelines with definitions of what is a quickstart, and what is a how-to guide? I'm wondering if we might find they are pretty similar and we could maybe combine them 🤔. But not sure. We might also find they serve separate purposes.

Good point to clarify the definition of Quickstart and How-to. IMO, Quickstarts are guides to quickly learn and understand something in 3-5 mins while How-to's are guides that can be elaborate, cover advanced topics, and help the reader understand the nuances and details of a particular feature/topic area. Quickstarts are a subset of how-to's but they can cater to a different purpose than how-to's on the depth of a feature/area

2023-05-15 18:19 UTC, AaronCrawfis commented on docs/content/author-apps/container/index.md
> +
Extra new line

2023-05-15 18:19 UTC, AaronCrawfis commented on docs/content/contributing/contributing-docs.md
> +#### Categorize content
Headers should have a newline underneath

2023-05-15 18:19 UTC, AaronCrawfis commented on docs/content/getting-started/quickstarts/_index.md
> +
Extra new line

2023-05-15 23:10 UTC, AaronCrawfis commented on docs/content/contributing/contributing-docs.md
> +### Contributing a new Reference-app
```suggestion
### Contributing a new Reference-app

```

2023-05-15 23:11 UTC, AaronCrawfis commented on docs/content/contributing/contributing-docs.md
> +tags: "METADATA ON THE DOCUMENT"
What would it look like if a document had 2 or more tags?

2023-05-15 23:11 UTC, AaronCrawfis commented on docs/content/contributing/contributing-docs.md
> +tags: "METADATA ON THE DOCUMENT"
Ah see the note below, way ahead of me :)

2023-05-15 23:15 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/aws-rds/index.md
> +categories: "Reference-app"
```suggestion
categories: "Reference application"
```

2023-05-15 23:15 UTC, AaronCrawfis commented on docs/content/contributing/contributing-docs.md
> +    - Reference app
```suggestion
    - Reference application
```

2023-05-15 23:15 UTC, AaronCrawfis commented on docs/content/contributing/contributing-docs.md
> +    - How to
```suggestion
    - How-To
```

2023-05-15 23:15 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/aws-s3/_index.md
> +categories: "Reference-app"
```suggestion
categories: "Reference application"
```

2023-05-15 23:15 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/container-app-store/index.md
This file was removed in a previous PR. I'd make sure you've pulled the latest 'edge' branch. If so I'd delete this directory

2023-05-15 23:15 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/eshop-dapr/_index.md
> +categories: "Reference-app"
```suggestion
categories: "Reference application"
```

2023-05-15 23:15 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/eshop/_index.md
> +categories: "Reference-app"
```suggestion
categories: "Reference application"
```

2023-05-15 23:15 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/eshop/_index.md
> +categories: "Reference-app"
```suggestion
categories: "Reference application"
```

2023-05-15 23:17 UTC, AaronCrawfis requested changes
Looking good! I'm thinking for the categories, "Reference application" would be better without the - and with app spelled out.

And for How-To, we've been capitalizing both words in the docs themselves. We should probably be consistent in the metadata as well.

2023-05-15 23:17 UTC, AaronCrawfis commented on docs/content/operations/platforms/kubernetes/kubernetes-metadata/index.md
> +categories: "How-to"
```suggestion
categories: "How-To"
```

2023-05-16 14:57 UTC, Reshrahim commented on docs/content/getting-started/reference-apps/container-app-store/index.md
removed it!

2023-05-16 15:30 UTC, AaronCrawfis approved these changes

2023-05-16 15:31 UTC, merged