Concepts Page sub-menu links changed
radius-project/docs pull request #539
Opened 2023-04-17 15:15 UTC by jasonviviano

Thank you for helping make the Radius documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.radapp.dev/contributing/docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Addressed a customer issue with the current layout of the Concepts Page and its sub-menu in each page by making sure the sub-menu in each page followed the Concepts Page menu flow.

From Architecture -> First-App

## Issue reference

https://github.com/project-radius/docs/issues/530

2023-04-24 16:45 UTC, willtsai commented on docs/content/concepts/environments-concept/_index.md
> +{{< button text="Links" page="links-concept" size="btn-lg" color="success" >}}
```suggestion
{{< button text="Radius Links" page="links-concept" size="btn-lg" color="success" >}}
```

2023-04-24 16:45 UTC, jasonviviano commented on docs/content/concepts/links-concept/_index.md
> +{{< button text="Learn about the Radius architecture" page="architecture" size="btn-lg" color="success" >}}
```suggestion
{{< button text="Radius architecture" page="architecture" size="btn-lg" color="success" >}}
```

2023-04-24 16:46 UTC, willtsai commented
Suggestion: remove verbs (e.g. "Learn about") from the buttons as the call to action is already specified in the introductory lines.

2023-04-24 17:24 UTC, AaronCrawfis requested changes

2023-04-24 17:24 UTC, AaronCrawfis commented on docs/content/concepts/appmodel-concept/_index.md
> +Now that you have an understanding of the Radius app model, learn more about the Radius environment:
```suggestion
Now that you have an understanding of the Radius app model, learn more about the Radius Environments:
```

2023-04-25 00:03 UTC, willtsai commented on docs/content/concepts/overview/_index.md
> +{{< button text="Learn about the Radius application model" page="appmodel-concept" size="btn-lg" color="success" >}}
should the "Radius app model" be referred to as the "Radius application graph" now?

2023-04-25 00:47 UTC, AaronCrawfis commented on docs/content/concepts/overview/_index.md
> +{{< button text="Learn about the Radius application model" page="appmodel-concept" size="btn-lg" color="success" >}}
Eventually yes, but not part of this PR

2023-05-15 18:20 UTC, AaronCrawfis commented on docs/content/concepts/architecture/index.md
> +{{< button text="Radius Demo" page="first-app" size="btn-lg" color="success" >}}
```suggestion
{{< button text="Get started" page="first-app" size="btn-lg" color="success" >}}
```

2023-05-15 18:22 UTC, willtsai submitted a review, later dismissed

2023-05-15 18:22 UTC, AaronCrawfis approved these changes

2023-05-15 18:26 UTC, merged