Updated param `location` to create a consistent description and updated schema references
radius-project/docs pull request #545
Opened 2023-04-20 14:50 UTC by jasonviviano

Thank you for helping make the Radius documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.radapp.dev/contributing/docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Removed `location` if usage was `resourceGroup().location` or `global` and updated schema references.
Left `location` in snippets that specified locations like `westus2`.

## Issue reference
https://github.com/project-radius/docs/issues/544

2023-04-20 14:59 UTC, AaronCrawfis commented on docs/content/author-apps/cloud-resources/azure-resources/snippets/azure-connection.bicep
> -  location: location
While Radius resources no longer need `location`, Azure resources still do. I'd keep all of the location params/properties for anything that's an Azure resource

2023-04-20 14:59 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/core-schema/application-schema/_index.md
> +| location | n | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
Good catch on these!

2023-04-20 15:00 UTC, AaronCrawfis requested changes
Thanks for getting this in! 

Azure resources actually still need locations. Could you restore all the params/properties for Azure resources?

Markdown fixes were a good catch, thanks! Those we should definitely fix as part of this PR

2023-04-20 15:17 UTC, jasonviviano commented on docs/content/author-apps/cloud-resources/azure-resources/snippets/azure-connection.bicep
> -  location: location
Fixed! Added/changed old descriptions to the one used in the `location` param table

2023-04-24 17:21 UTC, AaronCrawfis commented on docs/content/author-apps/cloud-resources/azure-resources/snippets/azure-connection.bicep
> +@description('The geo-location where the resource lives.')
Let's do something like:

```suggestion
@description('The Azure region to deploy Azure resource(s) into. Defaults to the region of the target Azure resource group.')
```

`geo-location` isn't a well-defined term.

2023-05-15 18:11 UTC, jasonviviano commented on docs/content/author-apps/links/snippets/redis-azure.bicep
> +@description('The geo-location where the resource lives.')
```suggestion
@description('The Azure region to deploy Azure resource(s) into. Defaults to the region of the target Azure resource group.')
```

2023-05-15 18:11 UTC, jasonviviano commented on docs/content/concepts/links-concept/snippets/corerp-link-example.bicep
> +@description('The geo-location where the resource lives.')
```suggestion
@description('The Azure region to deploy Azure resource(s) into. Defaults to the region of the target Azure resource group.')
```

2023-05-15 18:11 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-container-wi/snippets/container-wi.bicep
> +@description('The geo-location where the resource lives.')
```suggestion
@description('The Azure region to deploy Azure resource(s) into. Defaults to the region of the target Azure resource group.')
```

2023-05-15 18:11 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-dapr/dapr-microservices-add-dapr/snippets/dapr-azure.bicep
> +@description('The geo-location where the resource lives.')
```suggestion
@description('The Azure region to deploy Azure resource(s) into. Defaults to the region of the target Azure resource group.')
```

2023-05-15 18:11 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-dapr/dapr-microservices-add-dapr/snippets/statestore-azure.bicep
> +@description('The geo-location where the resource lives.')
```suggestion
@description('The Azure region to deploy Azure resource(s) into. Defaults to the region of the target Azure resource group.')
```

2023-05-15 18:12 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-dapr/dapr-microservices-add-ui/snippets/dapr-azure.bicep
> +@description('The geo-location where the resource lives.')
```suggestion
@description('The Azure region to deploy Azure resource(s) into. Defaults to the region of the target Azure resource group.')
```

2023-05-15 18:12 UTC, jasonviviano commented on docs/content/getting-started/quickstarts/quickstart-keyvault-wi/snippets/keyvault-wi.bicep
> +@description('The geo-location where the resource lives.')
```suggestion
@description('The Azure region to deploy Azure resource(s) into. Defaults to the region of the target Azure resource group.')
```

2023-05-15 18:12 UTC, jasonviviano commented on docs/content/getting-started/supported-languages/bicep/bicep-infrastructure/snippets/new.bicep
> +@description('The geo-location where the resource lives.')
```suggestion
@description('The Azure region to deploy Azure resource(s) into. Defaults to the region of the target Azure resource group.')
```

2023-05-15 18:12 UTC, jasonviviano commented on docs/content/operations/custom-recipes/snippets/recipe-params.bicep
> +@description('The geo-location where the resource lives.')
```suggestion
@description('The Azure region to deploy Azure resource(s) into. Defaults to the region of the target Azure resource group.')
```

2023-05-15 18:12 UTC, jasonviviano commented on docs/content/operations/custom-recipes/snippets/recipe.bicep
> +@description('The geo-location where the resource lives.')
```suggestion
@description('The Azure region to deploy Azure resource(s) into. Defaults to the region of the target Azure resource group.')
```

2023-05-15 18:12 UTC, jasonviviano commented on docs/content/reference/resource-schema/core-schema/volumes/volume-azure-keyvault/snippets/volume-keyvault.bicep
> +@description('The geo-location where the resource lives.')
```suggestion
@description('The Azure region to deploy Azure resource(s) into. Defaults to the region of the target Azure resource group.')
```

2023-05-15 18:12 UTC, jasonviviano commented on docs/content/reference/resource-schema/link-schema/dapr-schema/dapr-pubsub/snippets/dapr-pubsub-servicebus.bicep
> +@description('The geo-location where the resource lives.')
```suggestion
@description('The Azure region to deploy Azure resource(s) into. Defaults to the region of the target Azure resource group.')
```

2023-05-15 18:13 UTC, jasonviviano commented on docs/content/reference/resource-schema/link-schema/dapr-schema/dapr-statestore/snippets/dapr-statestore-sql.bicep
> +@description('The geo-location where the resource lives.')
```suggestion
@description('The Azure region to deploy Azure resource(s) into. Defaults to the region of the target Azure resource group.')
```

2023-05-15 18:13 UTC, jasonviviano commented on docs/content/reference/resource-schema/link-schema/dapr-schema/dapr-statestore/snippets/dapr-statestore-tablestorage.bicep
> +@description('The geo-location where the resource lives.')
```suggestion
@description('The Azure region to deploy Azure resource(s) into. Defaults to the region of the target Azure resource group.')
```

2023-05-15 18:54 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/core-schema/httproute/index.md
> +| location | n | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```suggestion
| location | y | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```

For now let's keep this as 'y', as it's required on-the-wire. We'll follow up with another PR updating this text with the nuance later.

2023-05-15 18:54 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/dapr-schema/dapr-http/index.md
> +| location | n | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```suggestion
| location | y | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```

2023-05-15 18:55 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/dapr-schema/dapr-pubsub/_index.md
> +| location | n | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```suggestion
| location | y | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```

2023-05-15 18:55 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/cache/redis/index.md
> +| location | n | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```suggestion
| location | y | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```

2023-05-15 18:55 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/dapr-schema/dapr-statestore/_index.md
> +| location | n | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```suggestion
| location | y | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```

2023-05-15 18:56 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/messaging/rabbitmq/index.md
> +| location | n | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```suggestion
| location | y | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```

2023-05-15 18:57 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/extender/_index.md
> +| location | n | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```suggestion
| location | y | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```

2023-05-15 18:57 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/databases/mongodb/index.md
> +| location | n | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```suggestion
| location | y | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```

2023-05-15 18:57 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/databases/microsoft-sql/index.md
> +| location | n | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```suggestion
| location | y | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```

2023-05-15 18:57 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/core-schema/gateway/index.md
> +| location | n | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```suggestion
| location | y | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```

2023-05-15 18:57 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/core-schema/application-schema/_index.md
> +| location | n | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```suggestion
| location | y | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```

2023-05-15 18:58 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/core-schema/container-schema/_index.md
> +| location | n | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```suggestion
| location | y | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```

2023-05-15 18:58 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/core-schema/environment-schema/index.md
> +| location | n | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```suggestion
| location | y | The location of your resource. See [common values]({{< ref "resource-schema.md#common-values" >}}) for more information. | `global`
```

2023-05-15 18:58 UTC, AaronCrawfis approved these changes

2023-05-15 19:07 UTC, merged

2023-05-16 18:22 UTC, kachawla reviewed
:shipit: