Update cloud provider docs
radius-project/docs pull request #567
Opened 2023-05-11 22:20 UTC by Reshrahim

Thank you for helping make the Radius documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.radapp.dev/contributing/docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description
Remove 'rad env init' reference and update the reinstall commands for adding a cloud provider to existing env

## Issue reference

2023-05-11 22:22 UTC, Reshrahim commented on docs/content/operations/providers/index.md
> +1. Select "yes" to add a cloud provider and select Azure as the cloud provider
```suggestion
1. Select "yes" to add a cloud provider and select AWS as the cloud provider
```

2023-05-15 18:32 UTC, AaronCrawfis commented on docs/content/operations/providers/index.md
>  #### Add a cloud provider to an AKS cluster using AAD pod identity
Let's actually remove this section altogether, it's no longer applicable

2023-05-15 19:38 UTC, Reshrahim commented on docs/content/operations/providers/index.md
>  #### Add a cloud provider to an AKS cluster using AAD pod identity
removed

2023-05-16 02:41 UTC, AaronCrawfis requested changes

2023-05-16 02:41 UTC, AaronCrawfis commented on docs/content/operations/providers/index.md
> +1. Select the kubernetes cluster to install Radius. Enter an environment name and namespace to deploy the apps into. Note that this namespace is used for application deployments.
```suggestion
1. Select the Kubernetes cluster to install Radius into. Enter an environment name and base Kubernetes namespace to deploy the apps into.
```

2023-05-16 02:41 UTC, AaronCrawfis commented on docs/content/operations/providers/index.md
> +1. Create an [Azure service principal](https://docs.microsoft.com/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-create-for-rbac) with the [proper permissions](https://aka.ms/azadsp-more).
```suggestion
1. Create an [Azure service principal](https://learn.microsoft.com/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-create-for-rbac) with the [proper permissions](https://aka.ms/azadsp-more). 
```

2023-05-16 02:41 UTC, AaronCrawfis commented on docs/content/operations/providers/index.md
> +   az ad sp create-for-rbac --role Owner --scope --scope /subscriptions/<subscriptionid>/resourceGroups/<resourcegroupname>
```suggestion
   az ad sp create-for-rbac --role Owner --scope /subscriptions/<subscriptionid>/resourceGroups/<resourcegroupname> 
```

2023-05-16 02:41 UTC, AaronCrawfis commented on docs/content/operations/providers/index.md
> +   Replace it with your subscription id and resource group name
```suggestion
   Make sure to update the command with your subscription id and resource group name
```

2023-05-16 02:41 UTC, AaronCrawfis commented on docs/content/operations/providers/index.md
> +1. Update your environment with your Azure subscription and resource group
```suggestion
1. Update your environment with your Azure subscription and resource group. This is where Azure resources will be deployed.
```

2023-05-16 02:41 UTC, AaronCrawfis commented on docs/content/operations/providers/index.md
> +1. Select the kubernetes cluster to install Radius. Enter an environment name and namespace to deploy the apps into. Note that this namespace is used for application deployments.
```suggestion
1. Select the Kubernetes cluster to install Radius into. Enter an environment name and base Kubernetes namespace to deploy the apps into.
```

2023-05-16 15:44 UTC, AaronCrawfis approved these changes

2023-05-16 17:35 UTC, merged