Update Redis docs for default recipe support
radius-project/docs pull request #575
Opened 2023-05-17 22:26 UTC by sk593

Thank you for helping make the Radius documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.radapp.dev/contributing/docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

## Issue reference

2023-05-18 18:15 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/cache/redis/index.md
> +### Recipe
```suggestion
### Recipe

```

Markdown headers should have newlines underneath

2023-05-18 18:15 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/cache/redis/index.md
> +### Resources
```suggestion
### Resources

```

2023-05-18 18:16 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/cache/redis/snippets/redis-resource.bicep
> +    }
In this example you're using a mix of Azure Cache for Redis and a Kubernets-based redis. Let's stick with Azure Cache for Redis

2023-05-18 18:18 UTC, AaronCrawfis commented on docs/content/author-apps/links/snippets/redis-azure.bicep
>    }
Could you also add the secrets here as well please?

2023-05-18 18:18 UTC, AaronCrawfis requested changes
Could you also update the custom recipes docs page under admin guides to talk about the default recipe behavior?

2023-05-22 19:37 UTC, AaronCrawfis requested changes
Couple small notes, but overall looking good!

2023-05-22 19:37 UTC, AaronCrawfis commented on docs/content/operations/custom-recipes/_index.md
>  {{< tabs Values Resource >}}
You can get rid of the tabs/codetab shortcodes altogether now that there's only one option

2023-05-22 19:37 UTC, AaronCrawfis commented on docs/content/operations/custom-recipes/_index.md
> +Recipes allow you to specify `values`:
```suggestion
Using the `values` output parameter, you can pass back information about your infrastructure.
```

2023-05-22 19:37 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/cache/redis/snippets/redis-resource.bicep
> +      password: '**************'
Instead of stars could we have this match the other example where we just specify password?

2023-05-22 19:37 UTC, AaronCrawfis requested changes
Couple small notes, but overall looking good!

2023-05-22 20:46 UTC, sk593 commented on docs/content/operations/custom-recipes/_index.md
> +Recipes allow you to specify `values`:
Fixed

2023-05-22 20:46 UTC, sk593 commented on docs/content/operations/custom-recipes/_index.md
>  {{< tabs Values Resource >}}
Fixed

2023-05-22 20:46 UTC, sk593 commented on docs/content/reference/resource-schema/link-schema/cache/redis/snippets/redis-resource.bicep
> +      password: '**************'
Sure, updated this

2023-05-22 20:54 UTC, AaronCrawfis requested changes

2023-05-22 20:54 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/cache/redis/snippets/redis-resource.bicep
> +      connectionString: azureRedis.listConnectionStrings()[0].connectionString
I don't believe these are right. Could you check to make sure this is the correct function call?

And I think we can remove connectionString as it's a computed value

2023-05-22 20:54 UTC, AaronCrawfis commented on docs/content/author-apps/links/snippets/redis-azure.bicep
> +      password: azureRedis.listPasswords()[0].password
Could you doublecheck that this is a supported function call?

2023-05-22 21:07 UTC, sk593 commented on docs/content/reference/resource-schema/link-schema/cache/redis/snippets/redis-resource.bicep
> +      connectionString: azureRedis.listConnectionStrings()[0].connectionString
Fixed

2023-05-22 21:07 UTC, sk593 commented on docs/content/author-apps/links/snippets/redis-azure.bicep
> +      password: azureRedis.listPasswords()[0].password
Fixed

2023-05-22 21:08 UTC, AaronCrawfis submitted a review, later dismissed

2023-05-22 23:34 UTC, AaronCrawfis approved these changes

2023-05-22 23:35 UTC, merged