Update Sql docs for default recipe support
radius-project/docs pull request #588
Opened 2023-05-24 21:12 UTC by vishwahiremat

Thank you for helping make the Radius documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.radapp.dev/contributing/docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Updating the sql docs for default recipe experience on sql databases.
Radius PR: https://github.com/project-radius/radius/pull/5572

## Issue reference

2023-05-25 19:56 UTC, AaronCrawfis requested changes

2023-05-25 19:56 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/databases/microsoft-sql/snippets/sql-resource.bicep
> +    database: 'https://sql.contoso.com'
Instead of using hard-coded strings could we instead use resource references using the `sqldb` param? We may need to use an extra existing resource here.

2023-05-25 19:57 UTC, AaronCrawfis commented
Could you also update the description to point to the PR in the radius repo where the code changes are going in? That way we can merge this after the code changes go in. Thanks!

2023-05-26 03:37 UTC, vishwahiremat commented on docs/content/reference/resource-schema/link-schema/databases/microsoft-sql/snippets/sql-resource.bicep
> +    database: 'https://sql.contoso.com'
we cannot get the resource reference using sqldb param as its a string param. do you mean we should add new params for server and database?

2023-05-26 22:29 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/databases/microsoft-sql/snippets/sql-resource.bicep
> +    database: 'https://sql.contoso.com'
I'd recommend using an `existing` resource. Might require changing the input parameter to be the resource name instead of the resource ID

2023-05-26 22:29 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/databases/microsoft-sql/snippets/sql-resource.bicep
> +    database: 'https://sql.contoso.com'
https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/existing-resource

2023-06-01 20:43 UTC, AaronCrawfis approved these changes

2023-06-01 20:43 UTC, merged