Update bicpe and docs for adding sql secrets
radius-project/docs pull request #620
Opened 2023-06-15 17:12 UTC by vishwahiremat

Radius PR: https://github.com/project-radius/radius/pull/5707

2023-06-15 17:47 UTC, AaronCrawfis requested changes

2023-06-15 17:47 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/databases/microsoft-sql/index.md
> +| port | n | The MongoDB port. | `1433`
```suggestion
| port | n | The port of the SQL server. | `1433`
```

2023-06-15 17:47 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/databases/microsoft-sql/index.md
> +| connectionString | n | The connection string for the SQL database. Write only. | `'https://mymongo.cluster.svc.local,password=*****,....'`
```suggestion
| connectionString | n | The connection string for the SQL database. Write only. | `'https://mysqlserver.cluster.svc.local,password=*****,....'`
```

2023-06-15 17:47 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/databases/microsoft-sql/index.md
> +
```suggestion
```

2023-06-15 17:47 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/databases/microsoft-sql/snippets/sql-resource.bicep
> +    port: port
Are you able to get port from the sqldb resource instead of using a param?

2023-06-15 17:47 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/databases/microsoft-sql/snippets/sql-resource.bicep
> +    secrets:{
Could you add connectionString here as well?

2023-06-15 17:47 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/databases/microsoft-sql/snippets/sql-values.bicep
Could you consolidate this with the other? Since we no longer have resource-backed support you can delete the sql-resource.bicep file and replace it with sql-recipe.bicep and then show in the doc both manual and recipe support. @jasonviviano can help

2023-06-16 06:26 UTC, vishwahiremat commented on docs/content/reference/resource-schema/link-schema/databases/microsoft-sql/snippets/sql-resource.bicep
> +    port: port
no i couldnt find a way to get port from sqldb. i dont see it in properties.

2023-06-16 16:04 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/databases/microsoft-sql/snippets/sql-resource.bicep
> +    port: port
Ah gotcha, in that case could you make it a var instead of a param? Sounds like it's something that a user would never need to pass in and change

2023-06-16 16:07 UTC, AaronCrawfis requested changes

2023-06-16 16:07 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/databases/microsoft-sql/index.md
Could you work with @jasonviviano on updating this PR with recipe support please?

2023-06-19 17:28 UTC, vishwahiremat commented on docs/content/reference/resource-schema/link-schema/databases/microsoft-sql/snippets/sql-values.bicep
its is added in this pr : https://github.com/project-radius/docs/pull/618

2023-06-19 17:39 UTC, AaronCrawfis approved these changes

2023-06-19 17:42 UTC, merged