Add new application graph concept page
radius-project/docs pull request #642
Opened 2023-07-06 18:00 UTC by AaronCrawfis

This PR adds a new application graph concept page, aligning with our new messaging.

It also removes the old app model page

2023-07-10 23:19 UTC, willtsai reviewed
left some nitpicky, wordsmithing suggestions for you to consider.

2023-07-10 23:19 UTC, willtsai commented on docs/content/concepts/application-graph/index.md
> +Radius adds a new [application resource]({{< ref "/author-apps/application" >}}) which app teams can use to define their entire application. This includes all the compute, data, and infrastructure th
```suggestion
Radius introduces the concept of an [application resource]({{< ref "/author-apps/application" >}}), which development teams can use to define and then deploy their entire applications. This includes all the compute, data, and infrastructure that makes up an application. Since Radius applications are defined as a graph of relationships between deployed resources, it enables more advanced visualizations than simply a list of resources.
```

2023-07-10 23:19 UTC, willtsai commented on docs/content/concepts/application-graph/index.md
> +Within a Radius application developers can express both the resources (_containers, databases, message queues, etc._), as well as all the relationships between them. This forms the Radius application
```suggestion
Within an application deployed using Radius, developers can express both the resources (_containers, databases, message queues, etc._), as well as all the relationships between them. This means that in the process of building out your application, you end up with a Radius application graph without spending additional effort.
```

2023-07-10 23:19 UTC, willtsai commented on docs/content/concepts/application-graph/index.md
> +Now that you have an understanding of the Radius app graph, learn how you can deploy Radius application to prepared landing zones with Radius Environments:
```suggestion
Now that you have an understanding of the Radius app graph, learn how you can deploy Radius applications to prepared landing zones with Radius Environments:
```

2023-07-17 21:30 UTC, AaronCrawfis commented on docs/content/concepts/application-graph/index.md
> +Within a Radius application developers can express both the resources (_containers, databases, message queues, etc._), as well as all the relationships between them. This forms the Radius application
Tweaked this a bit, there is going to be effort in declaring the app graph. Developers will need to state all of their relationships, so it's more of declare once: get both automation and then the visualization for free.

2023-07-17 21:31 UTC, AaronCrawfis commented on docs/content/concepts/application-graph/index.md
> +Radius adds a new [application resource]({{< ref "/author-apps/application" >}}) which app teams can use to define their entire application. This includes all the compute, data, and infrastructure th
Reworded this a bit based on suggestion. However not sure "concept" is the right noun for describing the application resource, since a Radius application is an actual resource type that can be used. "Concept" to me sounds more intangible and not as concrete as the resource type. But happy to chat on this more to make sure we find the right balance between product truth and high-level concepts.

2023-07-24 18:41 UTC, willtsai requested changes
a few more wordsmithing suggestions

2023-07-24 18:41 UTC, willtsai commented on docs/content/concepts/application-graph/index.md
> +Radius offers an [application resource]({{< ref "/author-apps/application" >}}) which teams can use to define and deploy their entire application, including all of the compute, relationships, and inf
```suggestion
Radius offers an [application resource]({{< ref "/author-apps/application" >}}) which teams can use to define and deploy their entire application, including all of the compute, relationships, and infrastructure that make up the application. Since the graph of relationships between deployed resources is much more descriptive than a basic list of resources, the Radius application graph enables advanced visualizations.
```

2023-07-24 18:41 UTC, willtsai commented on docs/content/concepts/application-graph/index.md
> +Within an application deployed with Radius, developers can express both the resources (_containers, databases, message queues, etc._), as well as all the relationships between them. This forms the Ra
```suggestion
Within an application deployed with Radius, developers can express both the resources (_containers, databases, message queues, etc._), as well as all the relationships between them. This forms the Radius application graph. This graph is powerful because it allows Radius to understand the relationships between resources, and automate the deployment and configuration of your application. Plus, it allows you to visualize your application in a way that is more intuitive than a list of resources.
```

2023-07-24 18:41 UTC, willtsai commented on docs/content/concepts/application-graph/index.md
> +For example, today if you want a container to read from an Azure Storage Account, this normally requires creating managed identities, RBAC roles, identity federation, Kubernetes service accounts, and
```suggestion
For example, if you want a container to read from an Azure Storage Account without using Radius, this normally requires creating managed identities, RBAC roles, identity federation, Kubernetes service accounts, and more. With Radius, developers can define a single connection from their container to a Storage Account, and Radius sets up all the required configuration automatically.
```

2023-07-26 18:23 UTC, rynowak commented on docs/content/concepts/application-graph/index.md
> +## Mine the app graph API
Do we want to include an example of `rad app connections` as well now that it's checked in?

2023-08-01 00:00 UTC, willtsai approved these changes

2023-08-01 23:46 UTC, AaronCrawfis commented on docs/content/concepts/application-graph/index.md
> +## Mine the app graph API
Working on a connections-specific page that I'll definitely include that in. Once complete I'll also link to that from this page.

2023-08-01 23:46 UTC, merged