Update bicep and docs for updating rabbitmq schema
radius-project/docs pull request #649
Opened 2023-07-18 05:29 UTC by vishwahiremat

Radius PR: https://github.com/project-radius/radius/pull/5863

2023-07-24 16:16 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/messaging/rabbitmq/index.md
> +| username | n | Username to use when connecting to the target rabbitM. | `'myusername'`
Also once you add TLS please update this table

2023-07-31 18:12 UTC, willtsai commented
@vishwahiremat - please address the feedback from @AaronCrawfis and also the spellchecker. Adding the `waiting-on-code-pr` label as well.

2023-08-02 21:43 UTC, AaronCrawfis requested changes
Small spelling error. Also for the words failing spellcheck but that are correct please update the spelling configuration file under .github/config

2023-08-02 21:43 UTC, AaronCrawfis commented on docs/content/reference/resource-schema/link-schema/messaging/rabbitmq/index.md
> +| username | n | Username to use when connecting to the target rabbitM. | `'myusername'`
```suggestion
| username | n | Username to use when connecting to the target rabbitMQ. | `'myusername'`
```

2023-08-03 00:06 UTC, AaronCrawfis approved these changes

2023-08-03 01:18 UTC, merged