Remove quickstarts from docs
radius-project/docs pull request #683
Opened 2023-08-14 17:02 UTC by AaronCrawfis

This PR removes quickstarts, migrating the existing guides into how-to guides and tutorials.

Note that tutorials still need to be documented and contribution guides need to be written, as part of a follow-up PR.

2023-08-15 00:21 UTC, willtsai requested changes
some general feedback:
1. I feel that the `reference apps` section should be nested under `tutorials` given the similarity in the intent of the content
2. I'm torn on whether the `languages/bicep` section should be nested under `getting started` as it's a pretty nuanced topic, perhaps it fits better under `concepts`?

2023-08-15 00:21 UTC, willtsai commented on docs/content/tutorials/tutorial-dapr/index.md
> +For more details on the app and access to the source code, visit the `tutorials/dapr` directory in the [samples repo](https://github.com/project-radius/samples). _For access to the project-radius Git
Does the `samples/quickstarts/...` need to be renamed as well?

2023-08-15 00:21 UTC, willtsai commented on docs/content/getting-started/reference-apps/aws-sqs/_index.md
I think this file name is causing issues with how the side bar renders and resulting in the S3 page being blank:

<img width="259" alt="image" src="https://github.com/project-radius/docs/assets/28876888/4c57c481-690c-42a1-aa67-81926a739920">

2023-08-15 13:22 UTC, AaronCrawfis commented
> I feel that the reference apps section should be nested under tutorials given the similarity in the intent of the content

Reference apps are also going to be removed in an upcoming PR, with eShop becoming a tutorial. Still working out where to put the others (or remove them). But that will be a follow up PR.

> I'm torn on whether the languages/bicep section should be nested under getting started as it's a pretty nuanced topic, perhaps it fits better under concepts?

The Bicep page will be converted into a how-to guide (or overview) under deploying apps in a follow up PR. Wanted to focus on just removing quickstarts in this PR.

2023-08-15 13:23 UTC, AaronCrawfis commented on docs/content/getting-started/reference-apps/aws-sqs/_index.md
That's an existing issue that exists already on docs.radapp.dev. I can get that fixed when I go in to remove the reference apps in a follow up PR

2023-08-15 13:25 UTC, AaronCrawfis commented on docs/content/tutorials/tutorial-dapr/index.md
> +For more details on the app and access to the source code, visit the `tutorials/dapr` directory in the [samples repo](https://github.com/project-radius/samples). _For access to the project-radius Git
Yes the container image names will need to be updated, but that will require a PR into the samples repo and redoing the CI/CD systems. Opened an Issue to track as part of a follow up PR: https://github.com/project-radius/samples/issues/462

2023-08-18 23:46 UTC, AaronCrawfis commented
Closing in favor of #690

2023-08-18 23:46 UTC, closed without merging