Restructure docs
radius-project/docs pull request #690
Opened 2023-08-18 23:46 UTC by AaronCrawfis

This PR restructures the docs based on the new diataxis framework.

Content updates were minimal, only changing page content to make it fit the new framework.

There are many guides to be written so spots in the docs might be a little sparse, but we'll fill them in.

2023-08-18 23:57 UTC, Reshrahim commented on docs/content/author-apps/howto-vscode/index.md
> +---
Can we move this page to a higher level section on "installation"

2023-08-18 23:58 UTC, Reshrahim commented on docs/content/deploy-apps/howto-rad-cli/index.md
> +---
This also makes a good page for top level "installation" section

2023-08-21 23:30 UTC, willtsai requested changes
One minor change suggested. Reviewed "First app" in detail and the other pages/menu bar at a higher level. New structure looks great and provides a great framework for us to continue building upon!

2023-08-21 23:30 UTC, willtsai commented on docs/content/getting-started/index.md
> +Next, update your container definition to include `connections` inside `properties`. This code creates a connection between the container and the database. Based on this connection, Radius will [inje
nitpick for first app experience:

```suggestion
Next, update your container definition to include `connections` inside `properties`. This code creates a connection between the container and the database. Based on this connection, Radius will [inject environment variables]({{< ref "/guides/author-apps/containers/overview#connections" >}}) into the container that inform the container how to connect. You will view these in the next step.
```

2023-08-22 15:47 UTC, Reshrahim requested changes
Overall the new structure is great!!. Suggested some changes on removing "how-to" in the link title and making the title task oriented.

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/community/contributing/contributing-docs/index.md
> +linkTitle: "How-To: Contribute docs"
```suggestion
linkTitle: "Contribute to docs"
```

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/community/maintainers/docs-maintainers.md
> +linkTitle: "How-To: Maintain docs"
```suggestion
linkTitle: "Maintain docs"
```

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/guides/author-apps/aws/howto-aws-resources/index.md
> +linkTitle: "How-To: Use AWS resources"
```suggestion
linkTitle: "Deploy AWS resources"
```

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/guides/author-apps/azure/howto-azure-resources/index.md
> +linkTitle: "How-To: Use Azure resources"
```suggestion
linkTitle: "Deploy Azure resources"
```

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/guides/author-apps/containers/howto-environment-variables/index.md
> +linkTitle: "How-To: Env vars"
```suggestion
linkTitle: "Set Env vars"
```

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/guides/author-apps/containers/howto-keyvault-volume/index.md
> +linkTitle: "How-To: Mount a Key Vault"
```suggestion
linkTitle: "Mount a Key Vault"
```

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/guides/author-apps/containers/howto-volumes/index.md
> +linkTitle: "How-To: Volumes"
```suggestion
linkTitle: "Mount a volume"
```

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/guides/author-apps/howto-vscode/index.md
> +linkTitle: "How-To: VS Code"
```suggestion
linkTitle: "Install VS Code extension"
```

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/guides/deploy-apps/howto-cicd/index.md
> +linkTitle: "How-To: GitHub Actions"
```suggestion
linkTitle: "Deploy with GitHub Actions"
```

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/guides/deploy-apps/howto-delete/index.md
> +linkTitle: "How-To: Delete apps"
```suggestion
linkTitle: "Delete apps"
```

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/guides/deploy-apps/howto-deploy/index.md
> +linkTitle: "How-To: Deploy apps"
```suggestion
linkTitle: "Deploy apps"
```

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/guides/deploy-apps/howto-rad-cli/index.md
> +linkTitle: "How-To: rad CLI"
```suggestion
linkTitle: "Install rad CLI"
```

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/guides/operations/kubernetes/_index.md
> +categories: "How-To"
```suggestion
```

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/guides/operations/providers/howto-cloud-providers/index.md
> +linkTitle: "How-To: Setup providers"
```suggestion
linkTitle: "Setup Cloud providers"
```

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/guides/operations/workspaces/howto-workspaces/index.md
> +linkTitle: "How-To: Workspaces"
```suggestion
linkTitle: "Use Workspaces"
```

2023-08-22 15:47 UTC, Reshrahim commented on docs/content/guides/recipes/howto-author-recipes/index.md
> +linkTitle: "How-To: Author Recipes"
```suggestion
linkTitle: "Author Recipes"
```

2023-08-22 15:57 UTC, jasonviviano commented on docs/content/guides/author-apps/application/overview/index.md
> +title: "Overview: Radius applications"
I think for the `title` leaving the name for all the sections that are accessed through diving into specific topics should probably stay as just "Overview" versus "Overview: Topic" makes more sense as the user should know by the time they click on Applications that the Overview page found here is for Applications.

2023-08-22 16:09 UTC, Reshrahim submitted a review, later dismissed

2023-08-22 16:09 UTC, Reshrahim commented on docs/content/guides/author-apps/howto-vscode/index.md
> +   <img src="./vsix-install.png" alt="Screenshot of installing a vsix extension" width=400>
Images are not rendering 
![image](https://github.com/project-radius/docs/assets/61033581/80317647-5fa1-48f1-9b16-0968455f5edc)

2023-08-22 16:09 UTC, Reshrahim commented on docs/content/guides/author-apps/howto-vscode/index.md
> +title: "How-To: Install the Radius-Bicep VSCode extension"
Should we move this content inside Installation page? This feels out of place under authoring

2023-08-22 16:10 UTC, willtsai submitted a review, later dismissed

2023-08-22 16:19 UTC, willtsai approved these changes
Approving the overall structure changes, we can open additional PRs to make changes to titles, ordering, etc.

2023-08-22 16:20 UTC, merged

2023-08-22 16:20 UTC, AaronCrawfis commented on docs/content/guides/author-apps/howto-vscode/index.md
> +   <img src="./vsix-install.png" alt="Screenshot of installing a vsix extension" width=400>
Fixed

2023-08-22 16:21 UTC, AaronCrawfis commented on docs/content/guides/author-apps/howto-vscode/index.md
> +title: "How-To: Install the Radius-Bicep VSCode extension"
Discussed in PM meeting, will pickup in PR to templatize this information and place it in both places